import {type Course, makeInterviewBuilder, makeMcqBuilder} from "./course-types";

// Round 1: Deep learning fundamentals every candidate should know cold —
// neurons/activations, forward/backward propagation, loss functions,
// optimizers, regularization, and the major architecture families (CNNs,
// RNNs/LSTMs, transformers) along with the practical realities of training
// (gradients, initialization, hardware).
const mcq = makeMcqBuilder("Deep Learning Fundamentals");

const round1Steps = [
  mcq(
    1,
    20,
    "What does a single artificial neuron (perceptron) compute before applying an activation function?",
    [
      "The median of its inputs",
      "A weighted sum of its inputs plus a bias term",
      "The product of all its inputs",
      "A random projection of its inputs",
    ],
    1,
    "A neuron computes z = w1x1 + w2x2 + ... + b, a weighted linear combination of inputs plus a bias, which is then passed through a nonlinear activation function.",
    "Think linear algebra: weights times inputs, summed, plus one extra learnable term.",
  ),
  mcq(
    2,
    20,
    "Sigmoid and tanh are both S-shaped activation functions. What is the main practical advantage of tanh over sigmoid?",
    [
      "Tanh outputs are zero-centered (range -1 to 1), which tends to make gradient-based learning in later layers better-behaved than sigmoid's 0-to-1, non-zero-centered output",
      "Tanh has no vanishing gradient problem at all, unlike sigmoid",
      "Tanh is always faster to compute than sigmoid",
      "Tanh can only be used in the output layer, never hidden layers",
    ],
    0,
    "Because tanh is centered at 0 and ranges from -1 to 1, its outputs don't push all downstream gradients to consistently have the same sign the way sigmoid's strictly positive outputs can, which often makes optimization converge a bit more smoothly.",
    "Compare the two functions' output ranges and where they're centered.",
  ),
  mcq(
    3,
    20,
    "Why has ReLU largely replaced sigmoid/tanh as the default hidden-layer activation in deep networks?",
    [
      "ReLU has no derivative, so training is skipped entirely",
      "ReLU avoids saturating gradients for positive inputs and is cheap to compute, which helps deep networks train faster",
      "ReLU always outputs values between -1 and 1",
      "ReLU guarantees the loss will reach zero",
    ],
    1,
    "For positive inputs ReLU's gradient is a constant 1 (no saturation), which mitigates vanishing gradients in deep networks, and it's just a max(0, x) operation, making it very cheap.",
    "Think about what happens to sigmoid/tanh gradients when inputs are very large or very small in magnitude.",
  ),
  mcq(
    4,
    20,
    "Which activation function is typically used in the output layer for multi-class classification with mutually exclusive classes?",
    ["Sigmoid", "ReLU", "Softmax", "Linear"],
    2,
    "Softmax converts a vector of raw scores (logits) into a probability distribution over classes that sums to 1, which is exactly what's needed when classes are mutually exclusive.",
    "You need an output that turns several scores into probabilities summing to one.",
  ),
  mcq(
    5,
    20,
    "What is the purpose of forward propagation in a neural network?",
    [
      "Updating the weights using gradients",
      "Computing the network's output/prediction by passing input data through the layers",
      "Randomly initializing the weights",
      "Splitting the dataset into train/test",
    ],
    1,
    "Forward propagation pushes input data through each layer's weights and activations in sequence to produce the network's final prediction, which is then compared to the true label to compute loss.",
    "It's the pass that goes from input to output, in the direction the data naturally flows.",
  ),
  mcq(
    6,
    20,
    "What is the core purpose of backpropagation?",
    [
      "To feed data into the network for the first time",
      "To efficiently compute the gradient of the loss with respect to every weight using the chain rule",
      "To normalize the input features",
      "To select the batch size",
    ],
    1,
    "Backpropagation applies the chain rule from calculus, working backward from the output loss through each layer, to compute how much each weight contributed to the error — these gradients are then used to update the weights.",
    "It's named for the direction it travels: backward from the loss to the earlier layers.",
  ),
  mcq(
    7,
    20,
    "Which pairing of loss function to task is correct?",
    [
      "Cross-entropy for regression, Mean Squared Error for classification",
      "Cross-entropy for classification (compares predicted vs true probability distributions), Mean Squared Error for regression (penalizes squared distance between continuous values)",
      "Both are only used for image data",
      "Cross-entropy and MSE are interchangeable for every task",
    ],
    1,
    "Cross-entropy measures how far a predicted probability distribution is from the true one-hot label distribution, making it the standard choice for classification, while MSE measures squared error between continuous predictions and targets, making it the standard choice for regression.",
    "Match each loss to the kind of target it was designed to compare: probabilities vs. continuous numbers.",
  ),
  mcq(
    8,
    20,
    "What is the key difference between plain Stochastic Gradient Descent (SGD) and the Adam optimizer?",
    [
      "Adam only works on CNNs, SGD only works on RNNs",
      "Adam adapts the learning rate per-parameter using estimates of first and second moments of the gradients, while plain SGD uses a single fixed step",
      "SGD requires no learning rate at all",
      "Adam does not use gradients",
    ],
    1,
    "Adam combines momentum (first moment) with an adaptive, per-parameter learning rate based on a running estimate of squared gradients (second moment), often converging faster than vanilla SGD, especially early in training.",
    "Adam's name is short for 'adaptive moment estimation' — think about what that implies it tracks.",
  ),
  mcq(
    9,
    20,
    "What does the learning rate control in gradient descent?",
    [
      "The number of layers in the network",
      "The size of the step taken in the direction of the negative gradient when updating weights",
      "The number of training examples per batch",
      "The choice of activation function",
    ],
    1,
    "The learning rate is a scalar multiplier on the gradient that determines how large each weight update step is; too high can overshoot/diverge, too low makes training very slow.",
    "It's the multiplier applied to the gradient before subtracting it from the weights.",
  ),
  mcq(
    10,
    20,
    "You have 10,000 training examples and a batch size of 100. How do epoch, batch, and iteration relate here?",
    [
      "One epoch = one iteration = one batch of 100 examples",
      "One epoch is a full pass over all 10,000 examples, made up of 100 iterations, each iteration processing one batch of 100 examples",
      "One epoch equals 10,000 iterations, each processing one example",
      "Batch size has no effect on the number of iterations per epoch",
    ],
    1,
    "An epoch is one complete pass through the dataset; splitting 10,000 examples into batches of 100 gives 100 batches, and processing each batch is one iteration (one weight update), so one epoch = 100 iterations here.",
    "Divide total examples by batch size to get the number of iterations per epoch.",
  ),
  mcq(
    11,
    20,
    "Which technique randomly disables a fraction of neurons during training to reduce overfitting?",
    ["Batch normalization", "Dropout", "Early stopping", "Data augmentation"],
    1,
    "Dropout randomly zeroes out a fraction of neuron activations on each training pass, forcing the network to not rely too heavily on any single neuron and effectively training an ensemble of subnetworks.",
    "The name describes literally what happens to some neurons on each pass.",
  ),
  mcq(
    12,
    20,
    "What is early stopping, as a regularization technique for neural networks?",
    [
      "Stopping training the moment training loss reaches zero",
      "Halting training once validation performance stops improving, even if training loss keeps decreasing",
      "Reducing the learning rate at the start of training",
      "Training for a fixed, very small number of epochs regardless of performance",
    ],
    1,
    "Early stopping monitors a held-out validation metric and stops training when it stops improving (or starts getting worse), which prevents the model from continuing to overfit the training data.",
    "It cares about validation performance, not training loss, as the stopping signal.",
  ),
  mcq(
    13,
    20,
    "What problem does Batch Normalization primarily address during training?",
    [
      "It compresses the model for deployment on mobile devices",
      "It stabilizes and speeds up training by normalizing layer inputs' distribution (mean/variance) within each mini-batch",
      "It removes the need for an activation function",
      "It replaces the loss function",
    ],
    1,
    "Batch normalization normalizes each layer's inputs to have roughly zero mean and unit variance per mini-batch (with learnable scale/shift), which reduces internal covariate shift and generally allows higher learning rates and faster, more stable convergence.",
    "The name tells you what statistic it's normalizing, computed per mini-batch.",
  ),
  mcq(
    14,
    20,
    "In a CNN, what does the convolution operation do, and why does this make CNNs well suited to images?",
    [
      "It slides a small learnable filter across the input to detect local patterns while sharing weights across positions, which exploits images' local spatial correlation and translation invariance far more efficiently than full connectivity",
      "It fully connects every pixel to every output neuron, which is the fastest possible option for images",
      "It randomly shuffles pixels to make the model more robust",
      "It removes color information before classification",
    ],
    0,
    "A convolution slides a small kernel across the input and reuses the same weights at every spatial position, so it can detect local patterns like edges anywhere in the image with far fewer parameters than a fully connected layer — exactly matching how useful visual patterns are local and can appear at any position. CNNs typically follow each convolution with a pooling layer (e.g. max pooling) to downsample the resulting feature maps, reducing computation and adding robustness to small translations.",
    "Think about a small window sliding across the image, reusing the same weights everywhere.",
  ),
  mcq(
    15,
    20,
    "Why is deep learning training typically done on GPUs (or TPUs) rather than CPUs?",
    [
      "GPUs have far more cores optimized for the massively parallel matrix/tensor multiplications that make up most of a neural network's forward and backward passes, giving huge speedups over a CPU's few general-purpose cores",
      "GPUs are simply cheaper than CPUs in every case",
      "CPUs cannot perform floating point arithmetic",
      "GPUs are required only for loading data from disk, not for computation",
    ],
    0,
    "Neural network training is dominated by large matrix multiplications and other tensor operations that decompose into many independent, parallelizable computations; GPUs (and TPUs) are built with thousands of simpler cores designed exactly for this kind of parallel workload, making them dramatically faster than CPUs for training and running deep networks.",
    "Think about what kind of math (matrix multiplication) dominates a forward/backward pass, and what hardware is built to parallelize that.",
  ),
  mcq(
    16,
    20,
    "Why do RNNs/LSTMs struggle with long sequences, and how does this relate to the vanishing gradient problem?",
    [
      "Gradients backpropagated through many time steps get repeatedly multiplied by small values, shrinking toward zero and preventing the network from learning long-range dependencies; LSTMs address this with gated, additive memory cells",
      "RNNs cannot process sequences longer than 10 steps under any circumstances",
      "Vanishing gradients only affect CNNs, not RNNs",
      "LSTMs remove the need for backpropagation entirely",
    ],
    0,
    "Because an RNN reuses the same weights at every time step, backpropagating through many steps multiplies the gradient by similar factors repeatedly, and if those factors are small the gradient vanishes before reaching early time steps; LSTMs mitigate this with a gated cell state that updates additively rather than through repeated multiplication.",
    "Think about what repeated multiplication of small numbers does over many time steps.",
  ),
  mcq(
    17,
    20,
    "What is the core idea behind the attention mechanism used in transformers?",
    [
      "Each element in a sequence computes a weighted combination of all other elements based on learned relevance (query/key/value), letting the model directly relate distant positions without a sequential hidden state",
      "Attention forces the model to only look at the very first token in a sequence",
      "Attention replaces the need for any training data",
      "Attention is a pooling operation identical to max pooling in CNNs",
    ],
    0,
    "Attention computes, for each token, a relevance score against every other token (via query/key comparisons) and uses those scores to weight a combination of value vectors, letting information flow directly between any two positions regardless of distance — unlike an RNN's step-by-step hidden state.",
    "Think 'each word looks at every other word and decides how much to weight it.'",
  ),
  mcq(
    18,
    20,
    "What is transfer learning, and why is it useful when you have limited labeled data?",
    [
      "Training a brand-new model from random weights on your small dataset only",
      "Reusing a model already pretrained on a large, related dataset (fine-tuning it or its features) so the new task benefits from previously learned general representations",
      "Manually copying predictions from one dataset to another",
      "A technique that only works when the new dataset is larger than the original one",
    ],
    1,
    "Transfer learning starts from a model pretrained on a large dataset, whose early layers have already learned general, reusable features; fine-tuning that model on a smaller target dataset typically reaches much better performance than training from scratch, since far less data is needed to adapt already-good representations.",
    "It's about reusing knowledge a model already learned elsewhere, not starting over.",
  ),
  mcq(
    19,
    20,
    "Why does weight initialization matter when training a deep neural network?",
    [
      "It has no real effect on training as long as the learning rate is correct",
      "Poor initialization (e.g. all zeros, or values too large/small) can cause vanishing or exploding gradients from the very first steps of training, so schemes like Xavier/He initialization are used to keep signal and gradient magnitudes stable across layers",
      "Weights only need to be initialized for the output layer",
      "Initialization determines the model's final accuracy regardless of training",
    ],
    1,
    "If weights start too small, activations and gradients shrink layer by layer (vanishing); if too large, they can grow uncontrollably (exploding); initialization schemes like Xavier (for tanh/sigmoid) or He (for ReLU) are designed to keep the variance of activations roughly stable across layers from the start.",
    "Think about what happens to signal magnitude layer after layer if the starting weights are too small or too large.",
  ),
  mcq(
    20,
    20,
    "In deep learning for NLP, what is the main advantage of learned embeddings over one-hot encoding for representing words?",
    [
      "One-hot encoding uses less memory than embeddings for large vocabularies",
      "Embeddings map words to dense, lower-dimensional vectors that can capture semantic similarity (similar words end up close together), whereas one-hot vectors are high-dimensional, sparse, and treat all words as equally dissimilar",
      "One-hot encoding captures word meaning better than embeddings",
      "Embeddings can only represent numbers, not words",
    ],
    1,
    "A one-hot vector is sparse and as long as the vocabulary, with every word equally distant from every other word, while a learned embedding is a dense, much lower-dimensional vector where geometric closeness reflects semantic or usage similarity, which is far more useful as input to a neural network.",
    "Compare vector size and whether 'distance' between two words' vectors means anything.",
  ),
];

// Round 2: open-ended interview questions a Deep Learning / ML Engineer
// candidate should be ready to answer out loud, with a thorough model
// answer to reveal and self-check against.
const interview = makeInterviewBuilder("deep-learning-interview", "Deep Learning Interview Prep");

const round2Steps = [
  interview(
    1,
    15,
    "Can you explain backpropagation intuitively, as if to someone who understands calculus but has never seen it applied to neural networks?",
    "Backpropagation is just the chain rule applied systematically, layer by layer, from the loss back to the earliest weights. During the forward pass the network computes a prediction and a loss; during the backward pass, we ask 'how much would the loss change if this weight changed a tiny bit,' and we compute that by multiplying local derivatives together as we walk backward through the computational graph, layer by layer. Each layer only needs to know the gradient flowing in from the layer after it and its own local derivative, which is what makes it efficient — you never have to recompute everything from scratch for each weight. The result is a gradient for every parameter in the network, which an optimizer like SGD or Adam then uses to nudge weights in the direction that reduces the loss.",
    "The interviewer wants to confirm you understand backprop as reused chain-rule calculus rather than a memorized black-box algorithm.",
    "Frame it as 'chain rule applied layer by layer, reusing local gradients as you go backward.'",
  ),
  interview(
    2,
    15,
    "Why do we need non-linear activation functions in neural networks — what would go wrong without them?",
    "If every layer applied only a linear transformation (a matrix multiply plus bias), then stacking any number of layers would still mathematically collapse into a single equivalent linear transformation, since the composition of linear functions is linear. That means a 100-layer network with no non-linearities would have no more representational power than a single-layer linear model — it couldn't learn curves, XOR-like patterns, or any complex decision boundary. Non-linear activations like ReLU or tanh are what let each layer bend the representation, so that depth actually buys you the ability to approximate arbitrarily complex functions.",
    "This tests whether you understand depth is only useful because of non-linearity, a foundational concept often glossed over.",
    "Point out that composed linear functions are still linear, no matter how many layers.",
  ),
  interview(
    3,
    15,
    "What causes vanishing gradients, and how do modern architectures like ResNets, LSTMs, and ReLU address it?",
    "Vanishing gradients happen when gradients are repeatedly multiplied by small numbers (like sigmoid/tanh derivatives, which max out around 0.25) as they're backpropagated through many layers or time steps, causing the gradient signal reaching early layers to shrink toward zero so those layers barely learn. ReLU helps because its gradient is a constant 1 for positive inputs, avoiding the systematic shrinkage that saturating activations cause. ResNets add skip/residual connections that let gradients flow directly through an identity path around blocks of layers, bypassing the multiplicative shrinkage entirely. LSTMs address the same problem in sequence models with gated memory cells and an additive cell-state update, which lets gradient information persist across many time steps instead of being repeatedly squashed by recurrent multiplication.",
    "The interviewer is checking that you understand the mechanism (repeated multiplication of small derivatives) and can name concrete architectural fixes, not just the term.",
    "Explain the repeated-multiplication mechanism first, then map one fix to each architecture named.",
  ),
  interview(
    4,
    15,
    "Explain the intuition behind attention and transformers in your own words.",
    "Attention lets a model decide, for each element in a sequence, which other elements are most relevant to it right now, by computing a weighted combination of all other elements' representations rather than relying on a fixed-size hidden state passed step by step. Concretely, each token produces a query, and is compared against every other token's key to get similarity scores, which are turned into weights (via softmax) used to combine the corresponding values — so a word like 'it' can directly attend to whichever earlier noun it refers to, regardless of distance. Transformers build entire architectures out of this mechanism (self-attention plus feedforward layers, stacked and combined with positional encodings since attention itself has no notion of order), which lets them process all positions in parallel rather than sequentially like an RNN, and capture long-range dependencies much more directly. This parallelism and long-range modeling is why transformers scaled so well and became the backbone of modern large language models.",
    "This tests whether you grasp attention as a content-based, all-pairs relevance mechanism rather than just knowing it's 'used in GPT/BERT.'",
    "Use the query/key/value framing and contrast the parallelism with RNNs' sequential processing.",
  ),
  interview(
    5,
    15,
    "How do you decide on network architecture depth and width when starting a new deep learning problem?",
    "I'd start from what's known to work for the data modality — a pretrained CNN backbone (e.g. ResNet/EfficientNet) for images, a transformer for text or sequences, rather than designing from scratch, since transfer learning almost always beats a hand-designed architecture on limited data. From there, depth/width choices are guided by dataset size (a small dataset can't support a huge model without overfitting), available compute/latency budget, and empirical iteration: start with a smaller/shallower baseline, check whether it's underfitting (in which case add capacity) or overfitting (add regularization or reduce capacity), and use validation curves to guide the decision rather than guessing up front. I'd also lean on established scaling heuristics and prior work in the specific domain, and use techniques like learning-rate range tests and small-scale experiments before committing to expensive full-scale training runs.",
    "The interviewer wants to see a practical, iterative process grounded in data size and compute constraints, not a claim of knowing the 'right' architecture in advance.",
    "Emphasize starting from proven pretrained architectures and iterating based on under/overfitting signals.",
  ),
  interview(
    6,
    15,
    "What is batch normalization, and why does it help training?",
    "Batch normalization normalizes the inputs to a layer — subtracting the batch mean and dividing by the batch standard deviation — and then applies a learnable scale and shift so the layer can still represent its optimal distribution if needed. This helps because it reduces internal covariate shift, meaning the distribution of inputs each layer sees stays more stable during training instead of shifting as earlier layers' weights change, which in turn allows higher learning rates, faster convergence, and makes the network less sensitive to initialization. As a side effect, because normalization statistics are computed per mini-batch (adding some noise), it also has a mild regularizing effect similar to dropout.",
    "This checks whether you know both the mechanism (per-batch normalize plus learnable scale/shift) and the practical training benefits, not just that 'it makes training better.'",
    "Describe the normalize-then-scale-and-shift mechanism before listing the training benefits.",
  ),
  interview(
    7,
    15,
    "Explain dropout and why it helps prevent overfitting.",
    "Dropout randomly zeroes out a fraction of neurons' activations (e.g. 50%) on each training forward pass, chosen independently each time, and at inference time uses all neurons but scales activations to account for the ones that were dropped during training. This prevents overfitting because it stops neurons from co-adapting too tightly to specific other neurons' outputs — each neuron has to learn features that are useful in combination with many different random subsets of the rest of the network, which is similar in spirit to training and averaging many different thinned sub-networks. In effect, it acts as a cheap approximation to ensembling many models, which improves generalization to unseen data.",
    "The interviewer is testing whether you understand dropout as preventing co-adaptation/acting like implicit ensembling, not just 'it randomly turns off neurons.'",
    "Explain the training-time random masking, then connect it to preventing co-adaptation and implicit ensembling.",
  ),
  interview(
    8,
    15,
    "When would you choose a CNN versus an RNN versus a transformer for a given task?",
    "CNNs are the natural choice when the data has strong local, spatially-structured patterns and translation invariance matters, like images or, sometimes, short local patterns in 1D signals — they're efficient and fast to train because of weight sharing. RNNs/LSTMs make sense for sequential data with a genuinely sequential, often streaming or causal, processing need, especially when sequences are short-to-moderate and there's a hard constraint favoring low memory or strictly online/incremental processing. Transformers are generally preferred today for text, and increasingly for many other sequence and even image tasks (via vision transformers), when you need to model long-range dependencies, can afford the quadratic-in-sequence-length attention cost, and want to leverage massive pretrained models and parallel training — they've largely displaced RNNs for most NLP tasks because they train faster (parallelizable) and capture long-range context better.",
    "This checks that you can reason about the tradeoffs (locality vs. sequential memory vs. long-range parallel attention) rather than just naming architectures.",
    "Anchor each choice to a structural property of the data: locality, strict sequential order, or long-range dependencies.",
  ),
  interview(
    9,
    15,
    "How do you debug a neural network whose training loss isn't decreasing at all?",
    "First I'd rule out simple bugs: check the loss function matches the task and labels are correctly formatted (e.g. off-by-one label indices, wrong loss for the output activation), verify data is actually being loaded and shuffled correctly and isn't all zeros or a constant, and confirm gradients are actually flowing (not all zero — check for accidentally frozen layers or a detached computation graph). Next I'd sanity check the setup at a tiny scale: try to overfit a very small subset (like 10 examples) — if the model can't drive loss to near zero on a handful of examples, there's a bug in the model or training loop, not a capacity or hyperparameter issue. If that works, I'd suspect the learning rate (too high causes instability/NaNs, too low means invisible progress), check for exploding or vanishing gradients via gradient norms, and verify inputs are normalized appropriately. Only after ruling all that out would I look at architecture capacity or feature quality.",
    "The interviewer wants a systematic debugging process (overfit-a-tiny-batch sanity check, gradient checks, learning rate) rather than random hyperparameter guessing.",
    "Lead with the 'overfit a tiny batch' sanity check — it's the single most diagnostic step.",
  ),
  interview(
    10,
    15,
    "Explain transfer learning and describe a scenario where it's clearly useful.",
    "Transfer learning takes a model pretrained on a large, related dataset (e.g. ImageNet for vision, or a large text corpus for language models) and reuses its learned representations for a new, often smaller, target task — either by fine-tuning all the weights on the new data, or freezing most of the network and only training a new head on top. It's useful because the earlier layers of a pretrained model have already learned general-purpose features (edges/textures in vision, syntax/semantics in language) that transfer well, so you need far less labeled data and compute to reach good performance than training from scratch. A clear example: building a medical image classifier with only a few thousand labeled X-rays — starting from an ImageNet-pretrained CNN and fine-tuning it typically massively outperforms training the same architecture from random initialization on that small dataset.",
    "This tests whether you understand why transfer learning works (reusable general features) and can give a concrete, realistic scenario, not just the definition.",
    "Give the mechanism (reused general features) plus a concrete small-data scenario like medical imaging.",
  ),
  interview(
    11,
    15,
    "What's the difference between an epoch, a batch, and an iteration?",
    "An epoch is one complete pass through the entire training dataset. Because the full dataset usually doesn't fit in memory or would make each weight update too slow, it's split into batches — a batch (or mini-batch) is a subset of the training data processed together in one forward/backward pass. An iteration is a single weight update, which corresponds to processing exactly one batch; so if a dataset has 10,000 examples and the batch size is 100, one epoch consists of 100 iterations. Understanding this distinction matters practically because hyperparameters like learning rate schedules are often defined in terms of iterations or epochs, and getting the two confused leads to misconfigured training runs.",
    "This is a basic-but-common question checking precise, unambiguous vocabulary since these terms get sloppily used interchangeably.",
    "Use a concrete example with numbers (dataset size, batch size) to show the relationship clearly.",
  ),
  interview(
    12,
    15,
    "How do you choose a learning rate, and what happens if it's set too high or too low?",
    "I'd typically start with a value known to work well for the optimizer and architecture (e.g. 1e-3 for Adam as a common default) and then use a learning rate range test — ramping the learning rate up over a few hundred iterations and plotting loss to see where it starts diverging — to pick a good order of magnitude, often combined with a learning rate scheduler (warmup then decay, or cosine annealing) rather than one fixed value for all of training. If the learning rate is too high, updates overshoot the minimum, causing the loss to oscillate, plateau at a high value, or even diverge to NaN. If it's too low, training will make very slow, barely-visible progress, and can get stuck in poor local regions or simply not converge within a practical training budget, wasting compute. Monitoring the loss curve shape (oscillating vs. flat vs. smoothly decreasing) is usually the fastest diagnostic for which regime you're in.",
    "The interviewer wants practical knowledge of learning-rate-finding techniques and the ability to diagnose from loss-curve behavior, not just 'try a few values.'",
    "Mention the learning-rate range test and describe the loss-curve symptoms of too-high vs. too-low.",
  ),
  interview(
    13,
    15,
    "Explain the exploding gradient problem — what causes it and how is it typically mitigated?",
    "Exploding gradients occur when gradients grow multiplicatively larger as they're backpropagated through many layers or time steps, particularly common in deep networks and RNNs, often because weight matrices have eigenvalues/singular values greater than 1, causing repeated multiplication to blow up the gradient magnitude. This shows up as loss suddenly spiking to very large values or NaN, and unstable, erratic training. The standard mitigation is gradient clipping — rescaling the gradient vector if its norm exceeds a threshold, which caps the size of any single update without changing its direction. Other mitigations include careful weight initialization (e.g. Xavier/He initialization), using architectures less prone to it (like LSTMs' gating, or residual connections that provide more well-behaved gradient paths), and using batch/layer normalization to keep activations and gradients in a reasonable range.",
    "This checks that you know the mechanism mirrors vanishing gradients (repeated multiplication, just >1 instead of <1) and can name gradient clipping as the standard concrete fix.",
    "Contrast it directly with vanishing gradients: same mechanism, opposite direction, and name gradient clipping as the fix.",
  ),
  interview(
    14,
    15,
    "How would you deploy a deep learning model under tight latency constraints, and what techniques would you consider?",
    "I'd first profile where time is actually spent (model forward pass vs. preprocessing vs. I/O) since sometimes the bottleneck isn't the model itself. For the model, common techniques are quantization (converting weights/activations from float32 to int8 or float16, which shrinks memory and speeds up inference on hardware with optimized low-precision kernels, usually with a small accuracy tradeoff), knowledge distillation (training a smaller 'student' model to mimic a larger 'teacher' model's outputs, retaining much of its accuracy at a fraction of the compute), and pruning (removing redundant weights or whole channels/heads that contribute little). I'd also consider architecture-level choices like using a smaller/faster backbone designed for edge deployment (e.g. MobileNet-style models), batching requests where possible, using an inference-optimized runtime (ONNX Runtime, TensorRT), and caching or precomputing where the workload allows it — and I'd always validate that the optimized model still meets accuracy requirements on a held-out set before shipping it.",
    "The interviewer wants to see practical, production-oriented knowledge (quantization, distillation, pruning, optimized runtimes) beyond just training a model.",
    "Name quantization and distillation explicitly, and mention validating accuracy after optimization.",
  ),
  interview(
    15,
    15,
    "What are the signs of overfitting specific to deep neural nets, and how would you address it?",
    "The clearest sign is a growing gap between training and validation loss/accuracy — training loss keeps dropping while validation loss flattens out or starts rising, meaning the model is memorizing training-specific noise rather than learning generalizable patterns. Deep nets are especially prone to this because of their huge parameter counts relative to typical dataset sizes. To address it, I'd add or increase regularization: dropout, weight decay (L2 regularization), data augmentation (especially effective for images — random crops, flips, color jitter) to effectively enlarge the training distribution, and early stopping based on validation performance. I'd also consider whether the model is simply too large for the amount of data available and whether transfer learning from a pretrained model, or collecting/labeling more data, would help more than further regularizing an oversized model trained from scratch.",
    "This tests whether you can diagnose overfitting from the train/validation gap and name the standard deep-learning-specific regularization toolbox, not just 'get more data.'",
    "Lead with the train/validation loss gap as the diagnostic signal, then list the regularization toolbox.",
  ),
];

export const DEEP_LEARNING_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1: Foundations",
      summary:
        "Core deep learning concepts: neurons, activations, forward/backward propagation, loss functions, optimizers, regularization, and the major architecture families (CNNs, RNNs/LSTMs, transformers).",
      topics: ["Fundamentals"],
      steps: round1Steps,
    },
    {
      number: 2,
      title: "Round 2: Interview Prep",
      summary:
        "Open-ended, real interview-style questions about backpropagation, gradient issues, architecture choice, regularization, and deploying models under real-world constraints.",
      topics: ["Deep Learning Interview Prep"],
      steps: round2Steps,
    },
  ],
};
