import {type Course, makeInterviewBuilder, makeMcqBuilder} from "./course-types";

// Round 1: Excel fundamentals every data analyst is expected to know cold —
// lookup functions, references, PivotTables, conditional aggregation,
// data cleaning, Power Query basics, charts, and common error values.
const mcq = makeMcqBuilder("Excel Fundamentals");

const round1Steps = [
  mcq(
    1,
    20,
    "What is the main advantage of XLOOKUP over VLOOKUP?",
    [
      "XLOOKUP can only search vertically, just like VLOOKUP",
      "XLOOKUP can search left or right of the lookup column and defaults to exact match",
      "XLOOKUP is only available in Excel for Mac",
      "XLOOKUP cannot return an array of values",
    ],
    1,
    "XLOOKUP isn't restricted to searching to the right of the lookup column like VLOOKUP, defaults to an exact match instead of approximate, and can return arrays, making it more flexible and less error-prone.",
    "Think about VLOOKUP's biggest structural limitation: it can only look to one side.",
  ),
  mcq(
    2,
    20,
    "Why would you use INDEX/MATCH instead of VLOOKUP in a large workbook?",
    [
      "INDEX/MATCH is always faster and doesn't break when columns are inserted or deleted between the lookup and return columns",
      "INDEX/MATCH can only return text values, never numbers",
      "VLOOKUP automatically updates when columns are inserted, so INDEX/MATCH is unnecessary",
      "INDEX/MATCH requires the lookup column to be sorted",
    ],
    0,
    "VLOOKUP relies on a hard-coded column index number, which shifts (and silently returns wrong data) if columns are inserted or deleted; INDEX/MATCH references the return column directly, so it's unaffected by such structural changes.",
    "Consider what happens to VLOOKUP's third argument when someone inserts a new column in the middle of the table.",
  ),
  mcq(
    3,
    20,
    "In the formula =A1*$B$1, what happens to the reference $B$1 when it is copied down to row 10?",
    [
      "It changes to $B$10",
      "It stays exactly $B$1 in every copied row",
      "It becomes B$1",
      "It causes a #REF! error",
    ],
    1,
    "Dollar signs before both the column letter and row number lock the reference completely, so $B$1 remains $B$1 no matter where the formula is copied.",
    "Both parts of the reference are anchored with dollar signs — nothing about it can shift.",
  ),
  mcq(
    4,
    20,
    "You have a raw sales table and want to quickly summarize total sales by region and month, with the ability to drag fields around interactively. What's the best tool?",
    ["Conditional formatting", "A PivotTable", "Data validation", "Freeze panes"],
    1,
    "PivotTables are purpose-built for interactively summarizing and reshaping large datasets by dragging fields into rows, columns, values, and filters without writing formulas.",
    "You want something you can drag-and-drop fields into, not a static formula.",
  ),
  mcq(
    5,
    20,
    "Which conditional formatting rule type would you use to highlight cells whose value is above the column's average?",
    [
      "A fixed 'Cell Value greater than' rule with a manually typed number",
      "'Top/Bottom Rules' → 'Above Average'",
      "Data validation with a custom formula",
      "Text that Contains rule",
    ],
    1,
    "Excel's built-in 'Above Average' rule under Top/Bottom Rules automatically computes the column's average and highlights cells exceeding it, without you having to calculate or hard-code the threshold.",
    "There's a built-in preset specifically for average-relative highlighting — you don't need to calculate AVERAGE() yourself.",
  ),
  mcq(
    6,
    20,
    "What is the key difference between SUMIF and SUMIFS?",
    [
      "SUMIF sums based on multiple criteria across multiple ranges, SUMIFS only supports one",
      "SUMIFS supports multiple criteria/ranges (AND logic), SUMIF only supports a single criterion",
      "They are functionally identical, SUMIFS is just newer syntax",
      "SUMIF works on text only, SUMIFS works on numbers only",
    ],
    1,
    "SUMIF takes exactly one range/criteria pair, while SUMIFS accepts multiple range/criteria pairs that are combined with AND logic, letting you filter on several conditions at once.",
    "The 'S' at the end hints at plural conditions.",
  ),
  mcq(
    7,
    20,
    "Which formula correctly counts orders where Region = \"West\" AND Status = \"Shipped\"?",
    [
      "=COUNTIF(Region,\"West\",Status,\"Shipped\")",
      "=COUNTIFS(Region,\"West\",Status,\"Shipped\")",
      "=SUMIF(Region,\"West\")+SUMIF(Status,\"Shipped\")",
      "=COUNT(Region,\"West\",Status,\"Shipped\")",
    ],
    1,
    "COUNTIFS accepts pairs of range and criteria and requires ALL of them to be true (AND logic), which is exactly what's needed to combine the Region and Status conditions.",
    "COUNTIF only takes one condition; you need the version built for multiple conditions.",
  ),
  mcq(
    8,
    20,
    "A cell should only accept whole numbers between 1 and 100. Which Excel feature enforces this as someone types?",
    ["Conditional formatting", "Data validation with a whole number rule", "Freeze panes", "AutoFilter"],
    1,
    "Data validation lets you restrict input to a whole number within a specified range, showing an error message if someone tries to enter something outside it, right at data-entry time.",
    "You need something that blocks bad input at entry, not something that just colors it after the fact.",
  ),
  mcq(
    9,
    20,
    "Which function combines text from multiple cells with a specified delimiter between each value, and can also ignore empty cells?",
    ["CONCATENATE", "TEXTJOIN", "LEFT", "TRIM"],
    1,
    "TEXTJOIN takes a delimiter, an ignore-empty flag, and a range/list of values, joining them all in one call — CONCATENATE has no delimiter or empty-cell handling and requires listing each cell.",
    "Think of the newer function designed specifically to add a separator and skip blanks.",
  ),
  mcq(
    10,
    20,
    "You need to extract the first 3 characters from a product code in A2. Which formula does this?",
    ["=MID(A2,1,3)", "=LEFT(A2,3)", "=RIGHT(A2,3)", "=TRIM(A2,3)"],
    1,
    "LEFT(text, num_chars) returns the specified number of characters starting from the left side of the string, which is exactly the first 3 characters.",
    "You want the function named for the side of the string you're extracting from.",
  ),
  mcq(
    11,
    20,
    "A column of names imported from another system has extra leading, trailing, and repeated internal spaces. Which function cleans this up?",
    ["TRIM", "CLEAN", "PROPER", "EXACT"],
    0,
    "TRIM removes leading and trailing spaces and collapses multiple internal spaces down to a single space between words.",
    "The function name directly describes 'trimming' whitespace.",
  ),
  mcq(
    12,
    20,
    "Which function returns the current date and automatically updates every time the workbook recalculates?",
    ["=DATE()", "=TODAY()", "=NOW()", "=DATEVALUE()"],
    1,
    "TODAY() returns the current date and recalculates automatically whenever the workbook opens or recalculates, whereas DATE() requires you to supply year/month/day values.",
    "You want the volatile function that needs no arguments and returns just the date, not the date and time.",
  ),
  mcq(
    13,
    20,
    "What is a dynamic array / spill formula in modern Excel (e.g. using UNIQUE or FILTER)?",
    [
      "A formula that must be entered with Ctrl+Shift+Enter to work at all",
      "A single formula in one cell that automatically 'spills' results into neighboring cells as needed",
      "A formula that only works inside PivotTables",
      "A macro-only feature not available as a worksheet function",
    ],
    1,
    "Dynamic array functions like UNIQUE, FILTER, and SORT return multiple results from a single formula entered in one cell, and Excel automatically spills the extra values into the adjacent empty cells.",
    "Think about what happens visually when a single-cell formula like UNIQUE() produces more than one result.",
  ),
  mcq(
    14,
    20,
    "In Power Query, what are the three broad stages of working with data?",
    [
      "Sort, Filter, Format",
      "Connect/Import, Transform (clean/shape), Load",
      "Encrypt, Compress, Export",
      "Record, Playback, Debug",
    ],
    1,
    "Power Query's workflow is to connect to and import a data source, transform it through a recorded series of shaping/cleaning steps in the Query Editor, and then load the result into the worksheet or data model.",
    "Think of it as get the data in, clean it up, then put it somewhere useful.",
  ),
  mcq(
    15,
    20,
    "You want a chart to show how a total is broken into parts over several time periods (e.g. revenue by product line across 12 months). Which chart type is generally the best fit?",
    ["Pie chart", "Stacked bar/column chart", "Scatter plot", "Radar chart"],
    1,
    "A stacked column chart shows both the total for each period and how that total is divided among categories, which is exactly what's needed to compare part-to-whole composition across multiple time periods; a pie chart can only show one period's composition at a time.",
    "You need to compare composition across many periods at once — a pie chart only handles a single snapshot.",
  ),
  mcq(
    16,
    20,
    "Which built-in feature removes duplicate rows from a dataset based on selected columns?",
    ["Data → Remove Duplicates", "Home → Conditional Formatting", "Data → Data Validation", "Formulas → Trace Precedents"],
    0,
    "The Data tab's 'Remove Duplicates' tool lets you choose which columns to check and deletes rows that are duplicates across those columns, keeping the first occurrence.",
    "Look on the Data ribbon tab for a tool with a very literal name.",
  ),
  mcq(
    17,
    20,
    "What is the purpose of a Named Range in Excel?",
    [
      "It permanently locks a cell so it cannot be edited",
      "It gives a cell or range a memorable name that can be used in formulas instead of a cell reference",
      "It automatically sorts the range alphabetically",
      "It converts the range into a PivotTable",
    ],
    1,
    "A named range lets you reference cells by a descriptive name (e.g. TaxRate instead of $B$2), which makes formulas more readable and keeps references stable when used consistently across a workbook.",
    "Think about readability: `=Revenue*TaxRate` versus `=B2*$C$2`.",
  ),
  mcq(
    18,
    20,
    "A formula returns #N/A. What does this error most commonly indicate?",
    [
      "A value referenced in a formula is of the wrong data type",
      "A lookup function could not find a matching value",
      "A formula refers to a cell that has been deleted",
      "A number was divided by zero",
    ],
    1,
    "#N/A most commonly appears from VLOOKUP/XLOOKUP/MATCH when the lookup value isn't found in the search range, signaling 'not available' rather than a broken reference or type mismatch.",
    "The 'N/A' literally stands for 'not available' — think about which functions search for something that might not exist.",
  ),
  mcq(
    19,
    20,
    "What typically causes a #REF! error?",
    [
      "Text was used where a number was expected",
      "A formula references a cell, row, or column that has been deleted",
      "A named range was misspelled",
      "A cell is formatted as text instead of a number",
    ],
    1,
    "#REF! appears when a formula's reference becomes invalid because the referenced cell, row, or column was deleted, so Excel has nothing left to point to.",
    "REF stands for reference — think about what happens when the thing being referenced disappears.",
  ),
  mcq(
    20,
    20,
    "Which keyboard shortcut freezes the panes above and to the left of the currently selected cell, keeping headers visible while scrolling?",
    [
      "Ctrl+Shift+F",
      "There is no shortcut; it must be done via View → Freeze Panes menu only",
      "Alt, W, F, F",
      "Ctrl+F",
    ],
    2,
    "Alt, W, F, F is the classic key-tip sequence (View tab, Freeze Panes, Freeze Panes) power users rely on to freeze panes without touching the mouse; Ctrl+F opens Find, not Freeze Panes.",
    "Ctrl+F is already taken by Find — this one is a sequence of ribbon key-tips instead.",
  ),
];

// Round 2: open-ended interview questions a Data Analyst candidate should be
// ready to answer about real-world Excel workflows — PivotTables, lookups,
// data cleaning, dashboards, auditing, and knowing when to graduate to SQL/Python.
const interview = makeInterviewBuilder("excel-interview", "Excel Interview Prep");

const round2Steps = [
  interview(
    1,
    15,
    "Walk through how you'd build a PivotTable to summarize monthly sales by region.",
    "I'd start with a clean, tabular source range (one row per transaction, with columns for date, region, and sales amount, no merged cells or blank rows), then insert a PivotTable from that range. I'd drag Region into Rows, group the Date field into Months (or add a helper column) and drag it into Columns, and drag Sales Amount into Values, setting it to Sum. From there I'd format the values as currency, sort regions by total descending, and optionally add a slicer or filter for year if there's multiple years of data. Finally I'd sanity-check the grand total against a SUM formula on the raw data to make sure nothing got excluded.",
    "The interviewer is checking that you understand PivotTable field zones (Rows/Columns/Values/Filters) and that you build on clean source data rather than treating the pivot as magic.",
    "Mention the four field zones by name and how you'd group dates into months.",
  ),
  interview(
    2,
    15,
    "When would you use INDEX/MATCH over VLOOKUP?",
    "I'd reach for INDEX/MATCH whenever I need to look up a value to the left of the lookup column, since VLOOKUP can only search to the right. It's also more robust in large, evolving workbooks because it references the return column directly rather than a hard-coded column index number, so inserting or deleting columns between the lookup and return columns won't silently break it or return the wrong value. In practice I use XLOOKUP now when it's available since it solves both problems with cleaner syntax, but INDEX/MATCH is still important to know for older files or shared workbooks that need to stay compatible.",
    "This tests whether you understand VLOOKUP's structural weaknesses rather than just knowing the syntax of both functions.",
    "Lead with the leftward-lookup limitation, then the column-index fragility.",
  ),
  interview(
    3,
    15,
    "How would you clean a messy dataset with duplicate rows and inconsistent text casing before analysis?",
    "First I'd standardize text casing using PROPER, UPPER, or LOWER (often in a helper column) so that 'new york', 'New York', and 'NEW YORK' are treated as the same value, and I'd also TRIM whitespace since invisible extra spaces cause false mismatches. Once the text is normalized, I'd use Data → Remove Duplicates on the key columns, but only after confirming with a COUNTIFS or a PivotTable count which rows are true duplicates versus legitimately similar records. For anything more complex or repeatable, I'd do this cleanup in Power Query instead of manual formulas, since it records the steps and reapplies them automatically the next time the data refreshes.",
    "The interviewer wants to see a deliberate cleaning sequence (normalize before dedupe) and awareness that Power Query scales better than one-off formulas.",
    "Sequence matters: normalize text before you deduplicate, otherwise near-duplicates slip through.",
  ),
  interview(
    4,
    15,
    "Explain how you'd use SUMIFS to calculate revenue for a specific product and date range.",
    "I'd write something like =SUMIFS(Revenue, Product, \"Widget A\", Date, \">=\"&StartDate, Date, \"<=\"&EndDate), where Revenue is the sum range and each subsequent pair is a criteria range and its condition. The two Date criteria act together as a lower and upper bound, effectively filtering to a date window, while the Product criterion narrows it to the specific item. I'd typically put StartDate and EndDate in their own cells rather than hard-coding them in the formula, so the range can be adjusted without editing the formula itself.",
    "This checks that you know SUMIFS syntax precisely, including how to express a date range using two criteria on the same field.",
    "Remember you need the same date column referenced twice, once with >= and once with <=.",
  ),
  interview(
    5,
    15,
    "How do you audit a spreadsheet you inherited for formula errors?",
    "I'd start with Formulas → Error Checking and Trace Precedents/Dependents to visually map how cells feed into each other, and use Ctrl+` (show formulas) to scan for inconsistent formulas across a column that should otherwise be uniform. I'd specifically look for hard-coded numbers mixed into formula cells, #REF!/#N/A/#VALUE! errors, and ranges that don't extend to cover new rows. For anything suspicious, I'd isolate it into a blank area and rebuild the calculation from scratch to confirm it matches, and I'd check named ranges and data validation rules for stale references pointing at deleted sheets or ranges.",
    "This tests systematic debugging habits rather than just knowing that an 'error checking' button exists.",
    "Mention both automated tools (Trace Precedents, error checking) and a manual sanity-rebuild step.",
  ),
  interview(
    6,
    15,
    "Explain the difference between Power Query and a regular formula-driven workbook, and when you'd reach for Power Query.",
    "A formula-driven workbook recalculates live cell-by-cell every time you open it or change an input, which is great for small, interactive 'what-if' analysis but gets fragile and slow as data volume and transformation complexity grow. Power Query instead records a repeatable sequence of transformation steps (filter, merge, pivot, split columns, etc.) against a data source, and you refresh it to reapply that whole pipeline whenever the source changes, without touching formulas at all. I'd reach for Power Query whenever I'm combining data from multiple files or sources, need the same cleanup applied every time new data arrives, or I'm working with volumes large enough that formula-heavy sheets become slow and hard to audit.",
    "The interviewer wants to see you understand Power Query as a repeatable ETL layer, distinct from ad-hoc formula calculation.",
    "Frame it as repeatable pipeline versus live recalculation, and mention refresh.",
  ),
  interview(
    7,
    15,
    "How would you build a dynamic dashboard that updates automatically when new data is pasted in?",
    "I'd convert the source range into an Excel Table (Ctrl+T) so it automatically expands as new rows are added, and build all PivotTables, charts, and summary formulas to reference that table rather than a fixed range, so they pick up new rows without manual range edits. I'd use dynamic array functions or structured table references so summary formulas grow automatically, and add slicers connected to the PivotTables for interactive filtering. Finally I'd set PivotTables to refresh on file open (or add a simple 'Refresh All' button/macro) so the dashboard always reflects the latest pasted data without the user having to know to click Refresh manually.",
    "This tests whether you know Excel Tables are the mechanism that makes ranges auto-expand, which is the real foundation of a self-updating dashboard.",
    "The key trick is Ctrl+T (Excel Tables) so ranges grow automatically — mention that specifically.",
  ),
  interview(
    8,
    15,
    "What's your approach to handling a #REF! error appearing after someone deletes a column?",
    "First I'd use Ctrl+Z immediately if the deletion just happened, since undo is the cleanest fix before anything else recalculates over the broken state. If that's not possible, I'd trace which formulas show #REF! using Find (Ctrl+F, searching for '#REF!') or the Error Checking tool, then manually rebuild each broken reference by re-pointing it at the correct current cell or range. Going forward, I'd suggest using named ranges, Excel Tables, or INDEX/MATCH-style formulas that reference column headers instead of raw column letters, since those are more resilient to structural changes like inserted or deleted columns.",
    "The interviewer wants immediate triage (undo) plus a longer-term fix that prevents recurrence, not just a one-time patch.",
    "Undo first if possible, then talk about making formulas structurally resilient going forward.",
  ),
  interview(
    9,
    15,
    "How would you flag outliers in a dataset using conditional formatting?",
    "A simple approach is a 'Top/Bottom Rules' → 'Above/Below Average' rule, or a custom formula rule based on standard deviations, e.g. highlighting cells where ABS(value - AVERAGE(range)) > 2*STDEV(range), which flags anything more than two standard deviations from the mean. For something more visual and quick to scan, I'd add a color scale or data bars across the column so extreme values are immediately obvious even without a hard cutoff. I'd also cross-check flagged outliers against context (e.g. are they a data entry typo or a genuinely unusual but valid transaction) before treating them as errors to remove.",
    "This checks whether you can translate a statistical concept (standard deviations from the mean) into an actual conditional formatting formula, not just apply a color.",
    "A custom formula rule using AVERAGE and STDEV is the more rigorous answer than just 'Above Average'.",
  ),
  interview(
    10,
    15,
    "Explain how you'd reconcile two large datasets (e.g. system export vs. finance report) to find mismatches.",
    "I'd bring both datasets into the same workbook (or Power Query) and create a common key (like transaction ID or a concatenation of date+account+amount) in each, then use XLOOKUP or a full outer merge in Power Query to line up matching keys side by side. Anything that returns #N/A in one direction is unmatched in one system but not the other, and I'd add a comparison column that flags rows where the amounts match, don't match, or are missing entirely. For truly large volumes I'd prefer doing this reconciliation in Power Query or even SQL rather than nested formulas, since it's easier to make repeatable and less error-prone than manual VLOOKUPs across huge ranges.",
    "The interviewer wants to see a structured key-based matching approach and awareness of tool limits at scale, not ad-hoc eyeballing.",
    "Build a matching key first, then use lookups (or a Power Query merge) to surface exceptions rather than matches.",
  ),
  interview(
    11,
    15,
    "What's the difference between a PivotTable and a PivotChart?",
    "A PivotTable summarizes and aggregates raw data into a grid you can rearrange by dragging fields into rows, columns, values, and filters. A PivotChart is a visual representation built directly on top of a PivotTable's data, so it shares the same underlying field structure and stays linked to it — filtering or slicing the chart updates the table and vice versa. In practice you almost always need the PivotTable (or at least a PivotCache) underneath before you can create a PivotChart, since the chart is just a visual layer on the same aggregated data.",
    "This tests whether you understand that a PivotChart is dependent on, not a replacement for, a PivotTable's data structure.",
    "Emphasize that they share the same underlying data and stay linked/synchronized.",
  ),
  interview(
    12,
    15,
    "How do you decide when a task has outgrown Excel and needs SQL/Python instead?",
    "I look at a few signals: data volume approaching or exceeding what Excel can comfortably handle (millions of rows, or noticeably slow recalculation), the need for repeatable, version-controlled, auditable transformations rather than manual point-and-click steps, and requirements like joining many large tables, complex statistical modeling, or automation that needs to run on a schedule without a human opening a workbook. If I find myself fighting workbook size limits, writing extremely nested formulas just to approximate a database JOIN, or manually repeating the same cleanup every week, that's usually the sign to move the heavy lifting to SQL for the data prep and Python for anything requiring more advanced analysis or automation, while still using Excel for the final presentation layer if stakeholders expect it.",
    "The interviewer wants to see practical judgment about tool limits, not a blanket 'Excel is always fine' or 'always use Python' answer.",
    "Name concrete signals — volume, repeatability, complexity of joins/modeling — rather than a vague 'when it gets too big'.",
  ),
  interview(
    13,
    15,
    "Explain array formulas / dynamic arrays (SPILL) and a case where they're useful.",
    "A dynamic array formula is a single formula that can return multiple results at once, which modern Excel automatically 'spills' into the neighboring empty cells rather than requiring the older Ctrl+Shift+Enter array-entry method. A practical example is using =UNIQUE(FILTER(Products, Region=\"West\")) in one cell to instantly list every distinct product sold in the West region, updating automatically as the source data changes, without needing a helper column or a PivotTable. This is especially useful for building lightweight, formula-driven summaries or dropdown source lists that need to stay live without manual refreshing.",
    "This checks whether you know dynamic arrays are a specific modern Excel feature (SPILL) and can name a concrete function combination that uses them.",
    "Mention UNIQUE/FILTER/SORT specifically and describe what 'spilling' looks like on the sheet.",
  ),
  interview(
    14,
    15,
    "How would you protect a shared workbook from accidental edits while still letting people filter/view data?",
    "I'd use Format Cells to unlock only the specific input cells that people should be able to edit (unlocking is per-cell, off by default once protection is applied), then turn on Protect Sheet so all other cells remain locked and formulas can't be accidentally overwritten. Within Protect Sheet's options I'd explicitly allow 'Use AutoFilter' and 'Use PivotTable' (and sorting, if needed) so viewers can still filter and interact with the data without being able to type over formulas or headers. For an extra layer on a widely shared file, I'd also consider distributing it as a PivotTable-only view or a linked read-only copy so the source data itself stays untouched.",
    "The interviewer wants to see that you know protection is granular (locked cells plus specific allowed actions), not an all-or-nothing lock.",
    "Remember: unlock the input cells first, then protect the sheet, then explicitly enable filter/sort permissions.",
  ),
  interview(
    15,
    15,
    "Walk through building a data validation dropdown list tied to another sheet.",
    "First I'd put the list of valid options on a separate reference sheet (or as an Excel Table/named range), which keeps the dropdown source easy to maintain without cluttering the main sheet. I'd select the target cell(s), go to Data → Data Validation → List, and in the Source box reference that range, e.g. =Lists!$A$2:$A$10 or a named range like ProductList, rather than typing the values directly so it stays maintainable. I'd typically define it as a named range or a Table column so that if someone adds a new valid option to the list later, the dropdown automatically includes it without editing the validation rule itself.",
    "This tests that you know the source should point to a maintainable range (ideally a named range or Table), not a hard-coded, static list typed directly into the Source box.",
    "The best answers use a named range or Table column as the source so the list can grow without editing the validation rule.",
  ),
];

export const EXCEL_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1: Foundations",
      summary:
        "Core Excel skills for data analytics: lookups, references, PivotTables, conditional aggregation, data cleaning, Power Query, charts, and common errors.",
      topics: ["Fundamentals"],
      steps: round1Steps,
    },
    {
      number: 2,
      title: "Round 2: Interview Prep",
      summary:
        "Open-ended, real interview-style questions about PivotTables, lookups, dashboards, data cleaning, and knowing when Excel isn't the right tool.",
      topics: ["Excel Interview Prep"],
      steps: round2Steps,
    },
  ],
};
