import {type Course, makeInterviewBuilder, makeMcqBuilder} from "./course-types";

// Round 1: Machine Learning fundamentals every ML/Data Science candidate is
// expected to know cold — the learning paradigms, core algorithms, model
// evaluation concepts, and the everyday techniques used to build and
// validate models.
const mcq = makeMcqBuilder("Machine Learning Fundamentals");

const round1Steps = [
  mcq(
    1,
    20,
    "A model is trained on labeled examples (input paired with the correct output) to predict labels on new data. What type of learning is this?",
    ["Unsupervised learning", "Supervised learning", "Reinforcement learning", "Semi-supervised clustering"],
    1,
    "Supervised learning uses labeled data (known inputs paired with known correct outputs) so the model can learn a mapping from input to output and be evaluated against ground truth.",
    "Think about whether the training data comes with the 'answer key' attached.",
  ),
  mcq(
    2,
    20,
    "Which type of learning involves an agent taking actions in an environment and receiving rewards or penalties over time?",
    ["Supervised learning", "Unsupervised learning", "Reinforcement learning", "Transfer learning"],
    2,
    "Reinforcement learning trains an agent to choose actions that maximize cumulative reward through trial-and-error interaction with an environment, rather than from a fixed labeled dataset.",
    "It's the paradigm most associated with game-playing agents and robots learning by trial and error.",
  ),
  mcq(
    3,
    20,
    "Why do we split data into training, validation, and test sets instead of just training and testing?",
    [
      "To make the dataset larger",
      "The validation set is used to tune hyperparameters/select models, keeping the test set as an unbiased final check",
      "The test set is only needed if the dataset is small",
      "Validation and test sets must always be the same size",
    ],
    1,
    "The validation set lets you compare models and tune hyperparameters without touching the test set, so the test set remains an unbiased estimate of real-world performance on truly unseen data.",
    "Think about which set you're allowed to 'peek at' repeatedly versus the one you touch only once at the end.",
  ),
  mcq(
    4,
    20,
    "A model achieves 99% accuracy on the training set but only 60% on the test set. What is this called?",
    ["Underfitting", "Overfitting", "Regularization", "Bias"],
    1,
    "A large gap between training and test performance, with very high training performance, is the signature of overfitting: the model memorized noise/specifics of the training data rather than learning generalizable patterns.",
    "The model is doing great on data it has seen but poorly on data it hasn't — that mismatch has a specific name.",
  ),
  mcq(
    5,
    20,
    "A linear model performs poorly on both the training set and the test set. This is most likely an example of:",
    ["Overfitting", "Underfitting", "Data leakage", "High variance"],
    1,
    "Poor performance on both training and test data indicates the model is too simple to capture the underlying pattern — it has high bias and is underfitting.",
    "If it's bad even on data it trained on, the problem isn't memorization — it's that the model is too simple.",
  ),
  mcq(
    6,
    20,
    "In the bias-variance tradeoff, what does 'high variance' typically indicate about a model?",
    [
      "The model is too simple and misses real patterns",
      "The model is very sensitive to the specific training data and doesn't generalize well",
      "The model always predicts the same value",
      "The model has no hyperparameters",
    ],
    1,
    "High variance means the model's predictions change a lot if trained on a different sample of data, indicating it has fit noise specific to the training set rather than the underlying signal — a hallmark of overfitting.",
    "Variance is about sensitivity to which particular training data you happened to get.",
  ),
  mcq(
    7,
    20,
    "In simple linear regression, what does the model assume about the relationship between the input feature and the target?",
    [
      "It is a step function",
      "It is approximately linear (a straight-line relationship plus noise)",
      "It must be exponential",
      "There is no assumed relationship",
    ],
    1,
    "Linear regression models the target as a weighted linear combination of the input features plus an error term, so it assumes an approximately straight-line relationship.",
    "The word 'linear' is the giveaway — picture fitting a straight line through a scatter plot.",
  ),
  mcq(
    8,
    20,
    "Why is logistic regression used for binary classification instead of linear regression?",
    [
      "It has more parameters than linear regression",
      "The sigmoid function squashes outputs into a (0,1) range that can be interpreted as a probability",
      "It only works with categorical inputs",
      "Logistic regression cannot overfit",
    ],
    1,
    "Logistic regression applies the sigmoid function to a linear combination of inputs, mapping any real-valued output into the (0,1) range so it can be interpreted as the probability of the positive class.",
    "Think about what function keeps predictions bounded between 0 and 1 so they can act like probabilities.",
  ),
  mcq(
    9,
    20,
    "How does a decision tree decide which feature to split on at each node (e.g. using Gini impurity or information gain)?",
    [
      "It picks features alphabetically",
      "It chooses the split that produces the greatest increase in purity/homogeneity of the resulting child nodes",
      "It always splits on the feature with the largest raw values",
      "It picks a random feature every time regardless of quality",
    ],
    1,
    "Decision trees greedily choose the split (feature and threshold) that most reduces impurity (e.g. Gini impurity or entropy) in the resulting child nodes, making them as pure/homogeneous as possible.",
    "The tree is greedy: at each step it looks for the split that best separates the classes.",
  ),
  mcq(
    10,
    20,
    "How does a random forest generally achieve better generalization than a single decision tree?",
    [
      "It uses a single very deep tree instead of many shallow ones",
      "It averages/votes across many trees trained on bootstrapped samples with random feature subsets, reducing variance",
      "It removes the need for a test set",
      "It only works on regression problems",
    ],
    1,
    "Random forests train many decision trees on bootstrapped samples of the data and random subsets of features, then average (regression) or vote (classification) their predictions, which reduces the high variance of any single tree.",
    "It's an ensemble idea: many imperfect, decorrelated trees combined can outperform one tree.",
  ),
  mcq(
    11,
    20,
    "In k-nearest neighbors (KNN) classification, how is a new point's class typically predicted?",
    [
      "By fitting a regression line through all points",
      "By majority vote among the k closest training points (by some distance metric)",
      "By computing the mean of all training labels",
      "By splitting the feature space with a decision boundary learned via gradient descent",
    ],
    1,
    "KNN is a lazy, instance-based method: it finds the k training points closest to the new point (typically by Euclidean distance) and predicts the majority class among them.",
    "There's no training phase that learns parameters — it just looks at nearby labeled examples.",
  ),
  mcq(
    12,
    20,
    "What is the goal of the k-means clustering algorithm?",
    [
      "To predict a continuous target using labeled data",
      "To partition unlabeled data into k groups by minimizing within-cluster distance to each cluster's centroid",
      "To classify data using a decision tree",
      "To reduce the number of features via correlation analysis",
    ],
    1,
    "k-means is an unsupervised algorithm that iteratively assigns points to the nearest of k centroids and updates centroids to the mean of assigned points, minimizing within-cluster variance.",
    "It's unsupervised — there are no labels, just a target number of groups, k.",
  ),
  mcq(
    13,
    20,
    "What is the main purpose of k-fold cross-validation?",
    [
      "To increase the size of the training dataset",
      "To get a more robust estimate of model performance by training/evaluating on multiple different splits of the data",
      "To eliminate the need for a test set entirely",
      "To automatically select the best features",
    ],
    1,
    "k-fold cross-validation splits the data into k folds, trains on k-1 folds and validates on the remaining one, repeating so every fold is used for validation once, giving a more reliable, lower-variance estimate of performance than a single train/validation split.",
    "The goal is a more stable performance estimate by rotating which slice of data is held out.",
  ),
  mcq(
    14,
    20,
    "What is the key difference between L1 (Lasso) and L2 (Ridge) regularization?",
    [
      "L1 can shrink coefficients exactly to zero (sparse solutions); L2 shrinks coefficients smoothly toward zero but rarely to exactly zero",
      "L2 performs automatic feature selection; L1 does not",
      "L1 only works on classification problems; L2 only works on regression",
      "There is no practical difference between them",
    ],
    0,
    "L1 regularization adds a penalty proportional to the absolute value of coefficients, which can drive some coefficients to exactly zero (effectively performing feature selection), while L2 adds a penalty proportional to the squared coefficients, shrinking them smoothly but rarely to exactly zero.",
    "One of them is famous for producing sparse models by zeroing out coefficients entirely.",
  ),
  mcq(
    15,
    20,
    "Why is feature scaling (e.g. standardization or min-max normalization) important for algorithms like KNN, SVMs, or gradient descent-based models?",
    [
      "It is never actually necessary for any algorithm",
      "Features on very different scales can dominate distance calculations or slow/destabilize gradient-based optimization",
      "It guarantees the model will not overfit",
      "It converts categorical variables into numbers",
    ],
    1,
    "Distance-based methods (KNN, SVM) and gradient descent are sensitive to feature scale: a feature ranging in the thousands can dominate a feature ranging 0-1, and unscaled features can make gradient descent converge slowly or unevenly, so scaling puts features on comparable footing.",
    "Think about what happens to a distance calculation when one feature ranges 0-1 and another ranges 0-100,000.",
  ),
  mcq(
    16,
    20,
    "In a binary classification confusion matrix, what does a 'false negative' represent?",
    [
      "The model predicted positive when the true label was negative",
      "The model predicted negative when the true label was positive",
      "The model predicted positive and the true label was positive",
      "The model predicted negative and the true label was negative",
    ],
    1,
    "A false negative is a case where the actual class was positive but the model incorrectly predicted negative — the model missed a true positive case.",
    "Focus on the word 'negative' in 'false negative': that's what the model predicted, and it was wrong.",
  ),
  mcq(
    17,
    20,
    "In a medical screening test where missing a disease case (false negative) is very costly, which metric should you prioritize optimizing?",
    ["Precision", "Recall", "Specificity of negative predictions only", "Training accuracy"],
    1,
    "Recall (true positives / (true positives + false negatives)) measures how many actual positive cases the model correctly catches, so maximizing recall minimizes costly missed (false negative) diagnoses.",
    "Recall is about catching as many real positive cases as possible, even at the cost of some false alarms.",
  ),
  mcq(
    18,
    20,
    "What does the ROC-AUC score represent for a binary classifier?",
    [
      "The percentage of correct predictions at a single fixed threshold",
      "The probability that the model ranks a randomly chosen positive example higher than a randomly chosen negative example, across all thresholds",
      "The mean squared error of the predicted probabilities",
      "The number of features used by the model",
    ],
    1,
    "ROC-AUC (area under the ROC curve) summarizes classifier performance across all classification thresholds and equals the probability that a randomly chosen positive instance is ranked higher (given a higher predicted score) than a randomly chosen negative instance.",
    "It's threshold-independent — think about ranking positives above negatives across the whole curve, not just one cutoff.",
  ),
  mcq(
    19,
    20,
    "In gradient descent, what role does the learning rate play?",
    [
      "It determines how many features are used",
      "It controls the size of the step taken in the direction that reduces the loss function at each iteration",
      "It sets the number of training examples used",
      "It decides which algorithm (SGD vs Adam) to use",
    ],
    1,
    "The learning rate scales how far parameters move in the direction of the negative gradient at each update step; too large can overshoot/diverge, too small can converge very slowly.",
    "It's a step-size knob, not related to data size or feature count directly.",
  ),
  mcq(
    20,
    20,
    "Why do you typically apply one-hot encoding to a nominal categorical feature (like 'city') before feeding it to most ML models?",
    [
      "To make the feature take up less memory",
      "To avoid implying a false ordinal relationship that would exist if the categories were mapped to arbitrary integers",
      "Because models can only accept string inputs",
      "To automatically balance class distributions",
    ],
    1,
    "Mapping nominal categories to plain integers (e.g. Paris=1, Tokyo=2, Cairo=3) would imply an ordering or magnitude relationship that doesn't exist; one-hot encoding creates independent binary columns so no false ordinal structure is introduced.",
    "The concern is about accidentally implying that one category is 'greater than' another when they're really just different labels.",
  ),
];

// Round 2: open-ended interview questions a Machine Learning Engineer / Data
// Scientist candidate should be ready to answer out loud, with a model
// answer to reveal and self-check against.
const interview = makeInterviewBuilder("ml-interview", "Machine Learning Interview Prep");

const round2Steps = [
  interview(
    1,
    15,
    "Can you explain the bias-variance tradeoff, ideally with a concrete example?",
    "Bias is the error from a model being too simple to capture the true pattern (underfitting), while variance is the error from a model being too sensitive to the specific training data (overfitting). For example, fitting a straight line to clearly curved data has high bias — it will be wrong in the same systematic way regardless of which training sample you use. Fitting a very high-degree polynomial to the same noisy data has high variance — it fits the training points almost perfectly but wiggles wildly and generalizes poorly to new data. The goal is to find a model complexity that minimizes total error by balancing both, often using cross-validation to pick that sweet spot.",
    "The interviewer is checking whether you understand model complexity as a tradeoff, not just definitions in isolation.",
    "Use two concrete models (e.g. straight line vs. high-degree polynomial) to anchor the explanation.",
  ),
  interview(
    2,
    15,
    "How do you handle class imbalance in a classification problem, for example fraud detection where only 1% of transactions are fraudulent?",
    "First, accuracy is a misleading metric here since predicting 'not fraud' every time gives 99% accuracy, so I'd switch to precision, recall, F1, or PR-AUC. On the data side, techniques include oversampling the minority class (e.g. SMOTE), undersampling the majority class, or using class weights in the loss function so the model penalizes missing the minority class more heavily. I'd also consider threshold tuning after training rather than assuming 0.5, and evaluate with a hold-out set that reflects the true class distribution, not an artificially balanced one, since deployment will see the real imbalance. Finally I'd validate with business-relevant costs — a false negative in fraud is often much costlier than a false positive.",
    "The interviewer wants to see you avoid the accuracy trap and know multiple concrete remedies, not just 'use SMOTE'.",
    "Start by naming why accuracy fails here, then give both data-level and algorithm-level fixes.",
  ),
  interview(
    3,
    15,
    "Walk me through how you'd choose between logistic regression and a random forest for a given classification problem.",
    "I'd start with the problem constraints: if interpretability, speed, or a need to explain individual coefficients to stakeholders/regulators matters, logistic regression is attractive, especially with a roughly linear decision boundary and limited data. If the relationship between features and target is likely nonlinear or involves complex interactions, and I have enough data and less need for interpretability, a random forest usually performs better out of the box with less feature engineering. I'd also weigh training/inference latency requirements and team maintenance capacity. In practice, I'd try both, compare via cross-validation on the actual business metric, and let the data decide rather than assuming one is always better.",
    "The interviewer is testing practical judgment about matching model choice to constraints (interpretability, data size, nonlinearity), not just 'random forest is always better'.",
    "Frame it around constraints — interpretability, data size, and nonlinearity — rather than declaring one model universally superior.",
  ),
  interview(
    4,
    15,
    "How does a random forest reduce variance compared to a single decision tree?",
    "A single deep decision tree tends to overfit and has high variance — small changes in training data can produce a very different tree. Random forests build many trees, each on a bootstrapped sample of the data and considering only a random subset of features at each split, which decorrelates the individual trees so their errors are less likely to align. Averaging (regression) or majority-voting (classification) across many decorrelated trees cancels out much of that individual variance while largely preserving the low bias of deep trees, so the ensemble generalizes better than any single tree.",
    "This tests whether you understand the mechanism (bagging plus feature randomness reduces correlation between trees) rather than just knowing 'more trees is better'.",
    "Mention both ingredients: bootstrapped sampling (bagging) and random feature subsets at each split.",
  ),
  interview(
    5,
    15,
    "What is regularization, and why does it help a model generalize better?",
    "Regularization adds a penalty term to the loss function based on the size of the model's coefficients (L1 penalizes absolute value, L2 penalizes squared value), discouraging the model from fitting the training data too closely by keeping weights smaller. This constrains model complexity, which reduces variance at the cost of a small increase in bias — usually a good tradeoff when a model is overfitting. L1 has the added benefit of driving some coefficients to exactly zero, effectively performing feature selection, while L2 tends to shrink all coefficients smoothly.",
    "Interviewers want to hear the mechanism — penalizing coefficient size to reduce variance — plus awareness that it's a bias-variance tradeoff, not free lunch.",
    "Explain it as constraining coefficient size, and connect it directly back to the bias-variance tradeoff.",
  ),
  interview(
    6,
    15,
    "How do you detect that a model is overfitting, and what would you actually do about it?",
    "The classic signal is a large gap between training performance and validation/test performance — very high training accuracy with much lower validation accuracy, or a validation loss that starts increasing while training loss keeps decreasing (visible in a learning curve). To address it, I'd try getting more training data, simplifying the model (fewer features, shallower trees, fewer parameters), adding regularization (L1/L2, dropout for neural nets), using cross-validation to tune hyperparameters more carefully, or applying early stopping. I'd pick the fix based on what's actually driving the overfitting rather than trying everything at once.",
    "This tests whether you can both diagnose overfitting from learning curves/metrics and prescribe a specific, prioritized remedy.",
    "Lead with the diagnostic signal (train/validation gap or diverging learning curves), then list remedies in a sensible order.",
  ),
  interview(
    7,
    15,
    "Explain precision versus recall, and describe a business scenario where you'd optimize for one over the other.",
    "Precision is the fraction of predicted positives that are actually positive (minimizing false positives), while recall is the fraction of actual positives the model successfully catches (minimizing false negatives). For a spam filter, I'd prioritize precision, because a false positive — a legitimate email marked as spam — can mean a missed job offer or important message, which is worse than an occasional spam email slipping through. Conversely, for cancer screening, I'd prioritize recall, because missing a true case (false negative) can be life-threatening, and a false positive just leads to a follow-up test.",
    "The interviewer wants to see you translate a statistical definition into a real cost tradeoff tied to business or human consequences.",
    "Pick two contrasting real examples (like spam vs. medical screening) to show you understand the asymmetric cost of errors.",
  ),
  interview(
    8,
    15,
    "How would you validate a model before deploying it to production, beyond just checking test-set accuracy?",
    "I'd first make sure there's no train/test leakage — no features derived using information that wouldn't be available at prediction time (e.g. a future value, or a target-derived aggregate computed before splitting). I'd check performance across relevant slices (different regions, time periods, user segments) rather than just an aggregate metric, since a good overall score can hide poor performance on an important subgroup. I'd also validate on more recent, out-of-time data to catch data drift, since training data and production data distributions can diverge over time, and set up monitoring for input feature drift and prediction drift after deployment, not just a one-time check before launch.",
    "This tests awareness that offline test accuracy isn't sufficient — leakage, slice-level performance, and drift are common real-world failure modes.",
    "Cover three things: leakage checks, subgroup/slice performance, and drift monitoring over time.",
  ),
  interview(
    9,
    15,
    "Explain gradient descent and the role of the learning rate in intuitive terms.",
    "Gradient descent is an iterative optimization method that adjusts model parameters in the direction that most reduces the loss function, computed via the gradient (the slope of the loss with respect to each parameter). Intuitively, it's like walking downhill on a loss surface, always stepping in the steepest downward direction to reach a minimum. The learning rate controls how big each step is: too large and you can overshoot the minimum or even diverge, oscillating wildly; too small and training converges very slowly and can get stuck in flat regions or take far too long. In practice, techniques like learning rate schedules or adaptive optimizers (Adam) adjust the step size over training to balance speed and stability.",
    "Interviewers check both the mechanical understanding (following the gradient downhill) and practical intuition about learning rate tradeoffs.",
    "Use the 'walking downhill' metaphor, then explicitly cover what happens if the learning rate is too big versus too small.",
  ),
  interview(
    10,
    15,
    "What is cross-validation, and why specifically use k-fold rather than a single train/validation split?",
    "Cross-validation evaluates a model's performance by repeatedly splitting the data into different train/validation partitions and averaging the results, giving a more reliable estimate than any single split. In k-fold cross-validation specifically, the data is divided into k roughly equal folds; the model trains on k-1 folds and validates on the remaining fold, rotating which fold is held out until every fold has served as validation once. This is more robust than a single split because it reduces the risk that one lucky or unlucky split gives a misleading performance estimate, and it uses all the data for both training and validation across the k rounds, which is especially valuable with a smaller dataset.",
    "The interviewer wants confirmation you understand k-fold reduces variance in the performance estimate itself, not just that it's a validation technique.",
    "Emphasize that a single split is itself a random sample, and k-fold averages over several such samples.",
  ),
  interview(
    11,
    15,
    "How do you handle a categorical variable with very high cardinality, like a 'zip code' or 'product ID' column with thousands of unique values?",
    "One-hot encoding would explode the feature space and create very sparse, mostly-zero columns, so I'd avoid it here. Common alternatives include target/mean encoding (replacing each category with a smoothed statistic of the target, careful to compute it only on training folds to avoid leakage), frequency encoding, hashing tricks (feature hashing into a fixed number of buckets), or embedding layers if using a neural network, which learn a dense low-dimensional representation of each category. I'd also consider grouping rare categories into an 'other' bucket if many values appear only a handful of times, to reduce noise and overfitting risk.",
    "This tests knowledge beyond basic one-hot/label encoding and awareness of the leakage risk in target encoding specifically.",
    "Name at least two alternatives to one-hot (like target encoding and hashing) and flag the leakage risk of target encoding.",
  ),
  interview(
    12,
    15,
    "Explain the difference between bagging and boosting.",
    "Bagging (bootstrap aggregating) trains multiple models independently and in parallel on different bootstrapped samples of the data, then averages or votes their predictions — random forest is the classic example — and it primarily reduces variance. Boosting trains models sequentially, where each new model focuses on correcting the errors (residuals or misclassifications) of the previous ensemble, combining them in a weighted way — gradient boosting and AdaBoost are examples — and it primarily reduces bias while also often improving variance, though it can be more prone to overfitting if not regularized (e.g. via learning rate, tree depth, early stopping).",
    "The interviewer wants the structural distinction (parallel/independent vs. sequential/corrective) and which error component each primarily addresses.",
    "Contrast 'parallel and independent' with 'sequential and error-correcting', and name one algorithm for each.",
  ),
  interview(
    13,
    15,
    "How would you explain a model's predictions to a non-technical stakeholder who wants to know why a specific customer was flagged as high churn risk?",
    "I'd avoid discussing coefficients or gradients directly and instead use a feature importance or explanation tool like SHAP to show which specific factors pushed that individual prediction up or down — for example, 'this customer's risk score was high mainly because of a recent drop in usage and two support tickets in the last month, partially offset by their long tenure.' I'd present it visually (a simple bar chart of top contributing factors) rather than raw numbers, and tie it back to an action the stakeholder can take, like a targeted retention offer, rather than just the abstract score itself.",
    "This tests communication skill and knowledge of interpretability tools (SHAP/feature importance), applied to a specific individual prediction, not just global model behavior.",
    "Mention a concrete tool (SHAP or feature importance) and describe framing the explanation around a specific customer's contributing factors.",
  ),
  interview(
    14,
    15,
    "What is data leakage, and how do you prevent it?",
    "Data leakage happens when information that wouldn't be available at prediction time in production accidentally makes its way into training, causing the model to look much better offline than it will perform in reality. Common sources include computing preprocessing statistics (like mean/scaling parameters, or target encodings) on the full dataset before splitting instead of fitting them only on the training fold, including a feature that's a proxy for or derived from the target (e.g. a 'was refunded' flag when predicting fraud), or using future information in a time-series problem. Prevention means splitting data first before any fitting of transformations, using pipelines that fit preprocessing only on training folds within cross-validation, and carefully auditing features for any that could only exist because the outcome already happened.",
    "The interviewer is checking that you know leakage is often subtle (in preprocessing/CV, not just in obviously duplicated features) and know concrete prevention steps.",
    "Give a concrete example of leakage through preprocessing done before the train/test split, not just an obvious duplicated feature.",
  ),
  interview(
    15,
    15,
    "How do you decide a model is 'good enough' to ship to production?",
    "First, performance has to beat a clear baseline (a simple heuristic, a previous model, or a business rule) by a margin that's meaningful, not just statistically distinguishable. I'd tie the decision to a business metric, not just an ML metric — for example, does this reduce fraud losses or improve conversion by an amount that justifies the engineering cost of deployment. I'd also consider robustness (performance across important subgroups and on recent out-of-time data), operational constraints like latency and monitoring/rollback readiness, and often ship via a staged rollout or A/B test so real-world impact is measured before full commitment, rather than relying solely on offline metrics.",
    "The interviewer wants to see you connect model quality to business impact and deployment risk management, not treat a single offline metric as the whole answer.",
    "Anchor 'good enough' to a baseline comparison and a business metric, then mention staged rollout/A-B testing as the real-world validation step.",
  ),
];

export const ML_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1: Foundations",
      summary:
        "Core machine learning concepts, algorithms, and evaluation techniques used to build, validate, and reason about models.",
      topics: ["Fundamentals"],
      steps: round1Steps,
    },
    {
      number: 2,
      title: "Round 2: Interview Prep",
      summary:
        "Open-ended, real interview-style questions about model selection, evaluation, generalization, and explaining ML systems to stakeholders.",
      topics: ["Machine Learning Interview Prep"],
      steps: round2Steps,
    },
  ],
};
