import {type Course, makeInterviewBuilder, makeMcqBuilder} from "./course-types";

// Round 1: Power BI fundamentals every BI Analyst/Developer candidate is
// expected to know cold — Desktop vs Service, data modeling (star schema),
// Power Query (M) vs DAX, calculated columns vs measures, core DAX functions,
// relationships, visuals, and publishing/refresh/security basics.
const mcq = makeMcqBuilder("Power BI Fundamentals");

const round1Steps = [
  mcq(
    1,
    20,
    "What is the primary difference between Power BI Desktop and Power BI Service?",
    [
      "Desktop is used to author reports and models locally; Service is the cloud platform used to publish, share, schedule refresh, and collaborate on them",
      "Desktop is only for viewing reports; Service is only for building them",
      "They are two names for the exact same product with no functional difference",
      "Desktop is a mobile app; Service only runs on-premises",
    ],
    0,
    "Power BI Desktop is the free Windows authoring tool for building data models, queries, and reports; Power BI Service (app.powerbi.com) is the cloud workspace where published reports are hosted, shared, scheduled to refresh, and consumed as dashboards.",
    "Think 'build locally' vs 'host and share in the cloud'.",
  ),
  mcq(
    2,
    20,
    "In a star schema data model, how do fact tables and dimension tables differ?",
    [
      "Fact tables contain measurable, quantitative data (sales amount, quantity, cost) plus foreign keys; dimension tables contain descriptive attributes (product name, region, date) used to filter and group facts",
      "Dimension tables store the numeric measures and fact tables store the descriptive attributes",
      "Fact tables and dimension tables always have identical columns",
      "Dimension tables cannot be related to fact tables",
    ],
    0,
    "Fact tables are typically long and narrow, holding quantitative measures and keys that link to dimension tables, which provide the descriptive 'who, what, where, when' context you slice and group those measures by.",
    "Facts = numbers to aggregate; dimensions = context to group by.",
  ),
  mcq(
    3,
    20,
    "How do Power Query (M) and DAX differ in purpose within Power BI?",
    [
      "Power Query connects to, cleans, and shapes data before it's loaded into the model; DAX is a formula language for calculations (measures and calculated columns) evaluated within the already-loaded model",
      "DAX is used to import data from external sources; Power Query is used only for formatting visuals",
      "They are interchangeable and always produce identical results",
      "DAX only works in Excel, never in Power BI",
    ],
    0,
    "Power Query (M) runs during refresh to connect, clean, and reshape source data before it lands in the model; DAX runs against the already-loaded model to define measures, calculated columns, and calculated tables.",
    "One shapes data on the way in; the other calculates once it's already in the model.",
  ),
  mcq(
    4,
    20,
    "What is the key difference between a calculated column and a measure, and why are measures usually preferred for totals?",
    [
      "A calculated column is computed row-by-row and stored in the model; a measure is computed dynamically in the current filter context and isn't stored, so it correctly re-aggregates at any level without bloating the model",
      "A measure is stored in every row of the table; a calculated column recalculates per visual",
      "Calculated columns cannot be used in visuals at all",
      "There is no real difference; they always return identical results",
    ],
    0,
    "Calculated columns are evaluated once per row at refresh time and physically stored, increasing model size, while measures are evaluated dynamically based on the current filter context (slicers, visual groupings), so a single measure like Total Sales stays correct at any level without redundant stored values.",
    "One gets baked into the table; the other is calculated live and adapts to whatever a visual is grouped or filtered by.",
  ),
  mcq(
    5,
    20,
    "What does the CALCULATE function do in DAX?",
    [
      "It only sums a column, nothing else",
      "It evaluates an expression in a modified filter context, letting you add, replace, or remove filters",
      "It sorts a table by a given column",
      "It creates a new relationship between two tables",
    ],
    1,
    "CALCULATE takes an expression and one or more filter arguments, evaluates those filters, and then computes the expression in that new (modified) filter context — it's the primary mechanism for context transition in DAX.",
    "It's the function that lets you say 'calculate this, but under these different filter conditions'.",
  ),
  mcq(
    6,
    20,
    "What does the DAX FILTER function return?",
    [
      "A single scalar value",
      "A table containing only the rows of the input table that satisfy a given condition",
      "A visual-level slicer",
      "A boolean TRUE/FALSE value",
    ],
    1,
    "FILTER(table, condition) iterates row by row over the table and returns a new table consisting only of the rows where the condition evaluates to TRUE; it's most commonly used as an argument inside CALCULATE.",
    "Its output is a table, which is why it's so often nested inside CALCULATE.",
  ),
  mcq(
    7,
    20,
    "What does the DAX ALL function do when used inside CALCULATE, e.g. CALCULATE(SUM(Sales[Amount]), ALL(Sales))?",
    [
      "It removes all existing filters on the specified table (or column), so the calculation ignores slicers/filters applied to it",
      "It applies every filter in the report simultaneously",
      "It deletes the table from the model",
      "It sorts all rows in the table alphabetically",
    ],
    0,
    "ALL() returns all rows of a table (or all values of a column) ignoring any filters currently in effect, which is why it's used to compute things like 'percent of grand total' that shouldn't be affected by the current slicer selection.",
    "Think of it as clearing filters rather than adding them.",
  ),
  mcq(
    8,
    20,
    "What is the purpose of the DAX SUMX function compared to plain SUM?",
    [
      "SUMX can only be used on text columns",
      "SUMX iterates row by row over a table, evaluates an expression for each row, and sums the results — useful when the value to sum isn't a single existing column",
      "SUMX is identical to SUM in every way",
      "SUMX ignores the current filter context entirely",
    ],
    1,
    "SUMX is an iterator: SUMX(Sales, Sales[Quantity] * Sales[UnitPrice]) computes quantity times price per row and adds up the results, whereas SUM only aggregates a single pre-existing column such as SUM(Sales[Amount]).",
    "The 'X' suffix marks it as a row-by-row iterator function, not a simple column aggregator.",
  ),
  mcq(
    9,
    20,
    "What does the RELATED function do in DAX?",
    [
      "It creates a brand-new relationship between two tables",
      "It retrieves a value from a related table on the 'one' side of a one-to-many relationship, from the perspective of a row on the 'many' side",
      "It removes a relationship from the model",
      "It duplicates a table entirely",
    ],
    1,
    "RELATED lets a calculated column (or expression) on the many side pull in a corresponding value from the one side of an existing relationship, such as fetching a Product[Category] value onto each row of the Sales fact table.",
    "It only works across an existing relationship, and it pulls from the 'one' side.",
  ),
  mcq(
    10,
    20,
    "How do row context and filter context differ in DAX?",
    [
      "Row context is the awareness of 'which row' a formula is evaluating (inherent in calculated columns and iterators like SUMX); filter context is the combined set of active filters (slicers, visual groupings, CALCULATE) that determines which rows a measure sees",
      "They are two names for exactly the same concept",
      "Row context only applies to measures; filter context only applies to calculated columns",
      "Filter context is set once per report and never changes",
    ],
    0,
    "Row context means the formula 'knows' which row it's on and can reference other columns in that row (calculated columns, or iterators like SUMX/FILTER/RELATED); filter context is the set of active filters from slicers, visual axes, and CALCULATE that narrows which rows are considered, which is why the same measure can return different values in a KPI card versus a matrix broken out by region.",
    "One is 'which row am I on'; the other is 'which filters are currently applied'.",
  ),
  mcq(
    11,
    20,
    "In a one-to-many relationship between a Date dimension and a Sales fact table, which side is typically the 'one' side, and what does 'cross-filter direction' control?",
    [
      "The Date table is the 'one' side since each date appears once; cross-filter direction controls whether filtering flows from the 'one' side to the 'many' side only (single) or both ways (bidirectional)",
      "The Sales fact table is the 'one' side since it has more rows; cross-filter direction controls the color of the relationship line",
      "Neither table has a 'one' side; cross-filter direction only matters in DirectQuery mode",
      "The 'one' side is whichever table was imported first, and cross-filter direction cannot be changed",
    ],
    0,
    "The Date table holds one row per unique date (the 'one' side) while many Sales rows reference the same date (the 'many' side); cross-filter direction then governs whether filters propagate only from the one side to the many side (the safer default) or bidirectionally, which can otherwise create ambiguous filter paths.",
    "First identify which table has one row per key; then think about which way filters are allowed to travel across that relationship.",
  ),
  mcq(
    12,
    20,
    "What is the purpose of a slicer visual in a Power BI report?",
    [
      "It performs data transformation before load",
      "It lets report viewers interactively filter all the other visuals on the page by selecting one or more values",
      "It only displays static text",
      "It exports the report to PDF",
    ],
    1,
    "A slicer is a visual filter control (list, dropdown, date range, etc.) that, when the viewer makes a selection, filters every other visual on the page that is connected to that field, enabling interactive exploration.",
    "It's the visual users click on to narrow down what everything else on the page shows.",
  ),
  mcq(
    13,
    20,
    "Which visual choice fits each scenario: a single running KPI number, a trend over time, and a pivot-style breakdown with subtotals?",
    [
      "Card for the KPI number, line chart for the trend over time, and matrix for the pivot-style breakdown with subtotals",
      "Pie chart for all three, since it can always substitute for any other visual",
      "Matrix for the KPI number, card for the trend, and line chart for the pivot-style breakdown",
      "Bar chart is the only visual Power BI supports for numeric data",
    ],
    0,
    "A card is built for a single glanceable number, a line chart is best for showing how a measure changes across an ordered axis like time, and a matrix supports nested row/column groupings with expandable subtotals like an Excel pivot table — each visual has a distinct job.",
    "Match each need (one number, trend, grouped breakdown) to the visual literally designed for it.",
  ),
  mcq(
    14,
    20,
    "What is a Quick Measure in Power BI?",
    [
      "A manually hand-written, highly optimized DAX formula only advanced users can create",
      "A pre-built calculation (like running total or percent of total) that Power BI generates automatically from a guided dialog, producing the underlying DAX for you",
      "A measure that only works in DirectQuery mode",
      "A type of relationship between two tables",
    ],
    1,
    "Quick Measures offer a menu of common calculation patterns (running total, percentage of total, year-over-year change, etc.); you fill in fields through a dialog and Power BI generates the corresponding DAX measure automatically, which is also a good way to learn DAX patterns.",
    "It's a guided, dialog-driven shortcut that writes common DAX patterns for you.",
  ),
  mcq(
    15,
    20,
    "How does drill-down differ from drillthrough?",
    [
      "Drill-down expands a hierarchy within the same visual (e.g. Year to Quarter to Month); drillthrough lets a user right-click a data point to navigate to a separate, filtered detail page",
      "They are the same feature under two names",
      "Drill-down only works on tables, drillthrough only works on cards",
      "Drill-down requires DirectQuery mode",
    ],
    0,
    "Drill-down moves through levels of a defined hierarchy while staying on the same visual/page, whereas drillthrough sends you to a different, purpose-built detail page automatically filtered to the clicked context — a 'summary to detail' navigation flow.",
    "One stays in the same visual and goes deeper into a hierarchy; the other jumps to another page entirely.",
  ),
  mcq(
    16,
    20,
    "What is a bookmark used for in Power BI reports?",
    [
      "It saves a snapshot of the current report state (filters, slicer selections, visibility of objects) that can be recalled later, often used to build guided narratives or toggle views",
      "It is only used to bookmark a page in a web browser",
      "It permanently deletes visuals from a page",
      "It is required before you can publish a report",
    ],
    0,
    "A bookmark captures the report's current state — which filters/slicers are set, which visuals are shown or hidden, and the current view — so a button or navigation menu can jump back to that exact state, commonly used for storytelling or toggling between chart views.",
    "It's a saved 'state snapshot' of the report, not a browser feature.",
  ),
  mcq(
    17,
    20,
    "What triggers a scheduled refresh in Power BI Service, and how does this relate to Import mode versus DirectQuery?",
    [
      "A configured schedule reruns the Power Query steps against the source and reloads the model for Import mode datasets; DirectQuery datasets instead query the source live on every interaction, so there is no cached copy to refresh in the same way",
      "Scheduled refresh only exists for DirectQuery datasets, never for Import mode",
      "The report automatically refreshes every time anyone opens it, regardless of storage mode",
      "You must manually re-publish the .pbix file every time data changes, even with scheduled refresh configured",
    ],
    0,
    "For Import mode datasets, scheduled refresh (configured in Power BI Service, subject to gateway/data source support) automatically re-runs the Power Query steps at set times to pull fresh data into the cached model; DirectQuery instead sends a live query to the source on every visual interaction, so it stays current without needing a scheduled reload of stored data.",
    "Think about which mode actually has a stored copy that needs reloading on a schedule.",
  ),
  mcq(
    18,
    20,
    "What does 'publishing to Power BI Service' actually do?",
    [
      "It deletes the local .pbix file",
      "It uploads the report and its dataset from Power BI Desktop to a workspace in the cloud Service, making it available to share, schedule refresh for, and view in a browser",
      "It converts the report into a Word document",
      "It only publishes the visuals, not the underlying data model",
    ],
    1,
    "Publishing sends the .pbix file's report and dataset to a chosen workspace in Power BI Service, where it can then be shared with others, embedded, scheduled for refresh, and viewed through the browser or mobile app instead of only in Desktop.",
    "Think 'upload from Desktop to the cloud workspace', not conversion to another file format.",
  ),
  mcq(
    19,
    20,
    "What is Row-Level Security (RLS) in Power BI used for, e.g. so each regional sales manager sees only their own region's data in one shared report?",
    [
      "Restricting which visuals a user can add to a report",
      "Restricting which rows of data a given user sees when they view a report, using roles with DAX filter rules mapped to their identity (e.g. their region)",
      "Encrypting the entire dataset so nobody can view it",
      "Limiting how many refreshes occur per day",
    ],
    1,
    "RLS defines roles with DAX filter rules (e.g. filtering the Region table to the current user, or [Region] = USERNAME()) so that when a user assigned to that role opens the report, they only see the rows permitted for them — the same shared report can show different data to different viewers, such as each manager seeing only their own region.",
    "It's about filtering rows per viewer's identity, not restricting report design capabilities.",
  ),
  mcq(
    20,
    20,
    "Why is a well-designed star schema generally recommended over a single flat wide table in Power BI?",
    [
      "Flat tables always load faster regardless of size",
      "A star schema (fact + dimension tables) reduces data duplication, is more efficient for the VertiPaq engine to compress, and makes DAX filter/relationship logic simpler and more predictable",
      "Power BI cannot create relationships in a flat table at all",
      "Star schemas are only relevant for SQL Server, not Power BI",
    ],
    1,
    "Star schemas normalize descriptive attributes into dimension tables, which reduces repeated text data (helping VertiPaq's columnar compression), keeps relationships and filter propagation simple and predictable, and generally scales and performs better than one denormalized flat table.",
    "It's about compression efficiency and simpler, predictable filter propagation, not raw load speed of a single table.",
  ),
];

// Round 2: open-ended interview questions a BI Analyst/Developer candidate
// should be ready to answer out loud, with a model answer to reveal and
// self-check against.
const interview = makeInterviewBuilder("powerbi-interview", "Power BI Interview Prep");

const round2Steps = [
  interview(
    1,
    15,
    "Explain the difference between a calculated column and a measure, and when you'd use each.",
    "A calculated column is evaluated row-by-row at refresh time and physically stored in the model, so it's useful when you need a static, row-level value to slice or group by, like extracting a Year from a Date column or concatenating a full name. A measure is evaluated dynamically at query time within whatever filter context the visual applies, so it's the right choice for aggregations like Total Sales, Average Margin, or any ratio that must recalculate correctly whether you're looking at one product or the whole company. In general I default to measures for anything that gets aggregated, since they keep the model smaller and adapt automatically, and only use calculated columns when I need the value available as a row attribute for filtering, sorting, or relationships.",
    "The interviewer is checking whether you understand row context versus filter context and can justify the tradeoff, not just recite the definitions.",
    "Lead with 'stored per row vs computed on the fly', then give one concrete example of each.",
  ),
  interview(
    2,
    15,
    "Explain CALCULATE and why it's considered the most important DAX function.",
    "CALCULATE evaluates an expression inside a modified filter context — you pass it a base expression plus one or more filter arguments, and it applies those filters (adding, replacing, or removing existing ones) before evaluating the expression. It's foundational because almost every non-trivial DAX pattern relies on it: year-over-year comparisons, percent-of-total calculations, comparing a subset against ALL(), or applying a fixed business rule like 'only include completed orders' regardless of what the user has sliced by. Once you understand CALCULATE's context transition behavior, most other advanced DAX patterns become variations on the same idea.",
    "This tests whether the candidate actually understands filter context manipulation, the core concept the rest of DAX is built on.",
    "Explain it as 'modifying filter context before evaluating an expression', then name one pattern it enables.",
  ),
  interview(
    3,
    15,
    "Walk through how you'd design a star schema for a sales dashboard.",
    "I'd start by identifying the fact table — sales transactions, with numeric measures like quantity, unit price, and discount, plus foreign keys pointing to each dimension. Then I'd build out dimension tables: Date (for time intelligence), Product (with category/subcategory hierarchy), Customer, and Store/Region, each with one row per unique entity and no duplicated transactional data. I'd connect each dimension to the fact table via a single-direction, one-to-many relationship (dimension is the 'one' side), avoid snowflaking unless a dimension is very large, and keep the fact table narrow — just keys and measures — so DAX measures and Power Query loads stay fast and the model is easy to reason about.",
    "The interviewer wants to see practical modeling judgment: correct grain, clean relationships, and recognition of why dimensions and facts are separated.",
    "Name the fact table and its measures first, then list the dimensions and how they connect.",
  ),
  interview(
    4,
    15,
    "Explain row context versus filter context in DAX with an example.",
    "Row context is the awareness of 'which row am I currently on' — it exists naturally inside a calculated column and is created explicitly by iterator functions like SUMX or FILTER, letting a formula reference other columns in that same row, e.g. Sales[Quantity] * Sales[UnitPrice] inside SUMX. Filter context is the set of filters currently applied to the whole calculation — from slicers, visual row/column groupings, or CALCULATE — that determines which rows are considered at all, e.g. a Total Sales measure returns a different number depending on which region a slicer has filtered to. The tricky part, and where CALCULATE's context transition matters, is that row context does not automatically become filter context unless something like CALCULATE inside an iterator converts the current row into an equivalent single-row filter.",
    "This is one of the most common DAX interview questions because misunderstanding it causes the majority of real-world DAX bugs.",
    "Give one example that's purely row context (a calculated column) and one that's purely filter context (a slicer-driven measure).",
  ),
  interview(
    5,
    15,
    "How would you troubleshoot a report that's loading very slowly?",
    "I'd first isolate whether the bottleneck is the data model/query or the visuals: Performance Analyzer in Power BI Desktop breaks down time spent per visual into DAX query time, visual rendering time, and 'other', which tells you where to focus. If DAX query time dominates, I'd check for expensive patterns like unnecessary iterators over huge tables, bidirectional relationships causing ambiguous filter propagation, or overly complex measures, and consider DAX Studio to see the generated query plan. If it's a DirectQuery model, I'd look at the source database's own query performance and indexing. Other common fixes are reducing the number of visuals per page, removing unused columns to shrink the model, and pre-aggregating in Power Query or the source rather than doing heavy row-level DAX at query time.",
    "The interviewer wants a systematic diagnostic process, not a random guess at 'reduce visuals'.",
    "Mention Performance Analyzer as your first diagnostic step, then branch based on what it shows.",
  ),
  interview(
    6,
    15,
    "Explain the difference between Import mode and DirectQuery mode, and the tradeoffs of each.",
    "Import mode loads a compressed copy of the source data into Power BI's in-memory VertiPaq engine, which makes visuals extremely fast since everything is queried locally, but the data is only as fresh as the last scheduled refresh and there are dataset size limits depending on license. DirectQuery instead sends a live query back to the source database for every visual interaction, so data is always current and there's no duplicate copy of large datasets, but performance is entirely dependent on how fast the source system can respond, and some DAX functions and modeling features are restricted. I'd choose Import for most reporting scenarios where near-real-time data isn't critical, and DirectQuery when data must be live (e.g. operational dashboards) or the source is too large to import practically, sometimes combining both with composite models.",
    "This tests whether the candidate can reason about real performance/freshness tradeoffs, not just define the two modes.",
    "Contrast 'fast but cached' versus 'live but source-dependent', then mention composite models as a middle ground.",
  ),
  interview(
    7,
    15,
    "How would you implement row-level security so each regional manager only sees their region's data?",
    "I'd create a security role in Power BI Desktop's Manage Roles dialog and add a DAX filter expression on the Region (or Sales) table, something like [Region] = USERNAME() if regions map directly to user identities, or more commonly a filter against a mapping table that links each user's email to the region(s) they're allowed to see, using a relationship so the filter propagates to the fact table. After publishing, I'd assign users or Azure AD security groups to that role in Power BI Service's dataset security settings, and test it using 'View As' in Desktop or Service to confirm each manager only sees their own region before rolling it out.",
    "The interviewer is checking hands-on familiarity with RLS setup, not just the concept of row-level security.",
    "Mention the DAX role filter, a user-to-region mapping table, and testing with 'View As'.",
  ),
  interview(
    8,
    15,
    "How do you handle a many-to-many relationship in Power BI's data model?",
    "Power BI does support native many-to-many relationships directly between two tables, but I still prefer resolving it with a bridge table where possible — a table containing the unique combination of keys from both sides — because it keeps filter propagation predictable and avoids ambiguous or duplicated aggregation results. For example, if customers can have multiple accounts and accounts can belong to multiple customers, I'd build a bridge table of customer-account pairs and relate both original tables to it, rather than connecting them directly. I'd also be careful about cross-filter direction and test the specific aggregations that touch that relationship, since many-to-many is one of the most common sources of double-counting bugs.",
    "Interviewers want to know you recognize many-to-many as a risk area and have a concrete resolution pattern, not just that the feature technically exists.",
    "Mention the bridge-table pattern as your default, and note the double-counting risk.",
  ),
  interview(
    9,
    15,
    "Explain a time-intelligence DAX calculation like year-to-date or same-period-last-year.",
    "Time intelligence functions rely on having a proper Date dimension table marked as the model's date table, with a contiguous range of dates and a relationship to the fact table's date key. A year-to-date measure would look like TOTALYTD(SUM(Sales[Amount]), 'Date'[Date]), which uses CALCULATE under the hood to filter dates from the start of the fiscal/calendar year up through the current context's latest date. A same-period-last-year measure typically uses CALCULATE(SUM(Sales[Amount]), SAMEPERIODLASTYEAR('Date'[Date])), which shifts the current date filter back exactly one year while keeping everything else in context the same, letting you build YoY comparison visuals.",
    "This checks both DAX syntax knowledge and the prerequisite understanding that time intelligence requires a proper date table.",
    "Mention the date table requirement first, then name TOTALYTD or SAMEPERIODLASTYEAR as the function.",
  ),
  interview(
    10,
    15,
    "How would you design a dashboard for an executive audience versus one for an operational team?",
    "An executive dashboard should lead with a small number of high-level KPIs (revenue, margin, YoY growth) on cards or simple trend visuals, minimal clutter, clear color-coded status (RAG indicators), and the ability to drill down only if they want more detail — executives typically scan in seconds, not minutes. An operational dashboard, by contrast, serves people who need to act on the data daily, so it should show more granular, near-real-time detail — individual orders, tickets, or shipments — with filters/slicers for their specific area, sortable tables, and alerts for exceptions they need to address. I'd also consider refresh cadence: executives are usually fine with daily refresh, while operational teams often need much more frequent or DirectQuery-based near-live data.",
    "The interviewer wants to see audience-driven design thinking, not just visual preferences.",
    "Contrast 'few KPIs, glanceable' for executives versus 'granular, actionable, frequent refresh' for operational teams.",
  ),
  interview(
    11,
    15,
    "What's your process for validating that numbers in a new report match the source system?",
    "I start by picking a few simple, well-understood totals (e.g. total revenue for last month) and reconciling them directly against a known-good source, like a SQL query run straight against the source database or an existing trusted report. If those match, I test edge cases — a single filtered slice, a period with known missing or duplicate data, and any calculated measure with nontrivial logic like a ratio or year-over-year comparison. I pay close attention to relationship cardinality and filter direction, since double-counting from a many-to-many or bidirectional relationship is one of the most common causes of numbers being subtly wrong, and I document the reconciliation so stakeholders can trust the report before go-live.",
    "This tests rigor and awareness of the common failure modes (double-counting, wrong grain) rather than just 'I checked it looked right'.",
    "Mention reconciling against a direct source query first, then testing edge cases like filters and ratios.",
  ),
  interview(
    12,
    15,
    "Explain what a bidirectional relationship is and why you'd generally avoid it.",
    "A bidirectional (both-direction cross-filter) relationship lets filters propagate both from the 'one' side to the 'many' side and back from the 'many' side to the 'one' side, instead of the default single direction. It's occasionally necessary, such as for certain many-to-many scenarios, but I avoid it as a default because it can create ambiguous filter paths when multiple tables are involved, sometimes causing Power BI to silently produce unexpected or duplicated results, and it can hurt performance since the engine has to evaluate more complex filter propagation. I'd only enable it deliberately for a specific, tested scenario, and prefer single-direction relationships plus explicit CALCULATE-based filters or bridge tables when I need similar behavior in a more controlled way.",
    "The interviewer wants to see that the candidate understands bidirectional filtering isn't 'free' and carries real correctness and performance risk.",
    "Define the mechanism first, then name ambiguous filter paths and performance as the reasons to avoid it by default.",
  ),
  interview(
    13,
    15,
    "How would you optimize a Power BI model with millions of rows?",
    "First I'd make sure the model is a proper star schema rather than a flat wide table, since VertiPaq compresses normalized, low-cardinality dimension columns far better than repeated text in one huge table. Then I'd remove unused columns and rows before load (in Power Query, push filtering upstream to the source where possible), reduce high-cardinality columns like unique IDs or unrounded decimals that compress poorly, and convert calculated columns to measures wherever possible so nothing unnecessary is stored. For very large fact tables, I'd consider building aggregation tables (pre-summarized at a coarser grain) with Power BI's aggregations feature, so most visuals hit the small aggregated table while only detailed drill-throughs hit the full-grain table.",
    "This tests knowledge of concrete, real optimization levers (star schema, column cardinality, aggregations) rather than vague 'make it faster' answers.",
    "Mention star schema and cardinality reduction first, then aggregation tables as the advanced technique.",
  ),
  interview(
    14,
    15,
    "Explain the difference between Power Query transformations and DAX measures in terms of when they execute.",
    "Power Query (M) transformations execute during data load/refresh — they run once per refresh cycle to clean, reshape, filter, and combine source data before it's compressed into the model, so their cost is paid at refresh time, not when someone opens a report. DAX measures execute at query time, meaning every time a visual needs to display a value, the measure's expression is recalculated against the current filter context — so their cost is paid repeatedly, every time a user interacts with a report. This is why heavy row-level cleanup belongs in Power Query (paid once at refresh) while context-dependent aggregation logic belongs in DAX measures (which must react live to slicers), and why an expensive DAX measure can slow down report interaction even if refresh itself is fast.",
    "This checks whether the candidate understands the performance implications of where logic lives, not just the syntactic difference between M and DAX.",
    "Frame it as 'refresh-time cost' (Power Query) versus 'every-click cost' (DAX measures).",
  ),
  interview(
    15,
    15,
    "How would you set up and communicate a scheduled refresh failure to stakeholders?",
    "In Power BI Service I'd configure refresh failure notifications to alert the dataset owner (and ideally a shared distribution list or Teams/email integration) immediately when a scheduled refresh fails, rather than relying on someone noticing stale data. I'd also check the refresh history and error details to diagnose the root cause quickly — common culprits are gateway connectivity issues, changed source schema, or credential expiration — and fix or escalate promptly. For communication, I'd proactively tell affected stakeholders that the data may be stale as of a specific timestamp before they ask, rather than letting them discover a wrong number on their own, and once resolved, confirm the next successful refresh timestamp so they know the report is trustworthy again.",
    "The interviewer wants to see both the technical setup (alerts, gateway/credential troubleshooting) and the professional judgment to proactively communicate data staleness.",
    "Mention configuring refresh failure alerts first, then proactive stakeholder communication about stale data.",
  ),
];

export const POWERBI_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1: Foundations",
      summary:
        "Core Power BI concepts: Desktop vs Service, star schema modeling, Power Query vs DAX, calculated columns vs measures, key DAX functions, relationships, visuals, and refresh/security basics.",
      topics: ["Fundamentals"],
      steps: round1Steps,
    },
    {
      number: 2,
      title: "Round 2: Interview Prep",
      summary:
        "Open-ended, real interview-style questions about DAX, data modeling, performance tuning, security, and dashboard design.",
      topics: ["Power BI Interview Prep"],
      steps: round2Steps,
    },
  ],
};
