import {type Course, makeInterviewBuilder, makeMcqBuilder} from "./course-types";

// Round 1: Python fundamentals every data science candidate is expected to know
// cold — syntax, core data structures, functions, comprehensions, and the
// NumPy/pandas basics that show up in almost every take-home exercise.
const mcq = makeMcqBuilder("Python Fundamentals");

const round1Steps = [
  mcq(
    1,
    20,
    "Which data type is immutable in Python?",
    ["list", "dict", "tuple", "set"],
    2,
    "Tuples cannot be changed after creation (no item assignment, append, etc.), unlike lists, dicts, and sets.",
    "Think about which structure uses parentheses () and is often used for fixed records like coordinates.",
  ),
  mcq(
    2,
    20,
    "What does len([1, 2, [3, 4], 5]) return?",
    ["3", "4", "5", "TypeError"],
    1,
    "The nested list [3, 4] counts as a single element, so the outer list has 4 elements: 1, 2, [3,4], 5.",
    "len() only counts top-level items, it does not look inside nested lists.",
  ),
  mcq(
    3,
    20,
    "Which keyword creates a generator function instead of a normal function?",
    ["return", "yield", "async", "lambda"],
    1,
    "A function containing yield becomes a generator: calling it returns a generator object that produces values lazily.",
    "It's the keyword you use instead of return, one value at a time.",
  ),
  mcq(
    4,
    20,
    "What is the output of [x**2 for x in range(5) if x % 2 == 0]?",
    ["[0, 4, 16]", "[0, 1, 4, 9, 16]", "[1, 9]", "[0, 2, 4]"],
    0,
    "range(5) gives 0,1,2,3,4; keeping even x (0,2,4) and squaring gives [0, 4, 16].",
    "First filter for even numbers, then square what's left.",
  ),
  mcq(
    5,
    20,
    "Which method adds a key/value pair to a dict only if the key is not already present?",
    ["dict.update()", "dict.setdefault()", "dict.get()", "dict.pop()"],
    1,
    "setdefault(key, default) inserts the key with the default value only when it's missing, and returns the existing value otherwise.",
    "Its name literally describes 'set a default' for a missing key.",
  ),
  mcq(
    6,
    20,
    "In pandas, which method removes rows containing any missing values?",
    ["df.fillna()", "df.dropna()", "df.drop_duplicates()", "df.isnull()"],
    1,
    "df.dropna() drops rows (or columns, with axis=1) that contain NaN values by default.",
    "The opposite of filling missing values is dropping them.",
  ),
  mcq(
    7,
    20,
    "What does the following return? sorted([3, 1, 2], reverse=True)",
    ["[1, 2, 3]", "[3, 2, 1]", "[2, 1, 3]", "None"],
    1,
    "sorted() with reverse=True sorts ascending first, then reverses, giving [3, 2, 1].",
    "reverse=True just flips the normal ascending order.",
  ),
  mcq(
    8,
    20,
    "Which NumPy function creates an array of 5 evenly spaced values between 0 and 1 inclusive?",
    ["np.arange(0, 1, 5)", "np.linspace(0, 1, 5)", "np.zeros(5)", "np.random.rand(5)"],
    1,
    "np.linspace(start, stop, num) returns num evenly spaced samples over [start, stop], inclusive of both endpoints by default.",
    "The name combines 'linear' and 'space'.",
  ),
  mcq(
    9,
    20,
    "What is the result of 10 // 3 in Python?",
    ["3.33", "3", "4", "1"],
    1,
    "// is floor division; 10 // 3 truncates toward negative infinity, giving 3 (the remainder 1 is discarded).",
    "This is integer/floor division, not the regular division operator /.",
  ),
  mcq(
    10,
    20,
    "Which statement about Python's GIL (Global Interpreter Lock) is true?",
    [
      "It prevents any two Python processes from running at once",
      "It allows only one thread to execute Python bytecode at a time within a process",
      "It only exists in Python 2",
      "It speeds up all multi-threaded numeric code",
    ],
    1,
    "The GIL is a per-process lock that lets only one thread execute Python bytecode at a time, which is why CPU-bound work often uses multiprocessing instead of threading.",
    "It's a per-process limitation on threads, not processes.",
  ),
  mcq(
    11,
    20,
    "What does *args allow a function to accept?",
    [
      "A variable number of positional arguments packed into a tuple",
      "A variable number of keyword arguments packed into a dict",
      "Only one optional argument",
      "A required list argument",
    ],
    0,
    "*args collects any number of extra positional arguments into a tuple inside the function.",
    "It's the star before args, not kwargs.",
  ),
  mcq(
    12,
    20,
    "Which pandas method groups rows and computes an aggregate per group in one step?",
    ["df.pivot()", "df.groupby('col').agg('mean')", "df.merge()", "df.melt()"],
    1,
    "groupby splits the DataFrame by the given column(s), and .agg() (or .mean(), .sum(), etc.) computes a summary statistic per group.",
    "Think split-apply-combine: group first, then aggregate.",
  ),
  mcq(
    13,
    20,
    "What will `print(type(5 / 2))` output in Python 3?",
    ["<class 'int'>", "<class 'float'>", "<class 'complex'>", "<class 'str'>"],
    1,
    "In Python 3, / is true division and always returns a float, even when both operands are ints.",
    "Python 3 changed / from Python 2's floor-division-on-ints behavior.",
  ),
  mcq(
    14,
    20,
    "Which is the correct way to open a file so it is automatically closed even if an error occurs?",
    [
      "f = open('data.csv'); f.read()",
      "with open('data.csv') as f: f.read()",
      "open('data.csv').read().close()",
      "File.read('data.csv')",
    ],
    1,
    "The `with` statement is a context manager: it guarantees f.close() runs even if an exception happens inside the block.",
    "It's the pattern using the `with` keyword.",
  ),
  mcq(
    15,
    20,
    "What does `df['col'].value_counts()` return in pandas?",
    [
      "The sum of the column",
      "A Series of unique values and how often each appears, sorted descending by count",
      "The number of missing values",
      "The column converted to a list",
    ],
    1,
    "value_counts() tallies occurrences of each distinct value in the Series and sorts them from most to least frequent by default.",
    "It's about counting how many times each value shows up.",
  ),
  mcq(
    16,
    20,
    "Which of these correctly defines a lambda that squares a number?",
    ["lambda x: x ** 2", "lambda x = x ** 2", "def lambda(x): x ** 2", "lambda: x ** 2"],
    0,
    "Lambda syntax is `lambda <params>: <expression>`, so `lambda x: x ** 2` is a correct anonymous function.",
    "The colon separates parameters from the single expression that gets returned.",
  ),
  mcq(
    17,
    20,
    "Why is vectorizing operations with NumPy/pandas usually faster than a Python for-loop over rows?",
    [
      "Vectorized operations run in compiled C code and avoid per-element Python interpreter overhead",
      "for-loops are not allowed on arrays",
      "Vectorization uses less memory in every case",
      "It automatically parallelizes across machines",
    ],
    0,
    "NumPy/pandas push the loop down into optimized, compiled C/Fortran routines operating on contiguous memory, avoiding the overhead of the Python bytecode interpreter running once per element.",
    "It's about where the loop actually executes: Python bytecode vs. compiled code.",
  ),
  mcq(
    18,
    20,
    "What is the output of `list(zip([1,2,3], ['a','b']))`?",
    [
      "[(1,'a'), (2,'b'), (3, None)]",
      "[(1,'a'), (2,'b')]",
      "[1, 2, 3, 'a', 'b']",
      "TypeError",
    ],
    1,
    "zip() stops at the shortest iterable, so pairing [1,2,3] with ['a','b'] only produces two tuples: (1,'a') and (2,'b').",
    "zip() is only as long as its shortest input.",
  ),
  mcq(
    19,
    20,
    "Which exception should you catch to handle a missing dictionary key safely with `d[key]`?",
    ["IndexError", "KeyError", "ValueError", "AttributeError"],
    1,
    "Accessing a missing key with square-bracket indexing raises KeyError; .get(key, default) avoids the exception entirely.",
    "Key... error. It's named after the thing that's missing.",
  ),
  mcq(
    20,
    20,
    "What does `pip install -r requirements.txt` do?",
    [
      "Installs a single package named requirements.txt",
      "Installs every package (and pinned version) listed in the requirements.txt file",
      "Uninstalls all packages",
      "Creates a new virtual environment",
    ],
    1,
    "The -r flag tells pip to read a requirements file and install each listed dependency, which is the standard way to reproduce a Python environment.",
    "The -r stands for 'requirements file'.",
  ),
];

// Round 2: open-ended interview questions a Data Scientist / ML Engineer
// candidate should be ready to answer out loud, with a model answer to
// reveal and self-check against.
const interview = makeInterviewBuilder("python-interview", "Python Interview Prep");

const round2Steps = [
  interview(
    1,
    15,
    "How would you explain the difference between a list and a tuple to someone deciding which to use, and when would you actually choose one over the other?",
    "Lists are mutable and meant for collections that change (append/remove/sort); tuples are immutable and meant for fixed, often heterogeneous records. Tuples are also hashable (when their contents are), so they can be dict keys or set members, and they're slightly faster/lighter than lists. Choose a tuple for a fixed-shape record (e.g. a coordinate, a row returned from a database), and a list when the collection will grow, shrink, or be reordered.",
    "Interviewers use this to see if you know 'mutability' isn't just trivia — it drives real design decisions like using tuples as dict keys.",
    "Lead with mutability, then mention hashability and a concrete use case for each.",
  ),
  interview(
    2,
    15,
    "You have a 10-million-row pandas DataFrame and a colleague wrote a for-loop over df.iterrows() to compute a new column. Why is this slow, and how would you fix it?",
    "iterrows() reconstructs a Series object for every row, which is extremely slow and also silently upcasts mixed dtypes. The fix is to vectorize: use built-in Series/DataFrame arithmetic and boolean masks (e.g. df['new'] = df['a'] * 2 + df['b']), or df.apply() only as a last resort, and NumPy ufuncs for numeric work. For row-wise logic that can't vectorize, np.where, pd.cut, or a compiled path (Cython/Numba) are better than a Python-level loop.",
    "This is a very common real interview question because it tests practical performance intuition, not just syntax.",
    "Name iterrows() as the anti-pattern, then explain vectorization as the fix.",
  ),
  interview(
    3,
    15,
    "What is a Python decorator, and can you describe a realistic use case you've seen or could imagine using one for in a data pipeline?",
    "A decorator is a function that takes another function (or class) and returns a modified version of it, typically using the @decorator syntax as sugar for `func = decorator(func)`. Realistic uses in data work: @timer to log how long a data-loading function takes, @retry to re-run a flaky API call with backoff, @lru_cache to memoize an expensive pure function, or a @staticmethod/@property in a class-based feature pipeline.",
    "Good answers connect the abstract mechanism ('a function wrapping a function') to something practical like logging or caching.",
    "Define it mechanically first (function wrapping function), then give one concrete example.",
  ),
  interview(
    4,
    15,
    "How do you handle missing data in a dataset before modeling, and what factors influence whether you drop rows versus impute values?",
    "First quantify how much is missing and whether it's missing completely at random, at random, or not at random (MCAR/MAR/MNAR) — that shapes the right strategy. If missingness is small and random, dropping rows (dropna) is simplest and safest. If a column has heavy missingness but is informative, impute (mean/median for numeric, mode or a new 'missing' category for categorical, or a model-based imputer like KNNImputer/IterativeImputer), and often add a boolean 'was_missing' indicator column so the model can learn from the missingness pattern itself. Avoid leaking information from the test set into imputation statistics.",
    "Strong answers mention MCAR/MAR/MNAR and leakage, not just 'I'd use fillna'.",
    "Start with 'how much and why is it missing', then branch into drop vs. impute.",
  ),
  interview(
    5,
    15,
    "Explain the difference between `df.merge()` and `pd.concat()` and when you'd use each.",
    "merge() joins two DataFrames on one or more key columns (like a SQL JOIN — inner/left/right/outer), aligning rows by matching values. concat() stacks DataFrames along an axis (rows by default, or columns) without matching on keys — it's for combining datasets that share the same structure, like appending monthly files together. Use merge when you need to combine related information from two tables via a shared id; use concat when you're stacking similar-shaped chunks of data.",
    "The key distinction interviewers want: key-based alignment (merge) vs. positional stacking (concat).",
    "Compare it directly to SQL JOIN vs. UNION/append.",
  ),
  interview(
    6,
    15,
    "What are Python generators, and why might you use one instead of returning a full list when processing a large dataset?",
    "A generator produces values lazily, one at a time, via yield, instead of building the entire sequence in memory up front. For large or streaming datasets (e.g. reading a multi-GB file line by line, or processing an API's paginated results), a generator keeps memory usage constant instead of O(n), and lets downstream code start processing before the whole dataset is available. The tradeoff is you can only iterate once and can't index into it randomly.",
    "This tests whether you think about memory footprint, a common real bottleneck with large datasets.",
    "Contrast memory usage: list is O(n) upfront, generator is O(1) per step.",
  ),
  interview(
    7,
    15,
    "How would you structure error handling in a data pipeline that ingests files from an external source that sometimes sends malformed data?",
    "Wrap the risky I/O/parsing step in narrow try/except blocks that catch specific exceptions (e.g. pd.errors.ParserError, KeyError, ValueError) rather than a bare except. Log the offending record/file with enough context to debug later, and decide per-error whether to skip-and-continue (for a single bad row) or fail-fast (for a corrupt whole file), rather than silently swallowing everything. Consider routing bad records to a 'dead letter' location instead of dropping them, so nothing is silently lost.",
    "Interviewers are checking that you don't reach for a blanket try/except: pass, which hides real bugs.",
    "Emphasize specific exceptions, logging, and a decision between skip vs. fail.",
  ),
  interview(
    8,
    15,
    "What's the difference between `==` and `is` in Python, and why does this matter when comparing to `None`?",
    "== checks value equality (can be overridden via __eq__), while `is` checks object identity (same object in memory). None is a singleton, so `is None` is both faster and unambiguous, and is the recommended style (PEP 8) since a custom __eq__ on some object could otherwise make `obj == None` behave unexpectedly.",
    "A short, precise answer here signals real Python fluency versus surface-level knowledge.",
    "Identity vs. equality, then explain why None specifically uses `is`.",
  ),
  interview(
    9,
    15,
    "Describe how you would use virtual environments (or conda environments) and why they matter for reproducible data science work.",
    "A virtual environment isolates a project's package versions from the system Python and from other projects, avoiding version conflicts (e.g. one project needing pandas 1.x, another needing 2.x). Combined with a requirements.txt or environment.yml (pinned versions), it lets a teammate or a production server recreate the exact same environment, which is essential for reproducible results and for avoiding 'it works on my machine' bugs.",
    "Mention both the isolation problem and the reproducibility/pinning angle.",
    "Isolation first, reproducibility (pinned deps) second.",
  ),
  interview(
    10,
    15,
    "How does Python's list comprehension compare to a `map()`/`filter()` combination, and is one always faster?",
    "Both ultimately loop in C under the hood, so performance is usually similar and neither is a strict winner; comprehensions are generally considered more readable in Python and can express filter+transform in one line (`[f(x) for x in xs if cond(x)]`). map()/filter() can be marginally faster with an already-defined function (no per-iteration lambda overhead) but readability, not raw speed, is usually the deciding factor in real codebases.",
    "Good answers avoid overclaiming a big speed difference and focus on readability/idiom.",
    "Say they're comparable in speed; the real differentiator is readability.",
  ),
  interview(
    11,
    15,
    "What is broadcasting in NumPy, and why does it matter for writing efficient numeric code?",
    "Broadcasting lets NumPy perform element-wise operations on arrays of different but compatible shapes (e.g. adding a shape-(3,) vector to every row of a shape-(5,3) matrix) without explicitly copying data to match shapes. It matters because it lets you write concise vectorized expressions instead of manual loops, and NumPy implements it without materializing the expanded array in memory, keeping operations fast.",
    "Use a concrete shape example (like adding a row vector to a matrix) to show real understanding.",
    "Define compatible shapes, then give one small worked example.",
  ),
  interview(
    12,
    15,
    "Walk through how you'd debug a Python script that's raising a `MemoryError` while processing a large CSV.",
    "First check whether the whole file is being loaded at once (e.g. pd.read_csv without chunksize) and switch to chunked reading (chunksize=) or a more memory-efficient format (Parquet, or dtype downcasting like float64→float32, object→category). Profile actual memory usage (memory_profiler, or df.memory_usage(deep=True)) to find which columns/steps are the biggest consumers, and consider processing in a streaming fashion or on a machine with more RAM only after ruling out avoidable inefficiency.",
    "Interviewers want a diagnostic process, not just 'buy more RAM'.",
    "Chunking and dtype downcasting are the two most common concrete fixes to mention.",
  ),
  interview(
    13,
    15,
    "What's the difference between shallow copy and deep copy in Python, and when has this bitten you (or could it) with nested data like a list of dicts?",
    "A shallow copy (list.copy(), copy.copy()) creates a new outer container but still references the same nested objects, so mutating a nested dict inside a 'copied' list also mutates the original. A deep copy (copy.deepcopy()) recursively copies every nested object so the two structures are fully independent. This matters whenever you copy a list of dicts/lists and then mutate the inner objects expecting the original to be untouched.",
    "A concrete example (list of dicts) shows you understand the practical bug, not just the definition.",
    "Explain with 'new outer, same inner' vs 'everything copied recursively'.",
  ),
  interview(
    14,
    15,
    "How would you explain `*args` and `**kwargs` to a junior engineer, and why do library functions like pandas' `read_csv` use them?",
    "*args collects extra positional arguments into a tuple, and **kwargs collects extra keyword arguments into a dict, letting a function accept a flexible, open-ended set of inputs. Libraries like pandas use **kwargs so a function can forward arbitrary options down to an underlying parser/engine (e.g. encoding, delimiter) without every wrapper function having to explicitly list every possible parameter, which keeps the public API stable as new options get added.",
    "Tie the mechanism to the real reason libraries use it: forwarding flexible options.",
    "Mechanism first (tuple vs dict), then the API-design reason libraries rely on it.",
  ),
  interview(
    15,
    15,
    "Suppose a stakeholder asks you to speed up a Python data-processing script that's 'too slow.' What's your process before you start changing code?",
    "First profile before optimizing: use cProfile, line_profiler, or simple timing to find the actual bottleneck rather than guessing. Common culprits are Python-level loops over rows, repeated I/O, or unnecessary copies. Once the bottleneck is identified, apply the targeted fix (vectorize, cache/memoize, switch data structure, parallelize with multiprocessing for CPU-bound work, or reduce I/O), then re-measure to confirm the fix actually helped before declaring victory.",
    "The core message interviewers want: measure first, don't optimize blindly.",
    "Lead with 'profile first', then name one or two concrete fixes.",
  ),
];

export const PYTHON_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1: Foundations",
      summary:
        "Core Python syntax, data structures, functions, and the pandas/NumPy basics used in everyday data work.",
      topics: ["Fundamentals"],
      steps: round1Steps,
    },
    {
      number: 2,
      title: "Round 2: Interview Prep",
      summary:
        "Open-ended, real interview-style questions about performance, pandas/NumPy internals, and data pipeline design.",
      topics: ["Python Interview Prep"],
      steps: round2Steps,
    },
  ],
};
