import {type Course, makeInterviewBuilder, makeMcqBuilder} from "./course-types";

// Round 1: SQL fundamentals a Data/Business Analyst is expected to know cold —
// query execution order, joins, aggregates, window functions, CTEs, and the
// common pitfalls (fan-out, NULL handling) that show up in everyday reporting.
const mcq = makeMcqBuilder("SQL for Analytics Fundamentals");

const round1Steps = [
  mcq(
    1,
    20,
    "What is the logical order of execution for a SQL query with SELECT, FROM, WHERE, GROUP BY, HAVING, and ORDER BY?",
    [
      "SELECT, FROM, WHERE, GROUP BY, HAVING, ORDER BY",
      "FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY",
      "FROM, SELECT, WHERE, GROUP BY, HAVING, ORDER BY",
      "WHERE, FROM, GROUP BY, SELECT, HAVING, ORDER BY",
    ],
    1,
    "SQL is evaluated logically as FROM/JOIN, then WHERE (row filtering), then GROUP BY, then HAVING (group filtering), then SELECT, then ORDER BY — even though we write SELECT first, it's resolved after grouping and filtering.",
    "Think about what has to exist before you can filter groups or reference a column alias.",
  ),
  mcq(
    2,
    20,
    "Why can't you filter on an aggregate like COUNT(*) using WHERE?",
    [
      "WHERE only accepts string comparisons",
      "WHERE is evaluated before GROUP BY has produced any aggregates, so aggregates aren't available yet",
      "COUNT(*) is not a valid aggregate function",
      "WHERE can only be used with JOIN clauses",
    ],
    1,
    "WHERE filters individual rows before grouping happens, so aggregate values don't exist yet at that stage; HAVING runs after GROUP BY and can filter on aggregate results.",
    "Ask yourself: at the point WHERE runs, do groups even exist yet?",
  ),
  mcq(
    3,
    20,
    "You INNER JOIN orders to customers. A customer with no matching orders will:",
    [
      "Appear once with NULLs for order columns",
      "Not appear in the result at all",
      "Cause the query to error",
      "Appear once per column in customers",
    ],
    1,
    "INNER JOIN only returns rows where the join condition matches on both sides, so customers with zero matching orders are excluded entirely; a LEFT JOIN would be needed to keep them with NULLs.",
    "INNER JOIN keeps only the intersection — think Venn diagram overlap.",
  ),
  mcq(
    4,
    20,
    "What's the key difference between LEFT JOIN and RIGHT JOIN?",
    [
      "LEFT JOIN keeps all rows from the first (left) table, filling unmatched right-side columns with NULL; RIGHT JOIN does the same for the second (right) table",
      "LEFT JOIN only works with numeric keys",
      "RIGHT JOIN is faster because it reads right-to-left",
      "There is no difference, they are aliases for the same operation",
    ],
    0,
    "LEFT JOIN preserves every row from the left table regardless of a match; RIGHT JOIN preserves every row from the right table. Swapping table order and using the other keyword produces equivalent results.",
    "The name tells you which side is guaranteed to be fully preserved.",
  ),
  mcq(
    5,
    20,
    "A FULL OUTER JOIN between table A and table B returns:",
    [
      "Only rows that match in both tables",
      "All rows from A only",
      "All rows from A and B, with NULLs where there is no match on either side",
      "A cartesian product of A and B",
    ],
    2,
    "FULL OUTER JOIN combines LEFT and RIGHT JOIN behavior: every row from both tables is kept, with NULLs filled in wherever a matching row doesn't exist on the other side.",
    "It's the union of what LEFT JOIN and RIGHT JOIN would each return.",
  ),
  mcq(
    6,
    20,
    "What is the difference between COUNT(*) and COUNT(column_name)?",
    [
      "They are always identical",
      "COUNT(*) counts all rows including those with NULL in column_name; COUNT(column_name) skips rows where column_name is NULL",
      "COUNT(column_name) is faster in every database",
      "COUNT(*) only works on the primary key",
    ],
    1,
    "COUNT(*) counts rows regardless of NULLs, while COUNT(column) only counts rows where that specific column has a non-NULL value — a common source of subtly different totals in reports.",
    "One counts rows, the other counts non-missing values in a specific column.",
  ),
  mcq(
    7,
    20,
    "Which function would you use to count the number of distinct customers who placed an order?",
    ["COUNT(customer_id)", "COUNT(DISTINCT customer_id)", "SUM(customer_id)", "AVG(customer_id)"],
    1,
    "COUNT(DISTINCT customer_id) deduplicates customer_id before counting, so a customer with 5 orders is counted once instead of 5 times.",
    "Plain COUNT would count every order row, even repeat orders from the same customer.",
  ),
  mcq(
    8,
    20,
    "What does ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) produce?",
    [
      "A running total of order amounts per customer",
      "A sequential integer (1, 2, 3, ...) for each customer's orders, restarting at 1 for every new customer, ordered by date",
      "The total count of orders per customer, repeated on every row",
      "A random unique ID for each row",
    ],
    1,
    "PARTITION BY resets the numbering for each customer group, and ORDER BY determines the sequence within that group, so each customer's earliest order gets row number 1, the next gets 2, and so on.",
    "PARTITION BY is like a GROUP BY that doesn't collapse rows — it just resets the counter per group.",
  ),
  mcq(
    9,
    20,
    "You need to rank products by sales, but ties should receive the same rank with no gap in the following rank number. Which function do you use?",
    ["ROW_NUMBER()", "RANK()", "DENSE_RANK()", "NTILE()"],
    2,
    "DENSE_RANK() assigns the same rank to ties and does not skip subsequent rank values (e.g. 1,1,2), whereas RANK() would skip to 3 after two rows tied at 1.",
    "The word 'dense' hints that no rank numbers are skipped.",
  ),
  mcq(
    10,
    20,
    "What does LAG(revenue, 1) OVER (ORDER BY month) return for each row?",
    [
      "The revenue value from the next row",
      "The revenue value from the previous row (1 row back) in the ordered result",
      "The maximum revenue seen so far",
      "The average of all revenue values",
    ],
    1,
    "LAG looks backward by the specified offset (default 1), returning the value from a prior row in the window's order — commonly used to compare a metric to its previous period, like month-over-month.",
    "LAG lags behind — it looks back in time; LEAD looks forward.",
  ),
  mcq(
    11,
    20,
    "Which window function expression computes a running (cumulative) total of daily revenue ordered by date?",
    [
      "SUM(revenue) OVER (ORDER BY date)",
      "SUM(revenue) OVER (PARTITION BY date)",
      "AVG(revenue) OVER ()",
      "COUNT(revenue) OVER (ORDER BY date)",
    ],
    0,
    "SUM(revenue) OVER (ORDER BY date), with the default frame of RANGE/ROWS UNBOUNDED PRECEDING TO CURRENT ROW, accumulates the sum of all rows up to and including the current row, producing a running total.",
    "The ORDER BY inside OVER (without a PARTITION BY) creates an expanding window from the start up to the current row.",
  ),
  mcq(
    12,
    20,
    "What is the main practical benefit of a CTE (WITH clause) over a nested subquery?",
    [
      "CTEs always execute faster than subqueries",
      "CTEs let you name and reuse an intermediate result, making multi-step logic easier to read and maintain",
      "CTEs can only be used with SELECT *",
      "Subqueries cannot reference any table more than once",
    ],
    1,
    "A CTE gives an intermediate result set a name you can reference (even multiple times) later in the query, which breaks a complex query into readable, sequential steps — functionally similar to a subquery but far easier to follow and debug.",
    "Think readability and reuse, not raw performance — most engines optimize them similarly.",
  ),
  mcq(
    13,
    20,
    "How would you bucket customers into 'Low', 'Medium', and 'High' spend tiers based on total_spend in a SELECT?",
    [
      "GROUP BY total_spend",
      "CASE WHEN total_spend < 100 THEN 'Low' WHEN total_spend < 500 THEN 'Medium' ELSE 'High' END",
      "WHERE total_spend IN ('Low', 'Medium', 'High')",
      "ORDER BY total_spend DESC",
    ],
    1,
    "CASE WHEN evaluates conditions in order and returns the label for the first match, which is exactly how you turn a continuous numeric column into readable categorical buckets for reporting.",
    "You need conditional logic that returns a label per row, not a filter or an aggregation.",
  ),
  mcq(
    14,
    20,
    "You want to report revenue by month regardless of the exact day it happened. Which approach is standard?",
    [
      "GROUP BY revenue",
      "GROUP BY DATE_TRUNC('month', order_date)",
      "WHERE order_date = 'month'",
      "ORDER BY order_date DESC LIMIT 1",
    ],
    1,
    "DATE_TRUNC('month', order_date) rounds every date down to the first day of its month, so grouping by that expression rolls up all days within a month into one bucket for monthly reporting.",
    "You need a function that collapses a full date down to just its month.",
  ),
  mcq(
    15,
    20,
    "What is wrong with the condition WHERE discount_code = NULL?",
    [
      "Nothing, it correctly finds rows with no discount code",
      "NULL comparisons with = always evaluate to unknown/false, so this returns no rows; IS NULL should be used instead",
      "NULL cannot appear in a WHERE clause at all",
      "= NULL only works with numeric columns",
    ],
    1,
    "In SQL, NULL represents 'unknown', so any comparison using = (or !=) against NULL evaluates to unknown, not true — meaning the row is excluded. IS NULL / IS NOT NULL are the correct operators for checking nullability.",
    "NULL is not a value you can equal — it's the absence of one.",
  ),
  mcq(
    16,
    20,
    "Which expression returns the first non-NULL value from a list of columns, useful for filling in a default?",
    ["ISNULL(a)", "COALESCE(a, b, c)", "NULLIF(a, b)", "CAST(a AS NULL)"],
    1,
    "COALESCE(a, b, c) evaluates its arguments left to right and returns the first one that is not NULL, commonly used to substitute a fallback value when a preferred column is missing.",
    "It 'coalesces' several possible values down into one usable result.",
  ),
  mcq(
    17,
    20,
    "What is the key difference between UNION and UNION ALL?",
    [
      "UNION ALL requires the same column names, UNION does not",
      "UNION removes duplicate rows across the combined result sets, while UNION ALL keeps all rows including duplicates",
      "UNION only works on two tables, UNION ALL works on more",
      "UNION ALL is always slower and never used in practice",
    ],
    1,
    "UNION performs an implicit deduplication pass across the combined rows (which costs extra sorting/hashing), while UNION ALL simply concatenates all rows from both queries without checking for duplicates, making it cheaper when you know duplicates aren't a concern.",
    "One of them does extra work to guarantee uniqueness.",
  ),
  mcq(
    18,
    20,
    "What is a self-join typically used for?",
    [
      "Joining a table to itself, e.g. to compare each employee's salary to their manager's salary stored in the same employees table",
      "Joining a table to a view of itself only for performance testing",
      "A join that always returns zero rows",
      "Combining two completely unrelated tables",
    ],
    0,
    "A self-join joins a table to itself (using two aliases) so you can compare rows within the same table to each other, such as matching each employee row to their manager's row via a manager_id that also references employees.id.",
    "Think of comparing rows within one table to other rows in that same table.",
  ),
  mcq(
    19,
    20,
    "A report joins orders to order_line_items and then does SUM(orders.total_amount). The total comes out several times too high. What's the most likely cause?",
    [
      "SUM() is broken in this database",
      "The join fans out: each order has multiple line-item rows, so orders.total_amount gets duplicated and summed once per line item",
      "The orders table itself has duplicate rows",
      "GROUP BY was used instead of ORDER BY",
    ],
    1,
    "Joining a one-row-per-order table to a many-rows-per-order table multiplies each order row once per matching line item, so an order-level column like total_amount gets repeated and over-summed — a classic 'fan-out' bug. The fix is to aggregate line items first (or sum at the correct grain) before joining.",
    "Ask: after the join, how many rows now exist per original order?",
  ),
  mcq(
    20,
    20,
    "Which clause is used to filter groups after aggregation, e.g. only show customers with more than 5 orders?",
    ["WHERE COUNT(*) > 5", "HAVING COUNT(*) > 5", "GROUP BY COUNT(*) > 5", "ORDER BY COUNT(*) > 5"],
    1,
    "HAVING runs after GROUP BY has computed aggregates, so it's the correct clause to filter on an aggregate result like COUNT(*); WHERE cannot reference aggregates because it runs before grouping.",
    "This is the aggregate-aware sibling of WHERE.",
  ),
];

// Round 2: open-ended interview questions a Data/Business Analyst candidate
// should be ready to answer out loud — analytical query patterns, debugging
// joins, and communicating SQL logic to non-technical stakeholders.
const interview = makeInterviewBuilder("sql-analytics-interview", "SQL for Analytics Interview Prep");

const round2Steps = [
  interview(
    1,
    15,
    "How would you write a query to find the second-highest order amount per customer?",
    "I'd use a window function rather than nested MAX() logic, since it naturally handles per-customer ranking. Something like: WITH ranked AS (SELECT customer_id, order_amount, DENSE_RANK() OVER (PARTITION BY customer_id ORDER BY order_amount DESC) AS rnk FROM orders) SELECT customer_id, order_amount FROM ranked WHERE rnk = 2. I'd use DENSE_RANK() instead of ROW_NUMBER() if I want ties on the highest amount to still count as rank 1, so the 'second highest' is a genuinely different value, not just the next row.",
    "This tests whether you reach for window functions instead of fragile self-joins or nested MAX(MAX()) subqueries, and whether you think about how ties should be handled.",
    "Think PARTITION BY customer_id plus a rank function, then filter rank = 2.",
  ),
  interview(
    2,
    15,
    "Explain the difference between WHERE and HAVING with a concrete example.",
    "WHERE filters individual rows before any grouping happens, while HAVING filters groups after GROUP BY has produced aggregates. For example, WHERE order_date >= '2026-01-01' restricts which raw orders are considered, but SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id HAVING COUNT(*) > 10 filters out customers whose total order count is 10 or fewer — you can't write that condition in WHERE because COUNT(*) doesn't exist yet at that stage of execution.",
    "The interviewer wants to confirm you understand SQL's logical execution order, not just that both clauses 'filter stuff'.",
    "Anchor the answer on when each clause runs relative to GROUP BY.",
  ),
  interview(
    3,
    15,
    "How would you calculate a 7-day rolling average of daily revenue using SQL?",
    "I'd use a window function with an explicit frame: SELECT date, revenue, AVG(revenue) OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_7d_avg FROM daily_revenue. The ROWS BETWEEN 6 PRECEDING AND CURRENT ROW frame includes the current day plus the six before it, giving a true 7-day window as long as the underlying table has exactly one row per calendar day with no gaps — if dates can be missing, I'd first generate a complete date spine and left join revenue onto it so the window doesn't silently skip missing days.",
    "This checks that you know window frame syntax (ROWS BETWEEN) and that you think about data gaps, not just the happy path.",
    "You need an explicit ROWS BETWEEN frame, and consider whether every date actually exists in the table.",
  ),
  interview(
    4,
    15,
    "Walk through how you'd find duplicate rows in a table and how you'd remove them safely.",
    "First I'd identify duplicates by grouping on the columns that should be unique and filtering for a count greater than one: SELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1. To actually remove them, I'd avoid a blind DELETE and instead use ROW_NUMBER() OVER (PARTITION BY email ORDER BY created_at) inside a CTE to tag which copy to keep (rn = 1) and which are extras (rn > 1), then delete only the rn > 1 rows. I'd always run the SELECT version first to review exactly which rows would be removed before running the DELETE, ideally inside a transaction.",
    "The interviewer is checking that you have a safe, reviewable process and don't just run a destructive DELETE based on a guess.",
    "Detect with GROUP BY/HAVING, then dedupe with ROW_NUMBER() so you can choose which copy survives.",
  ),
  interview(
    5,
    15,
    "Explain window functions vs GROUP BY and when you need one over the other.",
    "GROUP BY collapses multiple rows into one row per group, so you lose row-level detail and can only see the aggregate. Window functions like SUM() OVER (PARTITION BY ...) compute the same kind of aggregate but keep every original row intact, attaching the aggregate value alongside the detail. I'd use GROUP BY when I only need the summary (e.g. total revenue per region), and a window function when I need both the detail and the aggregate together, like showing each order's amount next to that customer's running total or their rank among peers.",
    "This tests whether you understand that window functions preserve row-level granularity, which is the core practical difference analysts rely on.",
    "The key word is 'collapse' vs 'preserve' — does the row count change or stay the same?",
  ),
  interview(
    6,
    15,
    "How would you debug a query that's returning more rows than expected after a JOIN (fan-out)?",
    "I'd first check the expected grain: how many rows should exist per key on each side of the join. Then I'd run COUNT(*) on each table's key column grouped by that key to see if either side has multiple matching rows — e.g. SELECT order_id, COUNT(*) FROM order_line_items GROUP BY order_id HAVING COUNT(*) > 1 — which reveals a one-to-many relationship causing the join to duplicate the 'one' side. The fix is usually to aggregate the many-side table down to the join grain in a CTE before joining, so each key only contributes one row, or to explicitly account for the multiplication if it's actually intended.",
    "This tests real debugging instinct: can you isolate which side of the join is multiplying rows rather than just re-running the query and guessing.",
    "Check for one-to-many relationships on the join key before assuming the aggregate function is wrong.",
  ),
  interview(
    7,
    15,
    "How would you calculate month-over-month growth rate using LAG?",
    "I'd first aggregate revenue by month, then use LAG to pull the prior month's value into the same row: WITH monthly AS (SELECT DATE_TRUNC('month', order_date) AS month, SUM(amount) AS revenue FROM orders GROUP BY 1) SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS prev_revenue, (revenue - LAG(revenue) OVER (ORDER BY month)) / LAG(revenue) OVER (ORDER BY month) AS mom_growth FROM monthly. I'd also guard against division by zero or NULL for the very first month, since there's no prior month to compare against.",
    "The interviewer wants to see that you know LAG is the tool for period-over-period comparisons and that you think about the edge case of the first row having no predecessor.",
    "Aggregate to monthly grain first, then LAG the revenue column over an ORDER BY month window.",
  ),
  interview(
    8,
    15,
    "Explain the difference between a CTE and a subquery, and when you'd prefer one.",
    "Functionally, a CTE (WITH clause) and a subquery both define an intermediate result set the outer query can use, and most engines optimize them similarly. The practical difference is readability and reuse: a CTE gives the intermediate result a name that can be referenced multiple times later in the query and reads top-to-bottom like a sequence of steps, whereas deeply nested subqueries get hard to read once you have more than one or two levels. I'd prefer a CTE for any query with multiple logical steps or when I need to reference the same intermediate result twice, and reach for a simple inline subquery only for something trivial like a single scalar lookup.",
    "This checks that you value query readability and maintainability, since both approaches are often equivalent in execution.",
    "Focus on readability and reuse rather than claiming one is inherently faster.",
  ),
  interview(
    9,
    15,
    "How would you find customers who purchased in January but not in February?",
    "I'd get the distinct customer sets for each month and use set difference logic, most cleanly with EXCEPT (or NOT EXISTS as an alternative): WITH jan AS (SELECT DISTINCT customer_id FROM orders WHERE order_date >= '2026-01-01' AND order_date < '2026-02-01'), feb AS (SELECT DISTINCT customer_id FROM orders WHERE order_date >= '2026-02-01' AND order_date < '2026-03-01') SELECT customer_id FROM jan EXCEPT SELECT customer_id FROM feb. If the database doesn't support EXCEPT, I'd use a LEFT JOIN from jan to feb and filter WHERE feb.customer_id IS NULL, or a NOT EXISTS correlated subquery, which are logically equivalent.",
    "This tests whether you can translate a business question into set-difference logic and know multiple equivalent ways to express it (EXCEPT, LEFT JOIN + IS NULL, NOT EXISTS).",
    "Think of it as: (set of January customers) minus (set of February customers).",
  ),
  interview(
    10,
    15,
    "How do you optimize a slow analytical query on a large table?",
    "I'd start by looking at the query plan (EXPLAIN/EXPLAIN ANALYZE) to see where time is actually going, rather than guessing. Common fixes: filter as early as possible (push WHERE conditions before joins, avoid filtering after a huge join), select only the columns you need instead of SELECT *, make sure filtered/joined columns have appropriate indexes, and aggregate data down to the needed grain before joining onto larger detail tables to avoid fan-out. For genuinely huge tables, I'd also consider partitioning by date, using a pre-aggregated summary table, or materializing an intermediate result if the same expensive computation is reused often.",
    "The interviewer wants a practical, prioritized checklist grounded in actually reading the query plan, not just a list of buzzwords.",
    "Lead with 'look at the execution plan first', then name concrete fixes like early filtering, indexes, and avoiding SELECT *.",
  ),
  interview(
    11,
    15,
    "Explain how you'd handle NULLs when computing an average so they don't skew results incorrectly.",
    "AVG() in SQL already ignores NULLs by default — it divides by the count of non-NULL values, not the total row count — so a column with some NULLs won't be dragged toward zero the way a naive SUM/total-row-count calculation would. The danger is the opposite mistake: if I want NULL to actually mean zero (e.g. a customer who didn't purchase should count as $0, not be excluded), I need to explicitly COALESCE(amount, 0) before averaging, otherwise those customers get silently dropped from the denominator and inflate the average. So the key is being deliberate about whether NULL means 'missing/exclude' or 'should be treated as zero' for the specific business question.",
    "This tests whether you know AVG()'s default NULL-handling behavior and can reason about which behavior is actually correct for the business question at hand.",
    "Remember AVG() already excludes NULLs from both the sum and the count — the risk is when NULL should really mean zero.",
  ),
  interview(
    12,
    15,
    "How would you pivot rows into columns in SQL?",
    "The portable way that works across most databases is conditional aggregation: SELECT customer_id, SUM(CASE WHEN product = 'A' THEN amount ELSE 0 END) AS product_a, SUM(CASE WHEN product = 'B' THEN amount ELSE 0 END) AS product_b FROM sales GROUP BY customer_id. This turns distinct values in a 'product' column into their own output columns. Some databases (like SQL Server or Snowflake) also offer a native PIVOT operator that does the same thing with dedicated syntax, but I'd default to CASE WHEN + aggregate since it works everywhere and is easy for teammates to read and extend.",
    "The interviewer is checking that you know the CASE WHEN + aggregate pattern as the universal fallback, even if you also know a database-specific PIVOT syntax.",
    "Turn each target column value into its own CASE WHEN inside an aggregate function.",
  ),
  interview(
    13,
    15,
    "Walk through writing a query to compute retention/cohort analysis.",
    "First I'd assign each user to a cohort based on their first activity month: WITH cohort AS (SELECT user_id, DATE_TRUNC('month', MIN(activity_date)) AS cohort_month FROM activity GROUP BY user_id). Then I'd join that back to the full activity table and compute, for each user-month of activity, how many months have elapsed since their cohort month: SELECT c.cohort_month, DATE_DIFF('month', c.cohort_month, DATE_TRUNC('month', a.activity_date)) AS month_number, COUNT(DISTINCT a.user_id) AS active_users FROM cohort c JOIN activity a ON a.user_id = c.user_id GROUP BY 1, 2. Finally I'd pivot or chart month_number against cohort_month to see what fraction of each cohort is still active N months later, usually dividing by the original cohort size to get a retention percentage.",
    "This tests whether you can decompose a fuzzy business concept (retention) into concrete SQL steps: defining a cohort, calculating elapsed time, and aggregating active users per period.",
    "Break it into three steps: define the cohort (first activity date), measure months-since-cohort for later activity, then count distinct active users per (cohort, month_number).",
  ),
  interview(
    14,
    15,
    "Explain the difference between UNION and UNION ALL and a case where using the wrong one causes a bug.",
    "UNION combines two result sets and removes duplicate rows, which requires an extra dedup/sort step, while UNION ALL simply concatenates all rows from both queries, including duplicates. A real bug: if you're combining online_orders and in_store_orders to get a total order count, and you mistakenly use UNION instead of UNION ALL, any two orders that happen to have identical values across all selected columns (e.g. same customer_id, same amount, same date) get silently collapsed into one row, undercounting real, distinct transactions. The safe default for combining transactional/event data where duplicates are expected and meaningful is UNION ALL; UNION should only be used when you specifically want deduplication.",
    "This tests that you understand UNION's implicit dedup can silently drop legitimate rows that happen to look identical, not just that the two keywords 'do something similar'.",
    "Think about a case with legitimately identical-looking rows (same values, different real-world events) getting collapsed.",
  ),
  interview(
    15,
    15,
    "How would you explain a complex multi-CTE query to a non-technical stakeholder reviewing your work?",
    "I'd avoid walking through the SQL syntax line by line and instead describe it as a sequence of business steps, the same way I built the CTEs: 'First I pulled every order in the last 12 months. Then I grouped those into one row per customer to get their total spend. Then I split customers into spend tiers. Finally I counted how many customers fall into each tier.' I'd map each CTE name to a plain-English step and, where useful, show a small sample of the intermediate result (like the customer-level table before tiering) so they can sanity-check the logic themselves rather than trusting the whole query as a black box.",
    "This tests communication skill — can you translate technical query structure into a narrative of business logic that a non-technical reviewer can actually validate.",
    "Map each CTE to one plain-English sentence describing what business step it accomplishes, and offer to show an intermediate result as proof.",
  ),
];

export const SQL_ANALYTICS_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1: Foundations",
      summary:
        "Core SQL query patterns for analytics — execution order, joins, aggregates, window functions, and CTEs used in everyday reporting.",
      topics: ["Fundamentals"],
      steps: round1Steps,
    },
    {
      number: 2,
      title: "Round 2: Interview Prep",
      summary:
        "Open-ended, real interview-style questions about analytical query patterns, debugging joins, and communicating SQL logic to stakeholders.",
      topics: ["SQL for Analytics Interview Prep"],
      steps: round2Steps,
    },
  ],
};
