import {type Course, makeInterviewBuilder, makeMcqBuilder} from "./course-types";

// Round 1: Core statistics and probability every data science candidate is
// expected to know cold — descriptive stats, distributions, the central
// limit theorem, hypothesis testing, confidence intervals, and the
// correlation/causation and Bayes' theorem ideas that come up constantly
// in day-to-day analysis.
const mcq = makeMcqBuilder("Statistics Fundamentals");

const round1Steps = [
  mcq(
    1,
    20,
    "A dataset is 2, 4, 4, 4, 5, 5, 7, 9. What is the mode?",
    ["2", "4", "5", "7"],
    1,
    "4 appears three times, more often than any other value, so it is the mode.",
    "Look for the value that repeats the most, not the middle value.",
  ),
  mcq(
    2,
    20,
    "Why is the median often preferred over the mean for describing income data?",
    [
      "The median is always larger than the mean",
      "The median is resistant to extreme outliers like a few very high incomes",
      "The mean cannot be computed for income data",
      "The median uses every data point while the mean does not",
    ],
    1,
    "Income distributions are right-skewed with a few very high earners; those extreme values pull the mean upward, while the median (the middle value) is unaffected by their exact magnitude.",
    "Think about what happens to each measure when you add one billionaire to the dataset.",
  ),
  mcq(
    3,
    20,
    "What does the variance of a dataset measure?",
    [
      "The average distance between consecutive data points",
      "The average of the squared deviations from the mean",
      "The difference between the maximum and minimum values",
      "The most frequently occurring value",
    ],
    1,
    "Variance is defined as the average of the squared differences between each data point and the mean, capturing how spread out the values are.",
    "It's built from squaring deviations from the mean, not just ranking or ranges.",
  ),
  mcq(
    4,
    20,
    "Why do we typically divide by (n-1) instead of n when computing sample variance?",
    [
      "It makes the formula easier to compute by hand",
      "It corrects for the bias introduced by estimating the mean from the same sample (Bessel's correction)",
      "It is only a convention with no mathematical justification",
      "It ensures variance is always a whole number",
    ],
    1,
    "Using the sample mean to estimate deviations slightly understates true variability, so dividing by (n-1) instead of n (Bessel's correction) produces an unbiased estimator of the population variance.",
    "The sample mean itself was estimated from the data, which costs one 'degree of freedom'.",
  ),
  mcq(
    5,
    20,
    "In a standard normal distribution, approximately what percentage of values fall within one standard deviation of the mean?",
    ["50%", "68%", "95%", "99.7%"],
    1,
    "The empirical rule states that about 68% of values in a normal distribution lie within one standard deviation of the mean, 95% within two, and 99.7% within three.",
    "This is the first number in the classic 68-95-99.7 empirical rule.",
  ),
  mcq(
    6,
    20,
    "Which probability distribution is most appropriate for modeling the number of successes in a fixed number of independent yes/no trials, each with the same success probability?",
    ["Normal distribution", "Poisson distribution", "Binomial distribution", "Uniform distribution"],
    2,
    "The binomial distribution models the count of successes across n independent Bernoulli trials with a fixed probability p per trial, such as the number of heads in 10 coin flips.",
    "Think coin flips: a fixed number of independent trials, each with the same success chance.",
  ),
  mcq(
    7,
    20,
    "A call center receives an average of 5 calls per minute, and calls arrive independently of each other. Which distribution best models the number of calls in a given minute?",
    ["Binomial distribution", "Poisson distribution", "Normal distribution", "Exponential distribution"],
    1,
    "The Poisson distribution models the count of independent events occurring in a fixed interval of time given a known constant average rate, exactly the call-arrival scenario described.",
    "This is a rate of events per fixed time interval, not a fixed number of trials.",
  ),
  mcq(
    8,
    20,
    "What does the Central Limit Theorem state?",
    [
      "Every dataset eventually becomes normally distributed if you collect enough data",
      "The sampling distribution of the sample mean approaches a normal distribution as sample size grows, regardless of the population's original distribution",
      "Larger samples always have smaller variance than the population",
      "The mean of a sample always equals the mean of the population",
    ],
    1,
    "The CLT says that regardless of the shape of the underlying population distribution, the distribution of sample means approaches a normal distribution as the sample size increases, which is why normal-based inference works so broadly.",
    "It's a statement about the distribution of sample means across repeated samples, not about the raw data itself.",
  ),
  mcq(
    9,
    20,
    "In hypothesis testing, what does the null hypothesis (H0) typically represent?",
    [
      "The effect or difference the researcher hopes to prove exists",
      "A default position of no effect or no difference, which is tested against the alternative",
      "Whatever hypothesis has the smallest p-value",
      "The hypothesis that is always assumed to be true after the test",
    ],
    1,
    "The null hypothesis is the default assumption of no effect, no difference, or no relationship; the test asks whether the data provide enough evidence to reject it in favor of the alternative hypothesis.",
    "It's the 'status quo' or 'nothing is happening' statement that the test tries to find evidence against.",
  ),
  mcq(
    10,
    20,
    "What does a p-value of 0.03 mean in a hypothesis test?",
    [
      "There is a 3% probability that the null hypothesis is true",
      "There is a 97% probability that the alternative hypothesis is true",
      "Assuming the null hypothesis is true, there is a 3% probability of observing data at least as extreme as what was actually observed",
      "The effect size is 0.03",
    ],
    2,
    "A p-value is the probability, computed under the assumption that the null hypothesis is true, of observing a result at least as extreme as the one obtained; it is not the probability that the null (or alternative) hypothesis itself is true.",
    "The p-value is a statement about the data given the null hypothesis, not a statement about the probability of the hypothesis itself.",
  ),
  mcq(
    11,
    20,
    "A study uses a significance level (alpha) of 0.05. What does this represent?",
    [
      "The probability of failing to detect a real effect",
      "The maximum acceptable probability of rejecting a true null hypothesis (a Type I error)",
      "The minimum sample size needed for the study",
      "The probability that the results will replicate",
    ],
    1,
    "Alpha is the threshold the researcher sets in advance for the probability of a Type I error — incorrectly rejecting a null hypothesis that is actually true.",
    "It's the researcher's pre-chosen tolerance for a 'false positive' result.",
  ),
  mcq(
    12,
    20,
    "A pregnancy test comes back positive for a woman who is not actually pregnant. In hypothesis testing terms, this is an example of:",
    ["A Type I error", "A Type II error", "A confidence interval failure", "A sampling bias"],
    0,
    "If the null hypothesis is 'not pregnant', a positive test on a non-pregnant woman incorrectly rejects a true null hypothesis, which is exactly a Type I error (a false positive).",
    "The null hypothesis here is 'no pregnancy'; this result wrongly rejects that true null.",
  ),
  mcq(
    13,
    20,
    "What does a 95% confidence interval for a population mean actually mean?",
    [
      "There is a 95% probability that the true population mean falls within this specific interval",
      "95% of the data falls within this interval",
      "If we repeated the sampling process many times and built an interval each time, about 95% of those intervals would contain the true population mean",
      "The sample mean is correct 95% of the time",
    ],
    2,
    "A confidence interval's 'confidence' refers to the long-run behavior of the procedure across repeated samples, not the probability that any single computed interval contains the fixed, unknown true parameter.",
    "The randomness is in the interval-generating procedure across repeated samples, not in the fixed true parameter.",
  ),
  mcq(
    14,
    20,
    "Two variables, ice cream sales and drowning incidents, are strongly positively correlated. What does this most likely indicate?",
    [
      "Ice cream sales cause drowning incidents",
      "Drowning incidents cause higher ice cream sales",
      "A confounding variable, such as hot weather, likely drives both",
      "The correlation must be a calculation error",
    ],
    2,
    "This is a classic example of confounding: hot weather increases both ice cream sales and swimming (and thus drowning risk), creating a correlation between the two variables with no direct causal link between them.",
    "Ask what third factor could plausibly be driving both variables up at the same time.",
  ),
  mcq(
    15,
    20,
    "What does covariance between two variables indicate?",
    [
      "The exact strength of the linear relationship on a scale from -1 to 1",
      "The direction of the linear relationship between two variables, but not a standardized measure of its strength",
      "The average of the two variables",
      "Whether one variable causes the other",
    ],
    1,
    "Covariance indicates whether two variables tend to move together (positive) or in opposite directions (negative), but its magnitude depends on the units of the variables, so it is not standardized like correlation.",
    "Covariance and correlation both describe direction, but only one of them is scaled to a fixed range.",
  ),
  mcq(
    16,
    20,
    "A student scores 82 on a test with a class mean of 70 and standard deviation of 8. What is the student's z-score?",
    ["1.0", "1.5", "8.0", "12.0"],
    1,
    "z = (x - mean) / standard deviation = (82 - 70) / 8 = 12 / 8 = 1.5, meaning the score is 1.5 standard deviations above the mean.",
    "Subtract the mean from the score, then divide by the standard deviation.",
  ),
  mcq(
    17,
    20,
    "A researcher wants every member of a population to have an equal chance of being selected, using a random number generator to pick participants from a complete list. This is an example of:",
    ["Stratified sampling", "Convenience sampling", "Simple random sampling", "Cluster sampling"],
    2,
    "Simple random sampling gives every member of the population an equal and independent chance of selection, typically implemented by randomly drawing from a complete list (sampling frame).",
    "This is the most basic sampling method — no groups, no strata, just equal chance for everyone.",
  ),
  mcq(
    18,
    20,
    "A distribution has a long tail extending to the right, with most values clustered on the lower end. This distribution is described as:",
    ["Negatively skewed", "Positively skewed", "Symmetric", "Platykurtic"],
    1,
    "A distribution with a longer tail on the right side (higher values) is positively skewed; the mean is typically pulled higher than the median in this case.",
    "The skew is named after the direction the long tail points, not where most of the data sits.",
  ),
  mcq(
    19,
    20,
    "What does high positive kurtosis (leptokurtic distribution) indicate compared to a normal distribution?",
    [
      "The distribution is perfectly symmetric with no outliers",
      "The distribution has heavier tails and a sharper peak, meaning more extreme outliers",
      "The distribution has no variance",
      "The distribution is uniform across all values",
    ],
    1,
    "Leptokurtic distributions have a sharper central peak and heavier tails than a normal distribution, indicating a higher likelihood of extreme values (outliers) than the normal distribution would predict.",
    "Think 'lepto' as in thin/tall peak, with more probability mass out in the tails.",
  ),
  mcq(
    20,
    20,
    "1% of a population has a disease. A test is 99% accurate (correctly identifies both positives and negatives). If a random person tests positive, using Bayes' theorem, why is the true probability they have the disease much lower than 99%?",
    [
      "Because the test accuracy quoted is fake",
      "Because false positives from the large healthy population outnumber true positives from the small diseased population",
      "Because Bayes' theorem only applies to continuous variables",
      "Because the prior probability is irrelevant once you have test results",
    ],
    1,
    "Bayes' theorem combines the test's accuracy with the low base rate (prior) of the disease: since the healthy population is so much larger, even a 1% false-positive rate on healthy people produces more false positives in absolute terms than true positives from the small diseased group, pulling the posterior probability well below 99%.",
    "Multiply the accuracy by how rare the condition is in the first place — the base rate matters as much as the test's accuracy.",
  ),
];

// Round 2: open-ended interview questions a Data Scientist / Data Analyst
// candidate should be ready to answer out loud, with a model answer to
// reveal and self-check against.
const interview = makeInterviewBuilder("statistics-interview", "Statistics Interview Prep");

const round2Steps = [
  interview(
    1,
    15,
    "How would you explain what a p-value is to a non-technical stakeholder who keeps saying '0.03 means there's a 3% chance we're wrong'?",
    "I'd say a p-value isn't the probability that our result is wrong or that the null hypothesis is true — it's the probability of seeing data this extreme (or more extreme) if there were actually no real effect at all. So a p-value of 0.03 means: 'if nothing were really going on, we'd only see a result this strong 3% of the time by chance.' That's evidence against 'nothing is going on,' but it's not a direct statement about how likely our conclusion is to be correct. I'd also remind them that statistical significance isn't the same as practical importance — a tiny, meaningless effect can still have a small p-value with enough data.",
    "The interviewer is checking whether you actually understand the definition of a p-value versus the extremely common misinterpretation, and whether you can communicate it without dumbing it down incorrectly.",
    "Contrast 'probability of the data given the null' with the wrong but common 'probability the null is true'.",
  ),
  interview(
    2,
    15,
    "How do you decide on a sample size for an A/B test before launching it?",
    "I'd start with a power analysis: I need the baseline conversion rate, the minimum detectable effect size that would actually matter to the business, a significance level (usually 0.05), and a desired power (usually 0.8). Those four inputs feed into a sample size formula (or a calculator) that tells you how many users per variant you need. I'd also factor in practical constraints like weekly traffic volume to estimate how long the test needs to run, and I'd make sure we're not peeking at results early and stopping as soon as it looks significant, since that inflates the false positive rate.",
    "The interviewer wants to see that you know sample size isn't arbitrary — it comes from a formal power analysis tied to a real minimum effect size, not just 'run it for two weeks.'",
    "Mention the four power-analysis inputs: baseline rate, minimum detectable effect, alpha, and power.",
  ),
  interview(
    3,
    15,
    "What's the difference between Type I and Type II error, and which one matters more when screening patients for a serious but treatable disease?",
    "A Type I error is a false positive — rejecting a true null hypothesis, e.g. telling a healthy patient they have the disease. A Type II error is a false negative — failing to reject a false null, e.g. telling a sick patient they're healthy. In a disease screening context, a Type II error is usually far more costly: missing a real case means a treatable illness goes untreated and can progress or spread, whereas a false positive typically just leads to a follow-up confirmatory test. So for screening tools we'd often tolerate a higher false-positive rate in exchange for very high sensitivity (low false-negative rate).",
    "The interviewer wants you to connect the abstract Type I/II definitions to a concrete cost trade-off, showing you can reason about which error is worse in context rather than reciting definitions.",
    "Define both errors first, then argue for asymmetric costs in this specific medical scenario.",
  ),
  interview(
    4,
    15,
    "Explain the Central Limit Theorem in your own words and why it matters in practice.",
    "The Central Limit Theorem says that if you repeatedly take random samples of a reasonably large size from any population — regardless of that population's original shape — and compute the mean of each sample, the distribution of those sample means will approach a normal distribution as the sample size grows. It matters because it justifies using normal-distribution-based methods, like z-tests, t-tests, and confidence intervals, on sample means even when the underlying data is skewed or non-normal, as long as the sample size is large enough (commonly n ≥ 30 as a rule of thumb, though it depends on how non-normal the population is).",
    "This tests whether you understand the CLT is about the sampling distribution of the mean, not a claim that raw data becomes normal — a very common confusion.",
    "Be explicit that it's the distribution of sample means, not the raw data, that becomes normal.",
  ),
  interview(
    5,
    15,
    "When would you use a t-test instead of a z-test?",
    "I'd use a z-test when the population standard deviation is known and/or the sample size is large (generally n > 30), since the sampling distribution of the mean is well-approximated by a normal distribution in that case. I'd use a t-test when the population standard deviation is unknown and has to be estimated from the sample, especially with a smaller sample size — the t-distribution has heavier tails than the normal distribution to account for that extra uncertainty, and it converges to the normal distribution as sample size grows. In practice, with real-world data we almost never know the true population standard deviation, so t-tests are the more common default.",
    "The interviewer is checking whether you know the actual distinguishing factor (known vs. estimated standard deviation) rather than just 'small sample = t-test' as a rote rule.",
    "The real criterion is whether the population standard deviation is known, not just sample size alone.",
  ),
  interview(
    6,
    15,
    "How do you detect and handle outliers in a dataset?",
    "For detection, I'd start with visualizations like box plots and histograms, then use quantitative rules such as values beyond 1.5x the IQR from the quartiles, or beyond 3 standard deviations from the mean for roughly normal data, or model-based methods like isolation forests for higher-dimensional data. For handling, the right approach depends on cause: if it's a data entry error, I'd correct or remove it; if it's a legitimate extreme value (like a genuinely huge transaction), I might keep it, cap it (winsorize), transform the variable (e.g. log transform), or use a model that's robust to outliers, such as a tree-based model or robust regression, rather than blindly deleting real data.",
    "The interviewer wants to see that you distinguish between detecting statistical outliers and deciding whether they're errors versus real signal, since blindly removing them can bias results.",
    "Separate the detection method from the handling decision, and stress that not all outliers should be deleted.",
  ),
  interview(
    7,
    15,
    "What is a confounding variable, and can you give an example from a business or health context?",
    "A confounding variable is an unmeasured or unaccounted-for factor that influences both the independent and dependent variable, creating an association between them that isn't causal. A classic example: a company observes that employees who use a wellness app have fewer sick days, and concludes the app reduces sick days. But a confounder like 'general health consciousness' could drive both app usage and fewer sick days independently, without the app itself doing anything — people who are already health-conscious are more likely to both use the app and take fewer sick days. The fix is to control for the confounder statistically (regression adjustment, stratification) or, ideally, run a randomized experiment where the confounder is balanced across groups.",
    "The interviewer is testing whether you can identify confounding in a realistic scenario, not just define it, and whether you know randomization is the gold-standard fix.",
    "Give a concrete example where a third variable plausibly drives both the 'cause' and the 'effect'.",
  ),
  interview(
    8,
    15,
    "How would you explain a confidence interval to someone with no statistics background?",
    "I'd say: imagine we ran this same study many times, each time on a fresh random sample, and each time built an interval the same way. A 95% confidence interval means that about 95% of the intervals built this way would contain the true underlying value we're trying to measure. So our specific interval is our best estimate of a plausible range for the true answer, given the uncertainty from only having one sample rather than the whole population — but it's not correct to say 'there's a 95% chance the true value is in this exact range,' since the true value is fixed and it's the procedure that has the 95% success rate.",
    "The interviewer wants to see you can convey the repeated-sampling interpretation in plain language without falling into the common but technically wrong 'probability the true value is in this interval' phrasing.",
    "Use the repeated-experiments framing rather than describing probability about the fixed true parameter.",
  ),
  interview(
    9,
    15,
    "What is Simpson's paradox, and why should analysts be careful about aggregated data?",
    "Simpson's paradox occurs when a trend appears in several different groups of data but disappears or reverses when those groups are combined. A classic example is comparing two hospitals' treatment success rates overall, where Hospital A looks worse than Hospital B in aggregate, but when you break the data down by patient severity (mild vs. severe cases), Hospital A actually outperforms Hospital B in both subgroups — it just treats a much higher proportion of severe cases, which drags down its overall average. The lesson is that aggregated statistics can hide or even reverse the true relationship, so analysts should check whether a lurking variable (like case severity here) is unevenly distributed across the groups being compared before trusting an aggregate comparison.",
    "The interviewer is checking whether you understand that this isn't just a curiosity — it's a real risk whenever you compare aggregated rates across groups with different underlying compositions.",
    "Use a concrete example where subgroup trends reverse once you aggregate them.",
  ),
  interview(
    10,
    15,
    "When is the median a better summary statistic than the mean?",
    "The median is preferable when the data is skewed or contains extreme outliers that would distort the mean, such as income, home prices, or wait times, where a small number of very large values can pull the mean far from what's 'typical.' The median, being the middle value, is robust to those extremes and better represents a typical observation. The mean is generally better when the distribution is roughly symmetric and you want a statistic that uses all the information in the data (for example, for further computations like variance) or when you specifically care about totals, since sums relate directly to the mean but not to the median.",
    "The interviewer wants a clear articulation of robustness to skew/outliers as the deciding factor, ideally with a real-world example.",
    "Skew and outliers are the key trigger for preferring the median.",
  ),
  interview(
    11,
    15,
    "How would you design an A/B test for a new checkout flow on an e-commerce site, and what could go wrong?",
    "I'd define a single clear primary metric (e.g. conversion rate to completed purchase), calculate the required sample size via a power analysis based on baseline conversion, minimum detectable effect, alpha, and power, then randomly assign users to control and treatment in a way that avoids contamination (e.g. bucket by user ID, not session, so a user doesn't see both variants). I'd run it for at least one full business cycle (typically 1-2 weeks) to capture weekday/weekend variation, and pre-register the analysis plan to avoid p-hacking. Things that could go wrong: novelty effects biasing early results, peeking at results early and stopping as soon as it's significant, sample ratio mismatch from a broken randomization, seasonal effects, and interference between users if the checkout flow has network effects (rare here, but relevant in some products).",
    "The interviewer wants an end-to-end grasp of experimental design, not just the statistics — sample size, randomization unit, test duration, and awareness of common pitfalls like peeking and novelty effects.",
    "Cover the full pipeline: metric, sample size, randomization unit, duration, and at least two concrete failure modes.",
  ),
  interview(
    12,
    15,
    "What is regression to the mean, and can you give an example of how it might mislead someone analyzing performance data?",
    "Regression to the mean is the statistical tendency for an extreme measurement to be followed by one closer to the average, simply because some of the extremeness was due to random chance/noise rather than a true underlying shift. A classic example: a sales rep has an unusually great month, gets extra coaching, and then has a more average month — management might credit the coaching, but some or all of the reversion would have happened anyway just because that great month was partly luck. Analysts need to be careful not to attribute regression-to-the-mean effects to an intervention (coaching, a new policy, etc.) without a proper control group, since it can create the illusion that an intervention caused improvement when it was actually just natural reversion.",
    "The interviewer is testing whether you can connect this concept to a real business scenario where it commonly creates false causal narratives, particularly around interventions following extreme performance.",
    "Tie it to a scenario where an intervention gets credited for what was really just reversion after an extreme, partly-lucky result.",
  ),
  interview(
    13,
    15,
    "What is the multiple comparisons problem, and how does it relate to p-hacking?",
    "When you run many statistical tests at once (say, testing 20 different metrics for a single experiment), the probability that at least one test comes back 'significant' purely by chance rises well above your nominal alpha level (e.g. 5%) — with 20 independent tests at alpha=0.05, you'd expect about one false positive just by chance. P-hacking is the practice, often unintentional, of running many tests, slicing data many ways, or repeatedly checking results until something crosses the significance threshold, then reporting only that result as if it were the single planned test. The fix is to pre-register the primary hypothesis before collecting data, and when multiple comparisons are genuinely needed, apply a correction like Bonferroni or the Benjamini-Hochberg false discovery rate procedure to control the overall error rate.",
    "The interviewer wants to see you understand why testing lots of things inflates false positives and know at least one concrete correction method, since this is a common source of unreliable findings in real analysis.",
    "Explain why more tests mechanically increase the chance of a false positive, then name a correction method.",
  ),
  interview(
    14,
    15,
    "Give a concrete example of 'correlation does not imply causation' and explain how you'd actually test for causation.",
    "A classic example: cities with more firefighters tend to have more fire damage per incident. It's tempting to think firefighters cause damage, but the real driver is fire severity — bigger fires prompt more firefighters to respond and also cause more damage; the firefighter count and the damage are both downstream effects of fire size, not causally linked to each other directly. To actually test for causation, the gold standard is a randomized controlled experiment, where you randomly assign the 'treatment' (removing confounding by construction) and measure the outcome. When randomization isn't feasible, quasi-experimental methods like difference-in-differences, instrumental variables, regression discontinuity, or propensity score matching can help approximate causal estimates from observational data by controlling for confounders.",
    "The interviewer wants a genuinely distinct example (not the tired ice-cream/drowning one) plus a real answer on causal inference methods, showing depth beyond the cliché phrase.",
    "Pick an example where a third variable drives both measured quantities, then name at least one causal inference method beyond 'just run an RCT'.",
  ),
  interview(
    15,
    15,
    "How do you choose between a parametric and a non-parametric statistical test?",
    "I'd start by checking the assumptions a parametric test requires — typically normality of the data (or of the residuals/sampling distribution), homogeneity of variance across groups, and a reasonably large sample size. If those assumptions hold reasonably well, I'd prefer a parametric test (t-test, ANOVA, Pearson correlation) since they're generally more statistically powerful when their assumptions are met. If the data is heavily skewed, has significant outliers, is ordinal rather than continuous, or the sample size is too small to check normality reliably, I'd switch to the non-parametric equivalent (Mann-Whitney U instead of a t-test, Kruskal-Wallis instead of ANOVA, Spearman instead of Pearson correlation), which makes fewer distributional assumptions at some cost in power.",
    "The interviewer wants to see that you know the assumption-checking process drives the choice, and that you can name the actual parametric/non-parametric test pairs rather than speaking only in the abstract.",
    "Name the assumptions to check first, then give at least one matched parametric/non-parametric test pair.",
  ),
];

export const STATISTICS_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1: Foundations",
      summary:
        "Descriptive statistics, probability distributions, the central limit theorem, hypothesis testing, and confidence intervals used in everyday data analysis.",
      topics: ["Fundamentals"],
      steps: round1Steps,
    },
    {
      number: 2,
      title: "Round 2: Interview Prep",
      summary:
        "Open-ended, real interview-style questions about experimental design, statistical reasoning, and communicating statistics to non-technical stakeholders.",
      topics: ["Statistics Interview Prep"],
      steps: round2Steps,
    },
  ],
};
