import {type Course, makeInterviewBuilder, makeMcqBuilder} from "./course-types";

// Round 1: Tableau fundamentals every BI / data-visualization candidate is
// expected to know cold — dimensions vs measures, the shelves and marks card,
// calculated fields and table calculations, LOD expressions, filters/sets/
// groups, joins vs blends, dual-axis charts, extracts, and publishing.
const mcq = makeMcqBuilder("Tableau Fundamentals");

const round1Steps = [
  mcq(
    1,
    20,
    "By default, how does Tableau decide whether a field becomes a dimension or a measure?",
    [
      "Alphabetical order of the field name",
      "Qualitative/categorical fields become dimensions; quantitative/numeric fields become measures",
      "It is chosen at random and must always be fixed manually",
      "Fields from Excel are always dimensions, fields from SQL are always measures",
    ],
    1,
    "Tableau's default heuristic is that discrete, categorical data (names, categories, dates) becomes a dimension, while continuous, numeric, aggregatable data becomes a measure — though either can be manually converted.",
    "Think about which kind of field you'd naturally want to sum or average versus which you'd use to slice/group data.",
  ),
  mcq(
    2,
    20,
    "In Tableau, what do the colors blue and green on a pill (field) on the shelves actually represent?",
    [
      "Blue = dimension, green = measure, regardless of anything else",
      "Blue = discrete, green = continuous — independent of whether the field is a dimension or measure",
      "Blue = string data, green = numeric data only",
      "Blue = calculated field, green = original field",
    ],
    1,
    "Pill color encodes discrete vs. continuous, not dimension vs. measure — a measure can be made discrete (blue) and a dimension like a date can be made continuous (green), which changes how it renders on the axis.",
    "Remember that a date field can be dragged onto a shelf as either color depending on how you want it to behave.",
  ),
  mcq(
    3,
    20,
    "What is the fundamental difference between the Rows/Columns shelves and the Marks card?",
    [
      "Rows/Columns build the table structure (axes and headers); the Marks card controls how each mark is drawn (color, size, label, detail, tooltip)",
      "They are two names for the same thing",
      "Rows/Columns only accept measures; Marks card only accepts dimensions",
      "The Marks card only affects the title of the worksheet",
    ],
    0,
    "Rows and Columns define the grid/axes of the visualization, while the Marks card controls the visual encoding of each mark — its color, size, shape, label, level of detail, and tooltip content.",
    "One shelf pair lays out the 'grid,' the other pair styles what gets drawn inside it.",
  ),
  mcq(
    4,
    20,
    "Dragging a dimension onto the 'Detail' property of the Marks card does what?",
    [
      "Nothing — Detail only accepts measures",
      "Increases the granularity of the view without adding a visual encoding like color or size",
      "Automatically colors each mark a different color",
      "Removes the field from the underlying data",
    ],
    1,
    "Adding a dimension to Detail breaks the marks into more granular groups (one mark per combination of values) without changing how the marks look visually, unlike Color or Size.",
    "It affects how finely data is split, not how it's displayed.",
  ),
  mcq(
    5,
    20,
    "What is a calculated field in Tableau?",
    [
      "A field imported directly from the data source with no modification",
      "A new field defined by a formula (using existing fields, functions, and operators) that becomes available like any other field",
      "A filter applied to an existing measure",
      "A field that can only be used in the title of a dashboard",
    ],
    1,
    "A calculated field lets you create new dimensions or measures using formulas (e.g. IF/CASE logic, string functions, arithmetic) built from existing fields, and it then behaves like any other pill in the workbook.",
    "Think 'new column derived by a formula,' not a raw source column.",
  ),
  mcq(
    6,
    20,
    "Which of these is a table calculation (computed on the data already in the view, not the underlying data source)?",
    ["SUM(Sales)", "Running Total of SUM(Sales)", "AVG(Profit)", "COUNTD(Customer ID)"],
    1,
    "Table calculations like running total, percent of total, and rank are computed on the aggregated result set that's already rendered in the view, based on the order/partitioning of the visible marks — unlike a plain aggregation which is computed by the data engine.",
    "The others are simple aggregations of raw rows; one of these depends on the layout/order of the other rows already in the view.",
  ),
  mcq(
    7,
    20,
    "You want to show each region's sales as a percentage of the grand total across all regions in the view. Which feature is designed exactly for this?",
    [
      "A context filter",
      "A table calculation using 'Percent of Total'",
      "A data blend",
      "A dual axis",
    ],
    1,
    "'Percent of Total' is a built-in quick table calculation that divides each mark's value by the total across a chosen scope (table, pane, or partition), which is exactly the running-total/rank/percent-of-total family of table calculations.",
    "This is one of Tableau's 'quick table calculations' available directly from a measure's right-click menu.",
  ),
  mcq(
    8,
    20,
    "Why do LOD (Level of Detail) expressions like FIXED exist, given that you can already control granularity with dimensions on the view?",
    [
      "They let you compute an aggregation at a granularity different from the granularity of the current visualization, independent of what's on the Rows/Columns/Marks shelves",
      "They are purely cosmetic and only change font size",
      "They replace the need for any dimensions in the view",
      "They can only be used in Tableau Prep, not Tableau Desktop",
    ],
    0,
    "LOD expressions (FIXED, INCLUDE, EXCLUDE) let you compute a value at a level of detail that's coarser or finer than the view itself — e.g. each customer's first purchase date, or total sales per region, shown alongside row-level detail — something normal view-level aggregation can't do.",
    "The key phrase is 'a different level of detail than the view,' regardless of what dimensions are dragged onto shelves.",
  ),
  mcq(
    9,
    20,
    "You need to compute total sales per customer, but display it on a view broken out by order date. Which LOD expression fits best?",
    [
      "{FIXED [Customer]: SUM([Sales])}",
      "{INCLUDE [Order Date]: SUM([Sales])}",
      "A context filter on Customer",
      "A quick table calculation of 'Rank'",
    ],
    0,
    "{FIXED [Customer]: SUM([Sales])} computes sales aggregated strictly at the customer level, ignoring other dimensions in the view (like Order Date), so every row for a given customer shows that customer's fixed total.",
    "You want the calculation to ignore the date dimension entirely and 'fix' on customer only.",
  ),
  mcq(
    10,
    20,
    "What is the key difference between EXCLUDE and FIXED level-of-detail expressions?",
    [
      "EXCLUDE has no relationship to the view's dimensions; FIXED always ignores filters",
      "EXCLUDE removes one or more specific dimensions from the view's existing granularity, while FIXED specifies its own independent granularity regardless of what's in the view",
      "They are exact synonyms",
      "EXCLUDE only works with dates",
    ],
    1,
    "EXCLUDE is relative to the view — it takes the view's current dimensions and removes the ones you specify, while FIXED declares its own granularity entirely independent of whatever dimensions happen to be in the view.",
    "One reacts relative to the current view, the other ignores the view completely.",
  ),
  mcq(
    11,
    20,
    "What is the difference between a Tableau filter and a Tableau set?",
    [
      "A filter permanently deletes data from the source; a set never affects the view",
      "A filter removes rows from the view based on a condition; a set is a custom, reusable subset of dimension members that can be used as a field (e.g. colored, filtered, or combined with other sets)",
      "They are identical features with different names",
      "Sets only work with measures, filters only work with dimensions",
    ],
    1,
    "A filter simply restricts what's shown in the view, while a set is a named, reusable group of members (static or dynamic) that becomes its own field you can use for coloring, combining with other sets (IN/OUT), or filtering elsewhere.",
    "One is a one-off view restriction; the other becomes a reusable field you can drop on shelves.",
  ),
  mcq(
    12,
    20,
    "What is a group in Tableau, and how does it differ from a set?",
    [
      "A group combines related dimension members into a single higher-level category (e.g. combining several product SKUs into 'Accessories'); a set is a binary in/out membership test rather than a renaming/combining tool",
      "A group and a set are computed identically and are interchangeable",
      "A group can only contain measures",
      "A group is only available in Tableau Server, not Desktop",
    ],
    0,
    "Grouping manually combines several dimension members into a new, higher-level member (useful for cleaning up categories), whereas a set represents membership (in the set / not in the set) and is often driven by a condition or a top-N rule.",
    "One is about relabeling/combining categories; the other is a yes/no membership flag.",
  ),
  mcq(
    13,
    20,
    "When would you use a parameter instead of a filter?",
    [
      "Parameters can only filter dates",
      "When you need a single, user-controlled input value that can drive multiple things at once, like swapping which measure is displayed, a dynamic reference line, or a top-N count — not just restrict rows",
      "Parameters and filters do exactly the same thing in every case",
      "Parameters cannot be exposed as controls on a dashboard",
    ],
    1,
    "A parameter is a standalone, workbook-level input value that a user can control (e.g. via a dropdown or slider); unlike a filter, it isn't tied to a single field, so it can drive a calculated field that swaps measures, adjusts a threshold, or sets a dynamic top-N — while a filter simply restricts which rows appear.",
    "Think about which one can be reused inside a formula to change what's being measured, not just which rows show.",
  ),
  mcq(
    14,
    20,
    "You need to combine sales data from a SQL Server table with a small spreadsheet of regional sales targets. The spreadsheet has a different level of granularity (one row per region) than the SQL data (one row per transaction). What is the most appropriate approach?",
    [
      "Always use a join, since joins are strictly better than blends",
      "A data blend, since it lets you combine sources at different granularities using a linking dimension, aggregating the secondary source at query time",
      "It's impossible to combine these two sources in Tableau",
      "Convert the spreadsheet into a calculated field",
    ],
    1,
    "Blending is designed for exactly this case: combining two data sources of different granularity from different connections, where the secondary source gets aggregated to match the primary source's level of detail on a shared linking field — something a row-level join would mishandle.",
    "The mismatch in granularity between the two sources is the giveaway for which combination technique fits.",
  ),
  mcq(
    15,
    20,
    "What is a key limitation of data blending compared to joining?",
    [
      "Blending supports row-level joins with unlimited granularity matching",
      "Blending can only aggregate the secondary source's measures at the level of the linking dimensions, so you lose access to its row-level detail and some calculations become harder or impossible",
      "Blending is always faster than joining",
      "Blending requires both sources to be the exact same file type",
    ],
    1,
    "Because blending pre-aggregates the secondary source to the granularity of the linking fields before combining, you can't drill into the secondary source's row-level detail, and certain calculations (like some LOD expressions across sources) don't work the way they would with a true join.",
    "Blending trades away row-level access to the secondary source in exchange for combining different granularities.",
  ),
  mcq(
    16,
    20,
    "What does a dual-axis chart let you do that a single-axis combo chart cannot?",
    [
      "Show two measures on independent axes (potentially with different scales and mark types) layered on the same set of dimensions",
      "Display more than two dimensions at once",
      "It is only cosmetic and has no functional difference from a single axis",
      "Automatically synchronize the two axes' scales at all times",
    ],
    0,
    "A dual-axis view puts two measures on two separate, independently scaled axes sharing the same category axis, letting you combine e.g. a bar chart of Sales with a line chart of Profit Ratio at very different scales in one view — synchronization is optional, not automatic.",
    "The key word is 'independent axes' — that's what distinguishes it from a single shared axis.",
  ),
  mcq(
    17,
    20,
    "What is the main practical difference between an extract (.hyper) and a live connection in Tableau?",
    [
      "An extract is a saved, compressed snapshot of the data pulled into Tableau's fast in-memory engine, which improves performance but requires refreshing to see new source data; a live connection queries the source directly and always reflects current data",
      "A live connection is always faster than an extract",
      "Extracts cannot be used with dashboards",
      "There is no difference; the terms are interchangeable",
    ],
    0,
    "Extracts materialize and compress the data into Tableau's optimized .hyper format for faster performance and offline use, but the data is only as current as the last refresh, whereas a live connection sends queries straight to the source so it's always up to date but depends on that source's performance.",
    "One trades freshness for speed; the other trades speed for always-current data.",
  ),
  mcq(
    18,
    20,
    "What is the main difference between a Tableau dashboard and a Tableau story?",
    [
      "A dashboard combines multiple worksheets/objects into one interactive view for exploration; a story is a sequence of dashboard/worksheet 'story points' arranged to guide viewers through a narrative",
      "Stories cannot contain any charts",
      "Dashboards are static images; stories are interactive",
      "They are the exact same object with a different name",
    ],
    0,
    "A dashboard assembles sheets, filters, and objects into a single interactive canvas for open-ended exploration, while a story is a sequenced set of story points (often built from dashboards or sheets) designed to walk an audience through a specific narrative, step by step.",
    "One is built for free exploration; the other is built for a guided, ordered narrative.",
  ),
  mcq(
    19,
    20,
    "A user clicks a bar in one sheet on a dashboard, and a second sheet automatically highlights only the matching category without hiding anything else. Which dashboard action produces this behavior?",
    ["A URL action", "A highlight action", "A filter action", "A parameter action"],
    1,
    "A highlight action visually emphasizes marks that match the selection in related sheets (dimming the rest) without removing any data from the view, unlike a filter action which actually restricts which marks are shown.",
    "The behavior described keeps everything visible but dims non-matching marks — that's the defining trait of one specific action type.",
  ),
  mcq(
    20,
    20,
    "What is the primary purpose of publishing a workbook to Tableau Server or Tableau Cloud instead of just sharing the .twbx file?",
    [
      "It converts the workbook into a PDF automatically",
      "It centralizes governed access, scheduled data refreshes, permissions, and browser-based viewing/interaction without requiring viewers to own Tableau Desktop",
      "It removes the need for any data connections",
      "It is only useful for training purposes and has no production use",
    ],
    1,
    "Publishing to Server/Cloud lets an organization govern access (permissions, projects), schedule automatic extract refreshes, and let stakeholders view and interact with the workbook in a browser without needing a Tableau Desktop license, which a locally shared .twbx file can't provide.",
    "Think about what a whole organization needs beyond one person opening a file locally: governance, refresh schedules, and browser access.",
  ),
];

// Round 2: open-ended interview questions a BI / Data Visualization Analyst
// candidate should be ready to answer out loud, with a model answer to
// reveal and self-check against.
const interview = makeInterviewBuilder("tableau-interview", "Tableau Interview Prep");

const round2Steps = [
  interview(
    1,
    15,
    "Explain the difference between a dimension and a measure in Tableau, and give an example of when a field's default role surprised you or could easily be misclassified.",
    "Dimensions are qualitative fields Tableau uses to slice and categorize data (names, categories, dates), while measures are quantitative fields meant to be aggregated (summed, averaged). A classic surprise is a field like 'Year' or 'Zip Code' or an 'Order ID' being numeric and auto-classified as a measure, when really it should be treated as a dimension since you never want to sum a zip code or an order ID — you have to manually convert it. Another common one is a Customer ID or Postal Code column that looks numeric but is really a categorical label. Recognizing this early avoids nonsensical aggregations like 'sum of zip codes' appearing in a view.",
    "This tests whether the candidate understands that Tableau's default type detection is a heuristic, not ground truth, and that misclassified fields cause real modeling bugs.",
    "Give a concrete example of a numeric-looking ID field that should really be a dimension.",
  ),
  interview(
    2,
    15,
    "Explain LOD expressions and walk through a business scenario where FIXED solves a problem a normal aggregation can't.",
    "LOD (Level of Detail) expressions let you compute an aggregation at a granularity independent of what's currently in the view, using FIXED, INCLUDE, or EXCLUDE. A classic scenario: you want to count how many customers made more than 5 orders, but the view is at the order level. A normal SUM/COUNT would only aggregate at the view's granularity; instead you'd write {FIXED [Customer ID]: COUNT([Order ID])} to get each customer's fixed order count regardless of what other dimensions are in the view, then build a second calculation or filter on top of that to bucket customers into 'more than 5 orders' vs not. Without LOD, you'd need a completely separate data source aggregation or a self-join outside Tableau to answer this question.",
    "The interviewer wants to see you can connect the abstract mechanism to a real 'cohort/customer-level metric shown alongside row-level detail' business problem.",
    "Use a customer-level metric (like order count per customer) shown in a row-level view as your example.",
  ),
  interview(
    3,
    15,
    "When would you use a data blend instead of a join, and what's the key limitation of blending?",
    "I'd blend when combining two data sources that live in genuinely separate connections and have different levels of granularity — for example, transaction-level sales data from a SQL database blended with a small spreadsheet of regional targets at the region level. Blending aggregates the secondary source up to the shared linking dimension before combining, which handles that granularity mismatch cleanly, whereas a join would either explode rows or fail to align properly. The key limitation is that once blended, you lose access to the secondary source's row-level detail — you can only use its aggregated measures at the linking level, and certain calculations (especially LOD expressions referencing the secondary source) don't work as expected, so I try to join within a single source whenever the granularities actually match.",
    "This checks whether the candidate treats blending as a genuine architectural decision, not a fallback used out of confusion with joins.",
    "Center your answer on granularity mismatch across separate connections, and name the row-level-detail tradeoff explicitly.",
  ),
  interview(
    4,
    15,
    "How would you design a dashboard so it stays performant with a large dataset?",
    "First, I'd use an extract rather than a live connection where possible, since Tableau's .hyper engine is optimized for query speed and lets me pre-aggregate or filter out unneeded columns/rows at extract time. I'd apply extract filters and context filters early to shrink the working data set, avoid unnecessary high-cardinality fields on Detail (which explode the number of marks), and limit the number of quick filters, especially ones that force expensive independent queries — using dashboard actions instead of filters where interactivity is needed. I'd also minimize the number of worksheets crammed onto one dashboard, use fewer, well-chosen visual encodings, and test with the Performance Recorder to find and fix the actual slow queries or calculations rather than guessing.",
    "This tests real-world tradecraft: whether the candidate has actually diagnosed and fixed a slow dashboard, not just recited buzzwords.",
    "Mention extracts, filter order, mark count, and the Performance Recorder as concrete tools.",
  ),
  interview(
    5,
    15,
    "Explain the difference between a table calculation and an LOD expression.",
    "A table calculation operates on the data that is already aggregated and rendered in the view — it works on the visible result set, respecting (or configurable relative to) the order and partitioning of marks already shown, which is why things like running total, percent of total, and rank are table calculations: they need to know about the other rows currently in the view. An LOD expression, by contrast, is computed by the data engine at query time, at a granularity you specify independently of the view (finer or coarser), before the table calculation stage even happens. In short, LOD expressions change what gets computed and at what grain; table calculations change how already-computed values are further processed relative to each other in the view.",
    "The interviewer is checking whether the candidate understands Tableau's actual order of operations, not just that both are 'advanced calculation types'.",
    "Emphasize the query-time (LOD) versus view-rendering-time (table calc) distinction.",
  ),
  interview(
    6,
    15,
    "Walk through how you'd build a dashboard showing year-over-year sales growth by region with drill-down.",
    "I'd start with a bar or line chart of Sales by Region and Year, then add a calculated field for YoY growth, either a table calculation ('Percent Difference' from the prior year along the date axis) or a LOD-based calculation if I need it independent of the exact view granularity. I'd put Region on the initial view at a summary level, then build a second, more detailed sheet (e.g. by Sub-Region or Product Category) and connect the two with a filter action triggered by clicking a region's bar, so clicking 'West' filters the detail sheet down to West's breakdown — that's the drill-down. I'd add a reset/'Show All' button and clear tooltips or a title change so users understand what they clicked and how to get back to the full view.",
    "This tests whether the candidate can translate a vague business ask into concrete Tableau mechanics: table calc for YoY, filter actions for drill-down.",
    "Name the specific YoY calculation type and the specific action (filter action) used for the drill-down.",
  ),
  interview(
    7,
    15,
    "How would you use parameters to let a user dynamically switch which measure is displayed?",
    "I'd create a string parameter listing the measure names a user can choose (e.g. 'Sales', 'Profit', 'Quantity'), expose it as a dropdown control on the dashboard, and then write a calculated field with a CASE or IF statement that returns the corresponding measure based on the parameter's current value — for example, CASE [Measure Selector] WHEN 'Sales' THEN SUM([Sales]) WHEN 'Profit' THEN SUM([Profit]) END. I'd drop that calculated field onto the shelf instead of a hardcoded measure, so changing the parameter instantly swaps what's plotted, and I'd usually also update the axis title dynamically to reflect the current selection so it doesn't look mislabeled.",
    "This checks whether the candidate knows parameters aren't tied to a single field and can drive a swappable calculated field — a very common real dashboard pattern.",
    "Mention the CASE/IF calculated field pattern that maps the parameter value to a chosen measure.",
  ),
  interview(
    8,
    15,
    "Explain the difference between an extract and a live connection and the tradeoffs of each.",
    "An extract is a compressed, optimized snapshot of the data pulled into Tableau's in-memory .hyper engine; it's fast, works offline, and reduces load on the source database, but the data is only as fresh as the last scheduled refresh, so it's a poor fit for real-time dashboards. A live connection queries the source system directly every time the view is interacted with, so the data is always current, but performance depends entirely on the underlying database's speed and can add real query load to production systems if not carefully governed. In practice I default to extracts for most reporting dashboards and reserve live connections for cases where near-real-time accuracy genuinely matters and the source can handle the query volume.",
    "The interviewer wants to see the candidate weigh freshness versus performance/load rather than picking one dogmatically.",
    "Frame it explicitly as a tradeoff between data freshness and query performance/source load.",
  ),
  interview(
    9,
    15,
    "How do you validate that a Tableau viz's numbers match the underlying source data?",
    "I start by cross-checking a small, simple aggregate — like total row count or a grand total sum — directly against a query run in the source system (SQL, or the raw file) to make sure the connection itself and any joins/blends aren't duplicating or dropping rows. Then I check that filters (extract filters, data source filters, context filters, and view-level filters) are applied consistently between my validation query and the dashboard, since a mismatch there is the most common cause of numbers not matching. I also review any calculated fields and LOD expressions for logic errors, and if numbers still disagree, I isolate the discrepancy by building a stripped-down worksheet with minimal dimensions/filters to narrow down exactly which layer (join, filter, calculation) introduces the difference.",
    "This tests whether the candidate has a systematic debugging process for a very common, high-stakes real-world problem: stakeholders not trusting the numbers.",
    "Start from a simple total, then narrow the discrepancy down layer by layer (joins, filters, calculations).",
  ),
  interview(
    10,
    15,
    "Explain how filter order of operations works in Tableau and why it matters.",
    "Tableau applies filters in a defined pipeline: extract filters run first (restricting what's even pulled into the extract), then data source filters (applied to every sheet using that source), then context filters (which are computed and materialized before anything below them, effectively creating a temporary independent dataset), then dimension filters, then measure filters, and finally table calculation filters last, after aggregation. This matters because a context filter changes the 'universe' that subsequent filters, LOD FIXED expressions, and top-N calculations operate against — for instance, a Top 10 Products filter needs to run against an already-context-filtered region, or it will pick the top 10 across all regions instead of within the selected one. Misunderstanding this order is a very common source of 'my Top N filter isn't working correctly' bugs.",
    "This is a favorite real interview question because it distinguishes candidates who've only used filters casually from those who understand how they interact with LOD expressions and Top-N logic.",
    "Walk through the pipeline in order and give the classic Top-N-inside-context-filter example.",
  ),
  interview(
    11,
    15,
    "How would you design a dashboard for a mobile/tablet audience versus desktop?",
    "I'd use Tableau's Device Designer to build a separate mobile layout rather than assuming the desktop layout will just resize well, prioritizing a single-column, vertically stacked arrangement since mobile users scroll rather than scan a wide grid. I'd simplify: fewer charts, larger touch targets for filters and buttons, bigger font sizes, and I'd often replace a dense filter panel with a single top-level parameter or a simplified sheet, since small quick-filter lists are hard to tap accurately. I'd also test actual load performance on mobile networks, since a dashboard with many marks or a live connection that's fine on desktop wifi can feel sluggish on a phone.",
    "This checks whether the candidate has hands-on experience with Tableau's device-specific layout tools, not just responsive-design platitudes.",
    "Name the Device Designer feature and the specific simplifications (fewer charts, bigger touch targets) mobile requires.",
  ),
  interview(
    12,
    15,
    "How would you use actions to build an interactive drill-through experience between two sheets?",
    "I'd build a summary sheet (e.g. Sales by Region) and a detail sheet (e.g. transaction-level records or a Sub-Category breakdown), place both on a dashboard, and add a filter action triggered on 'select' from the summary sheet targeting the detail sheet, so clicking a region filters the detail view down to just that region. I'd typically clear the selection to show 'nothing selected = show all' behavior, and add a clear/reset button or instruct via a 'click a region to drill in' title so users know it's interactive. For a true drill-through to a separate dashboard entirely, I'd use a 'Go to sheet' navigation action or a filter action targeting a different dashboard, carrying the selected value along as the filter context.",
    "The interviewer wants concrete mechanics — filter action on select, target sheet, and how to handle the 'nothing selected' state — not just 'I'd use an action'.",
    "Specify the action type (filter action on select) and what happens when nothing is selected.",
  ),
  interview(
    13,
    15,
    "What's your process when a stakeholder asks for 'just one more chart' on an already crowded dashboard?",
    "I first try to understand the actual question behind the request — often 'one more chart' is really asking for an answer that could be added as a tooltip, a filter, or a drill-down interaction rather than a whole new visual, so I ask what decision they're trying to make with it. If a genuinely new chart is warranted, I look at what could be removed, consolidated, or moved to a secondary tab/story point instead of just appending it, since dashboard clutter degrades both usability and performance. I'll often propose a small-multiples or a toggle/parameter-driven approach so multiple views can share the same space rather than stacking indefinitely, and I make the tradeoff explicit to the stakeholder rather than silently cramming it in.",
    "This tests communication and design judgment under real stakeholder pressure, not just Tableau mechanics.",
    "Push back gently by asking what decision the new chart supports, and offer a consolidation alternative.",
  ),
  interview(
    14,
    15,
    "Explain when you'd choose a dual-axis combo chart versus two separate charts.",
    "I'd use a dual-axis combo chart when the two measures are conceptually linked and comparing them side-by-side, aligned on the same category axis, adds direct insight — like bars for Sales and a line overlay for Profit Ratio on the same months, where seeing them together reveals a story (e.g. sales up but margin down). I'd use two separate charts when the measures have very different scales that would mislead if forced onto a shared category axis, when combining them would create visual clutter that hides the pattern rather than revealing it, or when the two measures aren't meant to be directly compared point-by-point at all. Dual-axis is a tool for a specific comparative story, not a default way to save space.",
    "Good answers show design judgment about when combining encodings clarifies versus when it just adds noise.",
    "Anchor your answer on whether the two measures tell one combined story or two separate ones.",
  ),
  interview(
    15,
    15,
    "How would you explain the difference between Tableau Desktop, Server, and Public to someone new to the tool?",
    "Tableau Desktop is the authoring application installed locally where you build workbooks, connect to data, and design dashboards. Tableau Server (or its cloud-hosted equivalent, Tableau Cloud) is where finished workbooks get published so an organization can govern permissions, schedule data refreshes, and let people view and interact with dashboards in a browser without needing Desktop installed themselves. Tableau Public is a free, cloud-hosted version meant for publicly shareable, non-sensitive data — anything published there is visible to the world, so it's used for portfolios, journalism, and open datasets rather than internal business data, and it lacks the governance/security features of Server or Cloud.",
    "This checks whether the candidate can clearly communicate the product landscape to a non-technical audience, a common real responsibility for a BI analyst.",
    "Cover authoring (Desktop) versus governed internal hosting (Server/Cloud) versus public/free hosting (Public).",
  ),
];

export const TABLEAU_COURSE: Course = {
  rounds: [
    {
      number: 1,
      title: "Round 1: Foundations",
      summary:
        "Core Tableau concepts: dimensions/measures, shelves and marks, calculated fields and table calculations, LOD expressions, filters/sets/groups, joins vs blends, and publishing.",
      topics: ["Fundamentals"],
      steps: round1Steps,
    },
    {
      number: 2,
      title: "Round 2: Interview Prep",
      summary:
        "Open-ended, real interview-style questions about LOD expressions, dashboard design, performance, and interactivity for a BI / Data Visualization Analyst role.",
      topics: ["Tableau Interview Prep"],
      steps: round2Steps,
    },
  ],
};
